import 'package:dio/dio.dart';

/// The one hand-written piece every generated provider ultimately reads
/// from: a `Dio` instance pointed at a real server. Everything
/// downstream of this — types, the `CratestackClientAdapter`, every
/// `@riverpod` provider (`boardProvider`, `boardListProvider`,
/// `BoardCreateController`, ...) — is generated by `--preset riverpod`
/// (see `../../client/`); this file is not "provider code", it's wiring
/// a base URL and a stand-in auth header, matching the ticket's
/// zero-hand-written-providers bar.
///
/// Stand-in for real auth (a session cookie, a bearer token, an OAuth
/// flow — anything a production app would use). The reused
/// `react-vite-swr` schema's `@@allow(..., auth() != null)` rules only
/// need SOME authenticated caller, and that example's server
/// (`../../react-vite-swr/src/lib.rs`'s `HeaderAuthProvider`) reads this
/// header as `auth().id` — a fixed header is enough to demonstrate the
/// generated surface without building a login screen, which is out of
/// scope here (see the README).
Dio buildAppDio({String baseUrl = 'http://127.0.0.1:3210'}) {
  final dio = Dio(BaseOptions(baseUrl: baseUrl));
  dio.options.headers['x-auth-id'] = '1';
  return dio;
}
