//! Assembles the final `.proto` file text from already-rendered blocks:
//! the file header/disclaimer, `syntax`/`package`, imports, then enums,
//! messages, and (grpc-only) the `service` block in that order. Split out
//! of `mod.rs` — which stays orchestration-only — per the repo's 200-LoC
//! convention.

use cratestack_core::{Schema, TransportStyle};

pub(super) fn render_file(
    schema: &Schema,
    schema_path: &str,
    package: &str,
    needs_timestamp_import: bool,
    enum_blocks: &[String],
    message_blocks: &[String],
    service_block: Option<&str>,
) -> String {
    let mut out = String::new();
    out.push_str("// Code generated by `cratestack generate-proto`. DO NOT EDIT BY HAND.\n");
    out.push_str("//\n");
    push_transport_disclaimer(&mut out, schema, schema_path);
    out.push_str("//\n");
    out.push_str(
        "// Field presence: every non-repeated field below is `optional` (proto3 explicit\n",
    );
    out.push_str("// presence), representing CrateStack's partial `fields`/`include` projection\n");
    out.push_str("// where a field can be genuinely absent. `repeated` (list) fields are the\n");
    out.push_str("// documented exception — proto3 forbids `repeated optional` — so an empty\n");
    out.push_str("// list and an unprojected/absent list read identically on this wire. See\n");
    out.push_str("// docs/design/protobuf.md §4.4.\n");
    out.push('\n');
    out.push_str("syntax = \"proto3\";\n\n");
    out.push_str(&format!("package {package};\n"));
    if needs_timestamp_import {
        out.push('\n');
        out.push_str("import \"google/protobuf/timestamp.proto\";\n");
    }

    for block in enum_blocks {
        out.push('\n');
        out.push_str(block);
    }
    for block in message_blocks {
        out.push('\n');
        out.push_str(block);
    }
    if let Some(service) = service_block {
        out.push('\n');
        out.push_str(service);
    }

    out
}

/// `transport grpc` schemas: this file *is* the wire (once the
/// `cratestack-grpc` runtime — #171 — lands; there's no runtime yet, so
/// this is phrased to stay true before and after that ships, per ticket
/// #170). `rest`/`rpc` schemas keep ticket #169's original "shape only, not
/// the wire" disclaimer unchanged — the server there speaks CBOR/JSON, and
/// a `.proto` that implied otherwise would be actively misleading.
fn push_transport_disclaimer(out: &mut String, schema: &Schema, schema_path: &str) {
    if schema.transport == TransportStyle::Grpc {
        out.push_str(&format!(
            "// Generated from `{schema_path}`, which declares `transport grpc`.\n"
        ));
        out.push_str(
            "// This file describes both the message shapes AND, via the `service` block\n",
        );
        out.push_str(
            "// below, the RPC contract this schema's `transport grpc` binding serves — it\n",
        );
        out.push_str(
            "// IS the wire, not just a shape description. See the CrateStack gRPC runtime\n",
        );
        out.push_str("// docs for current server/client support status.\n");
        return;
    }
    out.push_str(&format!(
        "// Describes message *shape* only, generated from `{schema_path}`.\n"
    ));
    out.push_str(&format!(
        "// This schema's `transport` is `{}`, not `grpc`, so this\n",
        schema.transport.as_str()
    ));
    out.push_str("// file does NOT describe the bytes on the wire: the server speaks CBOR/JSON,\n");
    out.push_str("// not protobuf. See docs/design/protobuf.md §5.\n");
}
