//! `.proto` text emission — ticket #169 Parts B/C. Messages and enums only;
//! no `service` block (that's ticket #170, which needs a third
//! `TransportStyle` variant that doesn't exist yet).
//!
//! [`synthesize_messages`] is Part B: it derives the field lists for every
//! message this crate's [`crate::build_lock`] doesn't already cover from
//! `schema.models`/`schema.types` alone (`Create<M>Input`,
//! `Update<M>Input`, `<Procedure>Input`, `<Procedure>Output`,
//! `PageOf<Item>`, `PageInfo`). [`emit_proto`] is Part C: it turns a schema
//! plus an already-built [`crate::PbLock`] plus that same synthesized-field
//! map into `.proto` source text, reading field/variant numbers from the
//! lock rather than recomputing them.
//!
//! Callers (ticket #169's CLI) are expected to call `synthesize_messages`
//! once, feed its output to both `build_lock` (as `extra_messages`) and
//! `emit_proto`, in that order — see `docs/design/protobuf.md` §5 and the
//! ticket's Part D pseudocode.

mod enum_render;
mod error;
mod field;
mod message;
mod mirror;
mod scalar;
mod synth;
mod synth_page;
#[cfg(test)]
mod tests;

use std::collections::BTreeMap;

use cratestack_core::{Field, Schema};

pub use error::ProtoEmitError;
pub use synth::synthesize_messages;

use crate::PbLock;
use mirror::{visible_model_fields, visible_type_fields};

pub fn emit_proto(
    schema: &Schema,
    lock: &PbLock,
    extra_messages: &BTreeMap<String, Vec<Field>>,
    schema_path: &str,
) -> Result<String, ProtoEmitError> {
    let package = lock
        .package
        .as_deref()
        .ok_or(ProtoEmitError::MissingPackage)?;

    let mut bodies: BTreeMap<String, Vec<&Field>> = BTreeMap::new();
    for model in &schema.models {
        bodies.insert(model.name.clone(), visible_model_fields(model));
    }
    for ty in &schema.types {
        bodies.insert(ty.name.clone(), visible_type_fields(ty));
    }
    for (name, fields) in extra_messages {
        bodies.insert(name.clone(), fields.iter().collect());
    }

    let mut enums_by_name: BTreeMap<&str, &cratestack_core::EnumDecl> = BTreeMap::new();
    for enum_decl in &schema.enums {
        enums_by_name.insert(enum_decl.name.as_str(), enum_decl);
    }

    let mut needs_timestamp_import = false;
    let mut enum_blocks = Vec::with_capacity(enums_by_name.len());
    for (name, decl) in &enums_by_name {
        let enum_lock = lock
            .enums
            .get(*name)
            .ok_or_else(|| ProtoEmitError::MissingEnumLock((*name).to_owned()))?;
        enum_blocks.push(enum_render::render_enum(decl, enum_lock)?);
    }

    let mut message_blocks = Vec::with_capacity(bodies.len());
    for (name, fields) in &bodies {
        let message_lock = lock
            .messages
            .get(name)
            .ok_or_else(|| ProtoEmitError::MissingMessageLock(name.clone()))?;
        let rendered = message::render_message(name, fields, &message_lock.fields)?;
        needs_timestamp_import |= rendered.needs_timestamp_import;
        message_blocks.push(rendered.text);
    }

    Ok(render_file(
        schema,
        schema_path,
        package,
        needs_timestamp_import,
        &enum_blocks,
        &message_blocks,
    ))
}

fn render_file(
    schema: &Schema,
    schema_path: &str,
    package: &str,
    needs_timestamp_import: bool,
    enum_blocks: &[String],
    message_blocks: &[String],
) -> String {
    let mut out = String::new();
    out.push_str("// Code generated by `cratestack generate-proto`. DO NOT EDIT BY HAND.\n");
    out.push_str("//\n");
    out.push_str(&format!(
        "// Describes message *shape* only, generated from `{schema_path}`.\n"
    ));
    out.push_str(&format!(
        "// This schema's `transport` is `{}` (no `grpc` transport exists yet), so this\n",
        schema.transport.as_str()
    ));
    out.push_str("// file does NOT describe the bytes on the wire: the server speaks CBOR/JSON,\n");
    out.push_str("// not protobuf. See docs/design/protobuf.md §5.\n");
    out.push_str("//\n");
    out.push_str(
        "// Field presence: every non-repeated field below is `optional` (proto3 explicit\n",
    );
    out.push_str("// presence), representing CrateStack's partial `fields`/`include` projection\n");
    out.push_str("// where a field can be genuinely absent. `repeated` (list) fields are the\n");
    out.push_str("// documented exception — proto3 forbids `repeated optional` — so an empty\n");
    out.push_str("// list and an unprojected/absent list read identically on this wire. See\n");
    out.push_str("// docs/design/protobuf.md §4.4.\n");
    out.push('\n');
    out.push_str("syntax = \"proto3\";\n\n");
    out.push_str(&format!("package {package};\n"));
    if needs_timestamp_import {
        out.push('\n');
        out.push_str("import \"google/protobuf/timestamp.proto\";\n");
    }

    for block in enum_blocks {
        out.push('\n');
        out.push_str(block);
    }
    for block in message_blocks {
        out.push('\n');
        out.push_str(block);
    }

    out
}
