FROM rust:1.88 AS web-build
RUN cargo install trunk
RUN rustup target add wasm32-unknown-unknown
RUN npm install -g pnpm
WORKDIR /app
COPY . .
RUN cd web && pnpm install && trunk build --release

FROM rust:1.88 AS backend-build
WORKDIR /app
COPY . .
RUN cargo build -p {{ workspace.backend_crate_name }} --release

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=backend-build /app/target/release/{{ workspace.backend_binary_name }} /usr/local/bin/{{ workspace.backend_binary_name }}
COPY --from=web-build /app/web/dist /app/web/dist
EXPOSE 3000
CMD ["{{ workspace.backend_binary_name }}"]
