set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

# Postgres connection used by every PG-backed integration test
# (banking_*.rs, policy_db_*.rs, generated_client_rust.rs, etc.).
# Matches the compose.yml mapping — port 55432 chosen so it doesn't
# fight any locally-running pg.
PG_URL := "postgres://cratestack:cratestack@localhost:55432/cratestack_test"

# Clippy lints allowed workspace-wide (shared by `lint` and `all-checks`).
# Each is a deliberate stance for a schema-codegen framework, not a
# blanket mute:
#   * too_many_arguments  — generated `const fn` constructors and internal
#     per-item helpers take one positional arg per field/concern.
#   * type_complexity     — sqlx query-result tuples and generated bounds.
#   * manual_async_fn     — examples/tests return `impl Future` by hand.
#   * missing_safety_doc  — only ever fires in the FFI example crates;
#     library `unsafe` is forbidden workspace-wide.
clippy_allow := "-A clippy::too_many_arguments -A clippy::type_complexity -A clippy::manual_async_fn -A clippy::missing_safety_doc"

default:
  @just --list


# Canonical pre-PR gate: format, lint, and check.
#
# Two deliberate scoping choices, both load-bearing:
#   * `--exclude embedded_flutter_native` — that crate has an
#     unconditional `mod frb_generated;` whose source is generated by
#     `flutter_rust_bridge_codegen` and is NOT checked in, so any
#     workspace-wide compile that includes it fails with E0583 on a
#     fresh checkout. The test recipes exclude it for the same reason.
#   * NO `--all-features` — `--all-features` turns on both
#     `decimal-rust-decimal` and `decimal-bigdecimal`, which are
#     mutually exclusive backends (cratestack#495), tripping a
#     `compile_error!` in cratestack-core. Default features select
#     `decimal-rust-decimal`; pass `--features decimal-bigdecimal
#     --no-default-features` on individual `-p` invocations to build
#     against the other one instead.
all-checks:
	@echo "Running Rust formatting, lint, and checks"
	just _fmt
	cargo fix --workspace --exclude embedded_flutter_native --allow-dirty
	cargo clippy --workspace --exclude embedded_flutter_native --all-targets --fix --allow-dirty -- -D warnings {{clippy_allow}}
	cargo check --workspace --exclude embedded_flutter_native --all-targets
	cargo deny check

# Run rustfmt over every workspace member EXCEPT embedded_flutter_native.
# `cargo fmt` has no `--exclude`, and that crate's `mod frb_generated;`
# source is generated by flutter_rust_bridge and not checked in — so a
# plain `cargo fmt` / `--all` fails rustfmt module resolution on a fresh
# checkout. Enumerate the members from `cargo metadata` instead. Pass
# `--check` to verify formatting without writing.
_fmt extra='':
	#!/usr/bin/env bash
	set -euo pipefail
	# Capture in a command substitution (not process substitution) so a
	# failure of cargo-metadata or python aborts the recipe under
	# `set -e`/pipefail instead of silently yielding an empty list — an
	# empty list would make `cargo fmt` format the whole workspace
	# (including the Flutter crate) and fail on its missing module.
	pkgs=$(cargo metadata --no-deps --format-version 1 \
	  | python3 -c "import json,sys;print(' '.join(x['name'] for x in json.load(sys.stdin)['packages'] if x['name']!='embedded_flutter_native'))")
	args=()
	for p in $pkgs; do args+=(-p "$p"); done
	if [ ${#args[@]} -eq 0 ]; then
	  echo "_fmt: no workspace packages resolved from cargo metadata" >&2
	  exit 1
	fi
	cargo fmt "${args[@]}" {{extra}}

# Type-check the whole workspace. Blocking CI gate. Same `--exclude`
# (Flutter glue → E0583) and no-`--all-features` (mutually-exclusive
# `decimal-*` backends → compile_error!) scoping as `all-checks`.
# Extra args pass through (CI appends `--locked` to catch lockfile drift).
check *args='':
	cargo check --workspace --exclude embedded_flutter_native --all-targets {{args}}

# Clippy as `-D warnings` — blocking CI gate. `clippy_allow` permits a
# small, documented set of codegen-friendly lints (see top of file).
lint:
	cargo clippy --workspace --exclude embedded_flutter_native --all-targets -- -D warnings {{clippy_allow}}

# Verify formatting without writing — blocking CI gate.
fmt-check:
	just _fmt --check

# Feature-graph regression matrix (cratestack#421, cratestack#495) —
# blocking CI gate. Asserts `decimal-rust-decimal`/`decimal-bigdecimal` are
# mutually exclusive (not "neither selectable" — #495 made the second
# backend real), that `cratestack-core`'s default feature set never leaks
# through a `--no-default-features` consumer, and that `rust_decimal` is
# never reachable anywhere in the graph once `decimal-bigdecimal` is
# selected. See `.ci/feature-matrix.sh` for the full rationale and the
# exact commands run.
feature-matrix:
	./.ci/feature-matrix.sh

# Bring the Postgres test container up (idempotent; waits for ready).
pg-up:
	@docker compose up -d postgres >/dev/null
	@until docker exec cratestack-postgres pg_isready -U cratestack -d cratestack_test >/dev/null 2>&1; do sleep 1; done
	@echo "postgres ready at {{PG_URL}}"

# Stop and remove the Postgres test container (safe when nothing is up).
pg-down:
	@docker compose down >/dev/null
	@echo "postgres stopped"

# Run the full workspace test suite against a real Postgres, with auto-teardown on exit.
# `--features cratestack-migrate/postgres-introspect` opts just that one
# workspace member into its feature-gated live-introspection tests
# (issue #204) — the default `--workspace` feature set otherwise leaves
# `cratestack-migrate` on its DB-dependency-free default build.
test-pg *args='':
	#!/usr/bin/env bash
	set -euo pipefail
	cleanup() { docker compose down >/dev/null 2>&1 || true; echo "postgres stopped"; }
	trap cleanup EXIT
	just pg-up
	CRATESTACK_TEST_DATABASE_URL='{{PG_URL}}' cargo test --workspace --exclude embedded_flutter_native --features cratestack-migrate/postgres-introspect {{args}}

# Run only the cratestack-pg integration tests against PG (faster inner loop).
# Targets the server-facade package explicitly — the workspace also
# ships a documentation-only `cratestack` vitrine crate, so
# `-p cratestack` would silently select the empty crate and return a
# false-green here.
test-pg-only *args='':
	#!/usr/bin/env bash
	set -euo pipefail
	cleanup() { docker compose down >/dev/null 2>&1 || true; echo "postgres stopped"; }
	trap cleanup EXIT
	just pg-up
	CRATESTACK_TEST_DATABASE_URL='{{PG_URL}}' cargo test -p cratestack-pg {{args}}

# Run the workspace test suite via testcontainers (per-binary ephemeral PG, recommended for CI).
test-pg-tc *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test --workspace --exclude embedded_flutter_native {{args}}

# --- CI test shards -------------------------------------------------------
# CI runs the suite as four parallel shards (see .github/workflows/ci.yml)
# so no single runner compiles the whole workspace — the tauri/wasm/napi
# example crates otherwise push the runner past its disk limit. Each shard
# is also usable locally.

# Shard: the Postgres-backed crate via testcontainers.
# (cratestack-redis no longer rides along here: it has its own blocking
# `tests-redis` job backed by the `test-ci-redis` recipe below.)
test-ci-db *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-pg {{args}}

# Shard: the Redis-backed crate via testcontainers (issue #418). Idempotency
# and rate-limit stores are the primitives the `banking_*` fixtures lean on
# for correctness under retries/concurrency, so this mirrors `test-ci-db`'s
# testcontainers pattern one-for-one rather than riding along in the host
# shard, where the tests used to skip silently for lack of a Redis.
test-ci-redis *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-redis {{args}}

# Shard: the Studio crate, whose api_smoke tests assert the Trunk-built UI
# is embedded. CI runs `trunk build` first; no database needed.
test-ci-studio *args='':
	cargo test -p cratestack-studio {{args}}

# Shard: everything else — the remaining framework crates + light example
# smoke tests, with no container, no wasm/desktop toolchain, and no GTK.
# Uses --exclude (a denylist) rather than -p so inline `#[cfg(test)]` unit
# tests in crates without a tests/ dir (core, parser, sqlx, macros, …) keep
# running. Excludes the three shards above, the flutter glue crate, and the
# heavy example crates that have zero tests (already compiled by `check` and
# the `embedded-examples` gate).
test-ci-host *args='':
	#!/usr/bin/env bash
	set -euo pipefail
	cargo test --workspace \
		--exclude embedded_flutter_native \
		--exclude cratestack-pg \
		--exclude cratestack-redis \
		--exclude cratestack-studio \
		--exclude tauri-web-shell-example \
		--exclude tauri-native-shell-example \
		--exclude tauri-web-wasm-example \
		--exclude embedded-browser-vite-example \
		--exclude embedded-browser-vite-pwa-example \
		--exclude embedded-browser-webpack-example \
		--exclude react-vite-daisyui-example \
		--exclude react-nextjs-daisyui-wasm \
		--exclude react-nextjs-daisyui-napi \
		--exclude embedded-expo-native {{args}}

# Report-only: surfaces the current pass/fail state of every `#[ignore]`d
# test without blocking CI (2026-08 policy-layer coverage audit, Phase 3 —
# nothing else in this repo ever runs or surfaces an ignored test, which is
# exactly how four policy-enforcement tests, two of them catching REAL
# authorization bugs, went unrun for months: `git grep -rn "\-\-include-ignored\|-- --ignored"`
# matched nothing anywhere in `.github/workflows/` or this justfile before
# this recipe). Reuses `test-ci-db`'s testcontainers Postgres (where every
# DB-backed `#[ignore]` lives) and `test-ci-host`'s exclude list (for
# no-DB ignores, e.g. cratestack-sqlx's characterization test for the
# auth-bypass bug found alongside this mechanism) — deliberately skips
# `cratestack-studio` and the wasm/tauri example crates as this recipe
# has no Trunk/GTK toolchain step of its own. Always exits 0: a red
# ignored test here is not a regression to fix in this job, it's a
# defect (real or stale) to triage in the test's own `#[ignore]` reason —
# see the top-level report this recipe prints for exactly which ones
# failed.
test-ci-ignored-report *args='':
	#!/usr/bin/env bash
	set -uo pipefail
	echo "=== Ignored tests: cratestack-pg (testcontainers Postgres) ==="
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-pg {{args}} -- --ignored --nocapture
	pg_status=$?
	echo ""
	echo "=== Ignored tests: workspace host shard (no DB, no wasm/desktop toolchain) ==="
	cargo test --workspace \
		--exclude embedded_flutter_native \
		--exclude cratestack-pg \
		--exclude cratestack-studio \
		--exclude tauri-web-shell-example \
		--exclude tauri-native-shell-example \
		--exclude tauri-web-wasm-example \
		--exclude embedded-browser-vite-example \
		--exclude embedded-browser-vite-pwa-example \
		--exclude embedded-browser-webpack-example \
		--exclude react-vite-daisyui-example \
		--exclude react-nextjs-daisyui-wasm \
		--exclude react-nextjs-daisyui-napi \
		--exclude embedded-expo-native {{args}} -- --ignored --nocapture
	host_status=$?
	echo ""
	echo "=== Ignored-test report summary ==="
	if [ "$pg_status" -ne 0 ] || [ "$host_status" -ne 0 ]; then
		echo "One or more #[ignore]d tests failed to run cleanly (pg shard exit=$pg_status, host shard exit=$host_status)."
		echo "This is expected for any test whose #[ignore] reason says REAL BUG — read that reason string before treating a red result here as new."
	else
		echo "All #[ignore]d tests ran clean (0 failures) — every one of them is a candidate to have its #[ignore] removed in a follow-up PR."
	fi
	exit 0

# Verify the Dart client generator's OUTPUT actually compiles, not just
# that its generated text matches a Rust-side snapshot (issue #300).
# Generates a REST and an RPC package during the run from committed
# fixtures (crates/cratestack-client-dart/tests/fixtures/ci_{rest,rpc}.cstack
# — multiple models, an enum, a relation, and a procedure each) via the
# real `cratestack generate-dart` CLI, then runs `flutter analyze` on
# each. This is the same check CI's `dart (generated packages)` job runs.
#
# Issue #301 extends this to also cover `--preset riverpod`: the same
# ci_rest/ci_rpc fixtures (proving the fan-out layout compiles under both
# transports) plus riverpod_shared_ownership.cstack (a dedicated fixture
# for the ownership rule — an enum genuinely shared by two models, a
# nested type reached only through a procedure, and a User -> Post[] ->
# User relation cycle across two per-model files).
#
# Issue #302 extends the riverpod-preset loop further: every riverpod
# fixture now also runs `dart run build_runner build
# --delete-conflicting-outputs` BEFORE `flutter analyze` — the ticket's
# load-bearing check, since a malformed `@riverpod` annotation surfaces
# as a `build_runner` error, not a `dart analyze` one, so analyze alone
# would not catch it — and `flutter test` after, which actually exercises
# the generated `test/*_test.dart`'s override-propagation proof (a fake
# adapter overrides the existing `xAdapterProvider`, then a generated
# operation provider is read and asserted to have gone through it).
# `riverpod_provider_collision.cstack` is a new fixture in this set: two
# models whose *naive* per-operation provider names would collide, plus a
# procedure that collides with one of the models' own controller name —
# proving the collision escalation in `provider_naming.rs` produces
# distinct names that still compile end to end (not just distinct in a
# Rust-side text assertion).
#
# Issue #303: `build_runner` is no longer invoked as a separate bash line
# here — every riverpod fixture regenerates with `generate-dart`'s own
# `--run-build-runner` flag instead, so this recipe is also the CI proof
# that the flag itself (not just a hand-rolled `dart run build_runner
# build`) actually works end to end against the real pinned toolchain.
# `flutter pub get` still runs as its own step first: `--run-build-runner`
# deliberately runs only the one command the acceptance criteria specify
# (`dart run build_runner build --delete-conflicting-outputs`), not an
# implicit `pub get`, so dependencies must already be resolved before it.
#
# Requires the Flutter SDK on PATH, not just the Dart SDK: the generated
# `pubspec.yaml` depends on `sdk: flutter` (the `flutter`/`flutter_test`
# packages) and `flutter_riverpod` — a standalone Dart SDK install has no
# Flutter pub cache to resolve those against (verified empirically before
# choosing this over `dart-lang/setup-dart`).
verify-dart:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v flutter >/dev/null; then
	  echo "flutter not found on PATH — install the Flutter SDK: https://docs.flutter.dev/get-started/install" >&2
	  exit 1
	fi
	out=target/dart-verify
	rm -rf "$out"

	verify_pkg() {
	  local pkg="$1"
	  echo "=== flutter pub get: $pkg ==="
	  (cd "$pkg" && flutter pub get)
	  echo "=== flutter analyze: $pkg ==="
	  # --fatal-warnings (Dart's own default): a warning-level finding
	  # fails the build — unused imports, dead code, deprecated API use
	  # are real signal on generated code that should never carry them.
	  # --no-fatal-infos: info-level style suggestions don't fail the
	  # build here. `flutter analyze` (unlike plain `dart analyze`)
	  # defaults `--fatal-infos` to ON; the two pre-existing info
	  # findings this surfaced on today's templates (a doc-comment
	  # angle-bracket lint in runtime.dart, and a nullable-narrowing
	  # suggestion on constants.dart's schema-hash constant that's a
	  # structural false positive — the field is `String?` because it
	  # can be null for hash-less configs, even though this particular
	  # generated instance's literal happens to be non-null) are noise,
	  # not evidence the generator is broken, so they don't gate the
	  # build. See the PR that introduced this recipe for the follow-up
	  # issue tracking them.
	  (cd "$pkg" && flutter analyze --fatal-warnings --no-fatal-infos)
	}

	# riverpod-preset-only: deliberately does NOT call `verify_pkg` (which
	# runs `flutter analyze` first) — `flutter analyze` on a freshly
	# generated riverpod package, before `build_runner` has run, reports
	# real `uri_has_not_been_generated`/`undefined_identifier` errors for
	# every `part '<file>.g.dart'` directive and every `@riverpod`
	# annotation's `ref`/`state` usage (verified empirically; this is
	# exactly the ticket's "a malformed annotation surfaces as a
	# build_runner error, not an analyzer error" risk, but the inverse
	# also holds — analyze alone, run too early, is *always* red here,
	# which would make this recipe permanently fail). Order is therefore
	# pub get -> build_runner -> analyze -> test, matching the acceptance
	# criteria's own "dart analyze is clean AFTER build_runner" wording.
	verify_riverpod_pkg() {
	  local pkg="$1"
	  local schema="$2"
	  local library_name="$3"
	  echo "=== flutter pub get: $pkg ==="
	  (cd "$pkg" && flutter pub get)
	  echo "=== generate-dart --preset riverpod --run-build-runner: $pkg ==="
	  cargo run --quiet -p cratestack-cli -- generate-dart \
	    --schema "$schema" \
	    --out "$pkg" \
	    --library-name "$library_name" \
	    --preset riverpod \
	    --run-build-runner
	  echo "=== flutter analyze (post build_runner): $pkg ==="
	  (cd "$pkg" && flutter analyze --fatal-warnings --no-fatal-infos)
	  echo "=== flutter test: $pkg ==="
	  (cd "$pkg" && flutter test)
	}

	fixtures=(ci_rest ci_rpc)
	for fixture in "${fixtures[@]}"; do
	  pkg="$out/default/$fixture"
	  echo "=== generate-dart --preset default: $fixture -> $pkg ==="
	  cargo run --quiet -p cratestack-cli -- generate-dart \
	    --schema "crates/cratestack-client-dart/tests/fixtures/$fixture.cstack" \
	    --out "$pkg" \
	    --library-name "dart_verify_${fixture}"
	  verify_pkg "$pkg"
	done

	riverpod_fixtures=(ci_rest ci_rpc riverpod_shared_ownership riverpod_provider_collision)
	for fixture in "${riverpod_fixtures[@]}"; do
	  pkg="$out/riverpod/$fixture"
	  schema="crates/cratestack-client-dart/tests/fixtures/$fixture.cstack"
	  library_name="dart_verify_riverpod_${fixture}"
	  echo "=== generate-dart --preset riverpod: $fixture -> $pkg ==="
	  cargo run --quiet -p cratestack-cli -- generate-dart \
	    --schema "$schema" \
	    --out "$pkg" \
	    --library-name "$library_name" \
	    --preset riverpod
	  verify_riverpod_pkg "$pkg" "$schema" "$library_name"
	done

# Verify the TypeScript client generator's OUTPUT actually typechecks,
# not just that its generated text matches a Rust-side snapshot (issue #419).
# Generates a REST and an RPC package during the run from committed
# fixtures (crates/cratestack-client-typescript/tests/fixtures/ci_{rest,rpc}.cstack
# and examples/react-vite-swr/schema.cstack — which uses swr preset over REST)
# via the real `cratestack generate-typescript` CLI, then runs `pnpm build`
# (which invokes `tsc`) on each.
#
# Unlike `dart-verify` which generates on-the-fly from fixtures, the
# REST/swr example already has committed generated output under
# examples/react-vite-swr/client/. That fixture exercises the swr preset
# over REST; this recipe adds an RPC fixture to prove RPC templates
# typecheck too.
verify-typescript:
	#!/usr/bin/env bash
	set -euo pipefail
	out=target/typescript-verify
	rm -rf "$out"

	# Generate and typecheck REST fixture
	pkg="$out/default/rest"
	echo "=== generate-typescript --preset default (REST): ci_rest.cstack -> $pkg ==="
	cargo run --quiet -p cratestack-cli -- generate-typescript \
	  --schema "crates/cratestack-client-typescript/tests/fixtures/ci_rest.cstack" \
	  --out "$pkg" \
	  --preset default \
	  --package-name typescript-verify-rest
	echo "=== npm install and build (typechecks with tsc): $pkg ==="
	(cd "$pkg" && npm install && npm run build)

	# Generate and typecheck RPC fixture
	pkg="$out/default/rpc"
	echo "=== generate-typescript --preset default (RPC): ci_rpc.cstack -> $pkg ==="
	cargo run --quiet -p cratestack-cli -- generate-typescript \
	  --schema "crates/cratestack-client-typescript/tests/fixtures/ci_rpc.cstack" \
	  --out "$pkg" \
	  --preset default \
	  --package-name typescript-verify-rpc
	echo "=== npm install and build (typechecks with tsc): $pkg ==="
	(cd "$pkg" && npm install && npm run build)

	echo ""
	echo "✓ TypeScript REST and RPC fixtures generated and typechecked successfully"

# Regenerate the two committed example clients in place (issue #471).
#
# `examples/flutter-riverpod/client` (via `generate-dart --preset riverpod`)
# and `examples/react-vite-swr/client` (via `generate-typescript --preset
# swr`) are committed generated output, guarded only by a CI `--check` step
# (the `flutter (flutter-riverpod example)` and `js (react-vite-swr
# example)` jobs in `.github/workflows/ci.yml`). Before this recipe existed
# there was no local command that could reconcile a template change
# against them — the only way to find out a template edit had drifted the
# committed examples was to push and read CI (see #444/#470/#471).
#
# `ci.yml`'s `flutter-riverpod-example`/`react-vite-swr-example` drift-check
# steps call this same recipe as `just regen-examples --check` — one
# mechanism, not a hand-copied third invocation — so the recipe and CI
# cannot copy-paste diverge (same `*args=''` passthrough shape as `check`
# above, which CI calls as `just check --locked`). Local, no-arg use
# defaults to write mode.
#
# Unlike `verify-dart`/`verify-typescript` above (which generate throwaway
# packages from fixtures into `target/`), this recipe overwrites the
# committed example directories directly. Run it with no args, review
# `git diff`, and commit the result — a non-empty diff on an otherwise-
# unmodified checkout of `main` means the committed examples have already
# drifted from their templates.
regen-examples *args='':
	cargo run -p cratestack-cli -- generate-dart \
	  --schema examples/react-vite-swr/schema.cstack \
	  --out examples/flutter-riverpod/client \
	  --library-name flutter_riverpod_client \
	  --preset riverpod {{args}}
	cargo run -p cratestack-cli -- generate-typescript \
	  --schema examples/react-vite-swr/schema.cstack \
	  --out examples/react-vite-swr/client \
	  --preset swr \
	  --package-name react-vite-swr-client {{args}}

# Layer-direction check (ADR 0014, docs/adr/0014-layer-direction-enforcement.md)
# — blocking CI gate. Asserts every NORMAL cratestack-* -> cratestack-* edge
# among the crates under `crates/` satisfies `dep.layer <= self.layer`
# against `docs/adr/layers.toml`, with target-gated normal dependencies
# included and dev-/build-dependencies exempt. Known violations are tracked
# in `.ci/layer-direction-allowlist.toml` (currently empty — #475, the
# client-store-{sqlite,redis} -> client-rust back-edge, was the only entry
# and is fixed) and don't fail the build; an allowlist entry that no longer
# matches a real violation does. See `.ci/layer-direction-check.sh` for the
# full rationale.
verify-layering:
	./.ci/layer-direction-check.sh

# Changelog verification: detect unedited seeds.
#
# Ensures that CHANGELOG.md contains no auto-generated seeds with the
# TODO marker still present. This is load-bearing: an unedited seed reaching
# main silently degrades the changelog from prose to a commit list, which is
# worse than today's honest gap (it looks maintained, but isn't).
#
# Blocking CI gate for any PR that touches CHANGELOG.md.
verify-changelog:
	./.ci/changelog-check.sh

# Test changelog-seed.sh and changelog-check.sh against an isolated sandbox
# copy of CHANGELOG.md (never the real, tracked file). Wired into CI so the
# test suite actually runs instead of silently rotting.
changelog-seed-test:
	./.ci/changelog-seed-tests.sh

# Bundle the Studio UI for publishing: source tarball (for `studio
# eject --with-ui`) and the Trunk-built wasm/JS dist (embedded into
# the served binary so `cratestack studio run` ships a real admin app
# out of the box). Both files are gitignored; cargo packages them via
# the explicit `include` list in cratestack-studio's Cargo.toml.
#
# Requires the wasm toolchain:
#   cargo install --locked trunk
#   rustup target add wasm32-unknown-unknown
bundle-studio-ui:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v trunk >/dev/null; then
	  echo "trunk not found. Run: cargo install --locked trunk" >&2
	  exit 1
	fi
	src=crates/cratestack-studio/embedded-ui.tar.gz
	dist=crates/cratestack-studio/embedded-ui-dist.tar.gz
	(cd crates/cratestack-studio-ui && trunk build --release)
	tar --exclude='target' \
	    --exclude='Cargo.lock' \
	    --exclude='.gitignore' \
	    --exclude='.trunk' \
	    --exclude='dist' \
	    -czf "$src" \
	    -C crates cratestack-studio-ui
	tar -czf "$dist" -C crates/cratestack-studio-ui/dist .
	echo "wrote $src ($(du -h "$src" | cut -f1))"
	echo "wrote $dist ($(du -h "$dist" | cut -f1))"

# End-to-end publish for cratestack-studio: refresh the embedded UI
# tarball, then publish. `--allow-dirty` is needed because the
# regenerated tarball is gitignored by design (binary, derived from
# the cratestack-studio-ui sibling); we guard the flag by refusing to
# publish if anything else in the crate is dirty.
publish-studio *args='':
	#!/usr/bin/env bash
	set -euo pipefail
	just bundle-studio-ui
	dirty=$(git status --porcelain -- crates/cratestack-studio crates/cratestack-studio-ui \
	        | grep -vE 'crates/cratestack-studio/embedded-ui(-dist)?\.tar\.gz$' || true)
	if [ -n "$dirty" ]; then
	  echo "refusing to publish: uncommitted changes besides embedded-ui tarballs:" >&2
	  echo "$dirty" >&2
	  exit 1
	fi
	cargo publish -p cratestack-studio --allow-dirty {{args}}

# Rewrite every workspace version literal `0.x.y` -> the given NEW
# version. Reads the current version from the workspace `Cargo.toml`,
# applies the substitution to every `Cargo.toml` in the repo (root +
# crates + examples + studio-ui sibling), and refreshes `Cargo.lock`.
# Idempotent: re-running with the same NEW is a no-op.
bump NEW:
	#!/usr/bin/env bash
	set -euo pipefail
	current=$(awk -F'"' '/^version = /{print $2; exit}' Cargo.toml)
	if [ -z "$current" ]; then
	  echo "could not read current version from Cargo.toml" >&2
	  exit 1
	fi
	if [ "$current" = "{{NEW}}" ]; then
	  echo "already at {{NEW}}; nothing to do"
	  exit 0
	fi
	echo "bumping $current -> {{NEW}}"
	# `perl -i` instead of `sed -i` for portability: BSD sed (macOS)
	# requires `-i ''` while GNU sed (Linux/CI) rejects the empty arg,
	# so a single recipe can't satisfy both. perl's in-place edit is
	# identical across platforms. `quotemeta` on the current version makes
	# its dots match literally rather than as `.` wildcards.
	#
	# Scoped to the VALUE OF A `version =` KEY, on either a package-version
	# line (`^version = "X"`, i.e. the root workspace package and the
	# excluded studio-ui sibling) or a workspace inter-crate dependency line
	# (which always carries `path = "crates/"`). Replacing the bare literal
	# `"X"` everywhere instead — as this recipe used to — also rewrites
	# unrelated third-party dependencies that happen to sit at the same
	# version: bumping 0.7.1 -> 0.7.2 turned `serde_urlencoded = "0.7.1"`
	# (root Cargo.toml) into `"0.7.2"`, which does not exist on crates.io,
	# and the release failed at `cargo update` with "failed to select a
	# version for the requirement `serde_urlencoded = ^0.7.2`". The bug is
	# dormant for most bumps — it only fires when the new workspace version
	# collides with some dependency's — so scope this narrowly rather than
	# relying on the collision not recurring.
	find . -name Cargo.toml \
	  -not -path './target/*' \
	  -not -path '*/node_modules/*' \
	  -print0 | CS_CUR="$current" CS_NEW="{{NEW}}" xargs -0 perl -i -pe '
	    BEGIN { $cur = quotemeta $ENV{CS_CUR}; $new = $ENV{CS_NEW}; }
	    if (/^version = "$cur"/ || m{path = "crates/}) {
	      s/version = "$cur"/version = "$new"/g;
	    }'
	# Keep the @cratestack/cli npm wrapper's version (and the release
	# asset tag it downloads), every package in the split @cratestack/api
	# family (ts-types, link-*, runtime-*, validator-*, adapter-*, and the
	# api compat shim itself), and the @cratestack/cbor family (cbor,
	# cbor-node, cbor-web) in lockstep with the workspace version —
	# scoped to these package.json files, not cratestack-vscode (versioned
	# independently) or the unrelated example apps'. A single
	# literal-string replace (not just the `"version": "..."` key) also
	# catches each package's own pinned `"@cratestack/xyz": "$current"`
	# cross-references to its siblings, which need to move in lockstep too.
	perl -i -pe "s/\Q\"$current\"\E/\"{{NEW}}\"/g" \
	  packages/cratestack-cli-npm/package.json \
	  packages/cratestack-api/package.json \
	  packages/cratestack-ts-types/package.json \
	  packages/cratestack-link-batch/package.json \
	  packages/cratestack-link-logger/package.json \
	  packages/cratestack-runtime-fetch/package.json \
	  packages/cratestack-runtime-axios/package.json \
	  packages/cratestack-validator-zod/package.json \
	  packages/cratestack-validator-yup/package.json \
	  packages/cratestack-adapter-tanstack-query/package.json \
	  packages/cratestack-adapter-rtk/package.json \
	  packages/cratestack-cbor/package.json \
	  packages/cratestack-cbor-node/package.json \
	  packages/cratestack-cbor-web/package.json
	# Refresh pnpm-lock.yaml so the version-literal edits above (which change
	# specifiers like `"@cratestack/ts-types": "{{NEW}}"`) are reflected in the
	# lockfile's `specifier:` entries too — otherwise a later `pnpm install
	# --frozen-lockfile` (every CI job, including release-cli.yml's npm
	# publish) fails with ERR_PNPM_OUTDATED_LOCKFILE. CRATESTACK_CLI_SKIP_DOWNLOAD
	# skips cratestack-cli-npm's postinstall download of a release binary that
	# doesn't exist yet at bump time (nothing has been tagged/published).
	# `--no-frozen-lockfile` is required explicitly: pnpm auto-detects CI
	# environments and defaults to frozen-lockfile there even without the
	# flag, which would make this step fail on the exact staleness it's
	# meant to fix (confirmed the hard way — this recipe's own first version
	# broke `prepare-release.yml`'s "Bump workspace version" step in CI).
	CRATESTACK_CLI_SKIP_DOWNLOAD=1 pnpm install --no-frozen-lockfile
	# Refresh Cargo.lock so all entries pick up the new version.
	# Exclude the Flutter crate (uncommitted frb_generated glue → E0583).
	cargo check --workspace --exclude embedded_flutter_native --quiet
	# cratestack-studio-ui is its own separate `[workspace]` (excluded from
	# the root one so contributors aren't forced onto the wasm32 toolchain),
	# so it has its own Cargo.lock that the check above never touches. Left
	# unrefreshed here, it silently drifts stale — its own recorded version
	# stays behind Cargo.toml's — which then breaks any `--locked` build of
	# that crate until someone notices and hand-fixes it (see #242). A plain
	# `cargo check` on the host target is enough to update the lock; it
	# doesn't need the wasm32 target or a wasm-capable clang for that.
	#
	# Subshell, not a bare `cd`: this recipe continues below with more
	# repo-root-relative paths, and a bare `cd` here leaks its directory
	# change into every one of them. That is exactly what broke `just bump
	# 0.7.9` in `prepare-release.yml` — the next line failed with `cd:
	# examples/no-database-verification: No such file or directory`, because
	# the shell was still sitting in `crates/cratestack-studio-ui`.
	(cd crates/cratestack-studio-ui && cargo check --quiet)
	# `examples/no-database-verification`, `-api`, and
	# `client-only-verification` are each their own `[workspace]` root
	# (excluded from the root one so a real `cargo tree` proves facade
	# disjointness for an external consumer — see their READMEs), so like
	# cratestack-studio-ui above they have their own Cargo.lock that the
	# root `cargo check` never touches. Left unrefreshed here, their locked
	# `cratestack-pg`/`cratestack-api`/`cratestack-client` path-dependency
	# versions silently drift behind the workspace version, which then
	# breaks any `--locked` build/`cargo tree` in either directory — this is
	# exactly the staleness that left them at 0.6.3/0.6.4 against 0.7.8
	# (cratestack#422), and what CI's `facade-disjointness` job now asserts
	# against with `cargo metadata --locked` for all three. Every standalone
	# workspace under examples/ must be listed here; adding one without a
	# line below is a latent CI break that only fires on the next bump.
	# Subshells (not a bare `cd`) so each step's directory change doesn't
	# leak into the next, same as the cratestack-studio-ui step above —
	# every directory-changing step in this recipe must be a subshell, since
	# each is followed by more repo-root-relative paths. A plain
	# `cargo check` in each is enough
	# to refresh the lock; Cargo.lock records the full optional-dependency
	# graph regardless of which features are active, so this also picks up
	# the `postgres`-gated cratestack-sqlx entry in no-database-verification
	# without needing `--features postgres` here.
	(cd examples/no-database-verification && cargo check --quiet)
	(cd examples/no-database-verification-api && cargo check --quiet)
	(cd examples/client-only-verification && cargo check --quiet)
	echo "bumped to {{NEW}}. Review with: git diff -- '**/Cargo.toml' Cargo.lock"

# Seed a CHANGELOG.md section for the given VERSION.
#
# Writes a new `## X.Y.Z (YYYY-MM-DD)` section to CHANGELOG.md, positioned
# above the current newest entry, seeded from the commit range since the last
# release and grouped by conventional-commit type. The section is marked as
# unedited (with a placeholder TODO comment) so CI/tooling can detect it and
# block the merge until a human rewrites it into narrative prose.
#
# Usage: `just changelog-seed 0.7.9`
#
# Non-negotiables (enforced by the script):
#   1. Refuse to write if a section for that version already exists
#   2. The generated section must be detected and rejected by CI if unedited
#
# This script mirrors `.github/workflows/prepare-release.yml:202`'s existing
# commit-range machinery, but outputs to a persistent file instead of
# discarding it.
changelog-seed VERSION:
	./.ci/changelog-seed.sh {{VERSION}}

# Workspace-wide validation gate. Mirrors what `just release` runs
# before publishing. Skips fmt + clippy because `all-checks` is the
# canonical pre-PR gate for those (it auto-fixes); release-check
# focuses on what must hold for a clean publish.
#
# Bundles the Studio UI first (requires trunk + wasm32-unknown-unknown,
# same as `just release-publish`'s own cratestack-studio step needs
# later): without it, `cratestack-studio`'s build.rs falls back to a
# placeholder admin UI, and its own `api_smoke` tests
# (`root_serves_bundled_ui_index_when_feature_on`,
# `unknown_static_path_falls_back_to_index_html`) assert on the REAL
# trunk-built UI and fail on a fresh checkout with no prior local Trunk
# build lying around. On a dev machine that already runs `trunk serve`
# regularly this is usually masked by leftover build artifacts — it only
# reliably surfaces on a clean environment (e.g. CI).
#
# Emergency override: `SKIP_TESTS=1 just release-check` bypasses the
# test stage entirely.
release-check:
	#!/usr/bin/env bash
	set -euo pipefail
	just bundle-studio-ui
	cargo check --workspace --exclude embedded_flutter_native --all-targets
	if [ "${SKIP_TESTS:-0}" = "1" ]; then
	  echo "release-check: SKIP_TESTS=1 — bypassing workspace tests." >&2
	  exit 0
	fi
	cargo test --workspace --exclude embedded_flutter_native

# Publish every workspace crate to crates.io in dependency order.
#
# The order is computed at recipe-time by topologically sorting the
# workspace graph from `cargo metadata`, so it can't drift when a new
# inter-crate dependency lands. Previously a hand-maintained list in
# this file (and in RELEASE.md) silently broke when cratestack-studio
# took on a cratestack-migrate dep but migrate stayed later in the list.
#
# Idempotent: each crate is checked against the crates.io API for the
# current workspace version before publishing — already-uploaded
# versions are skipped, so reruns after a partial failure pick up
# where they left off. Use `FROM=cratestack-studio just release-publish`
# to skip straight to a specific crate without hitting crates.io for
# the earlier ones.
#
# `dry` mode runs `cargo publish --dry-run` (packages + verifies each
# but skips upload). Pairs with `just bump` for the version step and
# `just release` for the full end-to-end flow.
release-publish mode='real':
	#!/usr/bin/env bash
	# Note: `set +e` here — we want to detect "already uploaded" errors
	# rather than abort the whole loop on them. Each command's exit
	# status is checked explicitly.
	set -uo pipefail
	if [ "{{mode}}" != "real" ] && [ "{{mode}}" != "dry" ]; then
	  echo "usage: just release-publish [real|dry]" >&2
	  exit 2
	fi
	# Compute the publish order by topo-sorting cratestack-* workspace
	# packages from `cargo metadata`. Requires python3 (ubiquitous on
	# dev machines). On failure (parse, cycle, missing python) the
	# error is loud and the recipe aborts before touching crates.io.
	#
	# Also computes `dry_safe_packages`: the packages with NO internal
	# cratestack-* dependency at all (currently just `cratestack` and
	# `cratestack-core`). This is the actual set `dry` mode can ever
	# meaningfully package-check for a version that has never been
	# published anywhere before — see the `--allow-dirty`/dry-run
	# handling below for why every other crate is structurally
	# unpackageable in that situation, no matter what flags are passed.
	topo_output=$(cargo metadata --format-version=1 --no-deps 2>/dev/null | \
	  python3 -c "$(cat <<'PYEOF'
	import json, sys, copy
	m = json.load(sys.stdin)
	pkgs = {p["name"]: p for p in m["packages"]
	        if p["name"].startswith("cratestack") and p.get("publish") != []}
	graph = {n: {d["name"] for d in p["dependencies"]
	             if d["name"] in pkgs and d["name"] != n}
	         for n, p in pkgs.items()}
	dry_safe = sorted(n for n, d in graph.items() if not d)
	order, remaining = [], copy.deepcopy(graph)
	while remaining:
	    leaves = sorted(n for n, d in remaining.items() if not d)
	    if not leaves:
	        sys.exit(f"dependency cycle: {remaining}")
	    for n in leaves:
	        order.append(n); del remaining[n]
	    for d in remaining.values():
	        d.difference_update(leaves)
	print(" ".join(order))
	print(" ".join(dry_safe))
	PYEOF
	)")
	publish_order=$(printf '%s\n' "$topo_output" | sed -n '1p')
	dry_safe_packages=$(printf '%s\n' "$topo_output" | sed -n '2p')
	if [ -z "$publish_order" ]; then
	  echo "failed to compute publish order from cargo metadata" >&2
	  exit 1
	fi
	dry=""
	# --no-verify alongside --dry-run: for the handful of packages dry
	# mode does attempt (see dry_safe_packages above), skip the
	# compile-verification step — it's redundant with `release-check`'s
	# own `cargo check --workspace` earlier in the same pipeline, and
	# just wastes time. Real mode is unaffected and still fully
	# verifies each crate.
	[ "{{mode}}" = "dry" ] && dry="--dry-run --no-verify"
	version=$(awk -F'"' '/^version = /{print $2; exit}' Cargo.toml)
	from="${FROM:-}"
	skipping=true
	[ -z "$from" ] && skipping=false

	# Returns 0 if `crate@version` is already published on crates.io.
	# Uses the JSON API; falls back to "not published" on any network
	# error so we surface a fresh publish failure rather than masking it.
	is_published() {
	  local pkg=$1 ver=$2
	  curl -fsS -A "cratestack-release/1.0" \
	    "https://crates.io/api/v1/crates/$pkg/$ver" \
	    -o /dev/null 2>/dev/null
	}

	# Run a single `cargo publish` and classify the outcome:
	#   0 = published or already uploaded (idempotent success)
	#   1 = real failure (caller decides retry vs abort)
	publish_once() {
	  local pkg=$1 extra=$2
	  local out rc
	  out=$(cargo publish -p "$pkg" $extra $dry 2>&1)
	  rc=$?
	  printf '%s\n' "$out"
	  if [ $rc -eq 0 ]; then
	    return 0
	  fi
	  if printf '%s' "$out" | grep -qE 'already (uploaded|exists)'; then
	    echo "  → already uploaded, treating as success"
	    return 0
	  fi
	  return 1
	}

	bundled=false
	bundle_studio() {
	  if [ "$bundled" = "false" ]; then
	    just bundle-studio-ui >&2
	    bundled=true
	  fi
	}

	failed=""
	for pkg in $publish_order; do
	  if [ "$skipping" = "true" ]; then
	    if [ "$pkg" = "$from" ]; then
	      skipping=false
	    else
	      echo "skipping $pkg (before FROM=$from)"
	      continue
	    fi
	  fi

	  echo ""
	  echo "=== $pkg @ $version ==="

	  # Cheap pre-check: if already on crates.io, skip the cargo publish
	  # round-trip entirely. Only meaningful in real mode; dry runs
	  # always want to exercise the package + verify path.
	  if [ "{{mode}}" = "real" ] && is_published "$pkg" "$version"; then
	    echo "  → already on crates.io, skipping"
	    continue
	  fi

	  # A crate with an internal cratestack-* dependency can NEVER be
	  # packaged in dry mode for a version that has never been published
	  # anywhere before: cargo resolves path+version workspace deps
	  # against the REAL crates.io index even just to build the package
	  # manifest (not only to verify/compile it), and a dry-run publish
	  # always "aborts upload" — so an earlier crate's new version never
	  # actually lands in that index for a later one to resolve against.
	  # This is a structural cargo limitation, not fixable with
	  # --allow-dirty/--no-verify/any other flag (confirmed locally: even
	  # RELEASE.md's own `cargo package --allow-dirty --no-verify`
	  # recipe fails identically). Only the packages with zero internal
	  # deps (dry_safe_packages, computed above) can ever be meaningfully
	  # dry-run in this situation — skip everything else with a clear
	  # explanation instead of attempting a guaranteed failure.
	  if [ "{{mode}}" = "dry" ]; then
	    case " $dry_safe_packages " in
	      *" $pkg "*) ;;
	      *)
	        echo "  → skipping dry-run package check: $pkg depends on another"
	        echo "    cratestack-* crate whose new version was never actually"
	        echo "    published (dry-run never uploads) — cargo can't resolve"
	        echo "    that dependency, no matter what flags are passed. See"
	        echo "    release-publish's comments in the justfile for detail."
	        continue
	        ;;
	    esac
	  fi

	  extra=""
	  if [ "{{mode}}" = "dry" ]; then
	    # Dry-run packaging verification is meant to work against an
	    # uncommitted version bump too — e.g. a CI dry-run rehearsal that
	    # deliberately never commits (unlike `just release VERSION dry`,
	    # which always commits the bump first regardless of mode). Never
	    # uploads anything, so allowing a dirty tree here is safe.
	    extra="--allow-dirty"
	  fi
	  if [ "$pkg" = "cratestack-studio" ]; then
	    # Re-bundle right before studio's publish so OUT_DIR matches the
	    # current sibling state, even if a prior loop iteration cleaned it.
	    bundle_studio
	    extra="--allow-dirty"
	  fi

	  if publish_once "$pkg" "$extra"; then
	    continue
	  fi
	  echo "  → first attempt failed; sleeping 30s and retrying once..." >&2
	  sleep 30
	  if publish_once "$pkg" "$extra"; then
	    continue
	  fi
	  failed="$pkg"
	  break
	done

	if [ -n "$failed" ]; then
	  echo "" >&2
	  echo "release-publish failed at $failed." >&2
	  echo "Resume with: FROM=$failed just release-publish {{mode}}" >&2
	  exit 1
	fi

# End-to-end release: bump version, validate, publish all crates, tag,
# and push. Refuses to run on a dirty working tree (besides the
# studio's regenerated tarballs). Tag push is opt-in via PUSH=1.
#
# Usage:
#   just release 0.3.4          # bump, validate, publish, tag locally
#   PUSH=1 just release 0.3.4   # also push commit + tag to origin
#   just release 0.3.4 dry      # rehearsal: dry-run publishes, no tag
release VERSION mode='real':
	#!/usr/bin/env bash
	set -euo pipefail
	if [ "{{mode}}" != "real" ] && [ "{{mode}}" != "dry" ]; then
	  echo "usage: just release VERSION [real|dry]" >&2
	  exit 2
	fi
	just bump {{VERSION}}
	just release-check
	# Commit the bump (unless already committed). Studio tarballs are
	# gitignored by design and don't get staged. `bump` also rewrites the
	# two npm package.json files (cli-npm, api) in lockstep — stage those
	# explicitly too, not just Cargo.toml/Cargo.lock, or their version
	# bumps are silently left uncommitted.
	if ! git diff --quiet -- '**/Cargo.toml' Cargo.lock packages/cratestack-cli-npm/package.json packages/cratestack-api/package.json; then
	  git add ':(glob)**/Cargo.toml' Cargo.lock \
	    packages/cratestack-cli-npm/package.json \
	    packages/cratestack-api/package.json
	  git commit -m "chore: bump workspace to v{{VERSION}}"
	fi
	just release-publish {{mode}}
	if [ "{{mode}}" = "real" ]; then
	  git tag "v{{VERSION}}"
	  if [ "${PUSH:-0}" = "1" ]; then
	    git push origin HEAD "v{{VERSION}}"
	  else
	    echo "tagged v{{VERSION}} locally. Push with: git push origin HEAD v{{VERSION}}"
	  fi
	fi
