set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

# Postgres connection used by every PG-backed integration test
# (banking_*.rs, policy_db_*.rs, generated_client_rust.rs, etc.).
# Matches the compose.yml mapping — port 55432 chosen so it doesn't
# fight any locally-running pg.
PG_URL := "postgres://cratestack:cratestack@localhost:55432/cratestack_test"

# Clippy lints allowed workspace-wide (shared by `lint` and `all-checks`).
# Each is a deliberate stance for a schema-codegen framework, not a
# blanket mute:
#   * too_many_arguments  — generated `const fn` constructors and internal
#     per-item helpers take one positional arg per field/concern.
#   * type_complexity     — sqlx query-result tuples and generated bounds.
#   * manual_async_fn     — examples/tests return `impl Future` by hand.
#   * missing_safety_doc  — only ever fires in the FFI crates/examples that
#     hold a documented `unsafe_code = "allow"` override (napi-derive
#     trampolines, raw C-ABI exports — see EXEMPT_MANUAL_OVERRIDE in
#     `.ci/lints_workspace_check.py`); every other member declares
#     `[lints]\nworkspace = true` (cratestack#523, `just
#     verify-lints-optin`), so `unsafe_code = "forbid"` is actually
#     enforced there, not just documented. Note wasm-bindgen crates
#     (`cratestack-cbor-wasm`, `cratestack-studio-ui`) need no override —
#     verified they compile clean under the forbid.
clippy_allow := "-A clippy::too_many_arguments -A clippy::type_complexity -A clippy::manual_async_fn -A clippy::missing_safety_doc"

default:
  @just --list


# Canonical pre-PR gate: format, lint, and check.
#
# Two deliberate scoping choices, both load-bearing:
#   * `--exclude embedded_flutter_native` — that crate has an
#     unconditional `mod frb_generated;` whose source is generated by
#     `flutter_rust_bridge_codegen` and is NOT checked in, so any
#     workspace-wide compile that includes it fails with E0583 on a
#     fresh checkout. The test recipes exclude it for the same reason.
#     This is a PERMANENT, deliberate exclusion (cratestack#563 decided
#     it, not just re-confirmed it): flutter_rust_bridge glue is
#     generated in CI (and locally via `just frb-generate`, below), never
#     committed.
#
#     `crates/cratestack-client-flutter` is a SECOND frb-bridged crate
#     (cratestack#563's "cratestack-client-flutter absorbs this" decision
#     — the CBOR bridge lives inside the existing crate, not a new
#     `cratestack-cbor-frb`) but does NOT follow this exclusion: its
#     generated `mod frb_generated;` is behind the `frb-glue` Cargo
#     feature (off by default — see `crates/cratestack-client-flutter/
#     src/lib.rs`), so a default `cargo build`/`cargo test -p
#     cratestack-client-flutter` never needs the generated file to exist.
#     Only `--features frb-glue` does (`just frb-verify-client-flutter`,
#     below, exercises that path). This is deliberately NOT the same
#     pattern as `embedded_flutter_native` — verified to keep this crate
#     a normal, always-built, always-tested workspace member instead of
#     joining the exclusion list.
#   * NO `--all-features` — `--all-features` turns on both
#     `decimal-rust-decimal` and `decimal-bigdecimal`, which are
#     mutually exclusive backends (cratestack#495), tripping a
#     `compile_error!` in cratestack-core. Default features select
#     `decimal-rust-decimal`; pass `--features decimal-bigdecimal
#     --no-default-features` on individual `-p` invocations to build
#     against the other one instead.
all-checks:
	@echo "Running Rust formatting, lint, and checks"
	just _fmt
	cargo fix --workspace --exclude embedded_flutter_native --allow-dirty
	cargo clippy --workspace --exclude embedded_flutter_native --all-targets --fix --allow-dirty -- -D warnings {{clippy_allow}}
	cargo check --workspace --exclude embedded_flutter_native --all-targets
	cargo deny check

# Run rustfmt over every workspace member EXCEPT embedded_flutter_native.
# `cargo fmt` has no `--exclude`, and that crate's `mod frb_generated;`
# source is generated by flutter_rust_bridge and not checked in — so a
# plain `cargo fmt` / `--all` fails rustfmt module resolution on a fresh
# checkout. Enumerate the members from `cargo metadata` instead. Pass
# `--check` to verify formatting without writing.
_fmt extra='':
	#!/usr/bin/env bash
	set -euo pipefail
	# Capture in a command substitution (not process substitution) so a
	# failure of cargo-metadata or python aborts the recipe under
	# `set -e`/pipefail instead of silently yielding an empty list — an
	# empty list would make `cargo fmt` format the whole workspace
	# (including the two Flutter crates below) and fail on a missing
	# module.
	#
	# `cratestack-client-flutter` (cratestack#563) needs a placeholder,
	# NOT an exclusion. rustfmt's module resolution does not evaluate
	# `#[cfg(...)]`: its AST walk tries to locate every `mod x;`
	# declaration's file regardless of the cfg gating it sits behind (a
	# real, confirmed rustfmt limitation, not a workaround). So `cargo fmt
	# -p cratestack-client-flutter` fails with "failed to resolve mod
	# `frb_generated`" whenever `src/frb_generated.rs` is missing, even
	# though that `mod` is behind the default-off `frb-glue` feature and
	# `cargo build`/`check`/`clippy`/`test -p cratestack-client-flutter`
	# all succeed without it.
	#
	# Skipping the package when the file is absent looks like it "tracks
	# the file's presence", but the generated glue is gitignored — so it
	# is absent on EVERY fresh checkout, which is exactly the state CI's
	# `rustfmt` job runs in (`just fmt-check` immediately after
	# `actions/checkout`, with no generation step before it). That makes
	# the skip permanent in CI in practice: measured 58 packages formatted
	# instead of 59, with nothing reporting the gap. This crate WAS
	# formatted before frb was wired in, so that would be a silent
	# coverage regression introduced by this ticket.
	#
	# Writing a one-line placeholder just long enough for rustfmt's module
	# resolution keeps the real sources covered. Verified both directions:
	# with the placeholder, `cargo fmt -p cratestack-client-flutter
	# --check` exits 0 on the real tree, and exits 1 reporting a diff when
	# a deliberately misformatted function is added.
	#
	# The placeholder is used whether or not the real glue exists, and that
	# is the point: generated frb output is NOT rustfmt-clean (14k lines,
	# ~30 diffs), so formatting it is both wrong and noisy. An earlier
	# version of this only substituted when the file was absent, which
	# looked right but meant that any developer who ran `just frb-generate`
	# or `just cbor-vendor-native` then hit `just fmt-check` failing on
	# generated code they did not write and must not edit. CI's rustfmt job
	# never caught it because it runs on a fresh checkout where the glue is
	# absent — a local-only breakage.
	#
	# So: stash any real glue aside, format against a placeholder, restore.
	# `trap` covers interruption, so a run killed mid-flight cannot leave
	# the placeholder in place of real glue that a later `--features
	# frb-glue` build would then try to compile.
	frb_glue=crates/cratestack-client-flutter/src/frb_generated.rs
	frb_stash="${frb_glue}.fmt-stash"
	if [ -f "$frb_glue" ]; then
	  mv "$frb_glue" "$frb_stash"
	  trap 'mv -f "'"$frb_stash"'" "'"$frb_glue"'"' EXIT
	else
	  trap 'rm -f "'"$frb_glue"'"' EXIT
	fi
	printf '// Placeholder so rustfmt can resolve `mod frb_generated;`.\n' > "$frb_glue"
	pkgs=$(cargo metadata --no-deps --format-version 1 \
	  | python3 -c "import json,sys;print(' '.join(x['name'] for x in json.load(sys.stdin)['packages'] if x['name'] != 'embedded_flutter_native'))")
	args=()
	for p in $pkgs; do args+=(-p "$p"); done
	if [ ${#args[@]} -eq 0 ]; then
	  echo "_fmt: no workspace packages resolved from cargo metadata" >&2
	  exit 1
	fi
	cargo fmt "${args[@]}" {{extra}}

# Type-check the whole workspace. Blocking CI gate. Same `--exclude`
# (Flutter glue → E0583) and no-`--all-features` (mutually-exclusive
# `decimal-*` backends → compile_error!) scoping as `all-checks`.
# Extra args pass through (CI appends `--locked` to catch lockfile drift).
check *args='':
	cargo check --workspace --exclude embedded_flutter_native --all-targets {{args}}

# Clippy as `-D warnings` — blocking CI gate. `clippy_allow` permits a
# small, documented set of codegen-friendly lints (see top of file).
lint:
	cargo clippy --workspace --exclude embedded_flutter_native --all-targets -- -D warnings {{clippy_allow}}

# Verify formatting without writing — blocking CI gate.
fmt-check:
	just _fmt --check

# Feature-graph regression matrix (cratestack#421, cratestack#495) —
# blocking CI gate. Asserts `decimal-rust-decimal`/`decimal-bigdecimal` are
# mutually exclusive (not "neither selectable" — #495 made the second
# backend real), that `cratestack-core`'s default feature set never leaks
# through a `--no-default-features` consumer, and that `rust_decimal` is
# never reachable anywhere in the graph once `decimal-bigdecimal` is
# selected. See `.ci/feature-matrix.sh` for the full rationale and the
# exact commands run.
feature-matrix:
	./.ci/feature-matrix.sh

# Bring the Postgres test container up (idempotent; waits for ready).
pg-up:
	@docker compose up -d postgres >/dev/null
	@until docker exec cratestack-postgres pg_isready -U cratestack -d cratestack_test >/dev/null 2>&1; do sleep 1; done
	@echo "postgres ready at {{PG_URL}}"

# Stop and remove the Postgres test container (safe when nothing is up).
pg-down:
	@docker compose down >/dev/null
	@echo "postgres stopped"

# Run the full workspace test suite against a real Postgres, with auto-teardown on exit.
# `--features cratestack-migrate/postgres-introspect` opts just that one
# workspace member into its feature-gated live-introspection tests
# (issue #204) — the default `--workspace` feature set otherwise leaves
# `cratestack-migrate` on its DB-dependency-free default build.
test-pg *args='':
	#!/usr/bin/env bash
	set -euo pipefail
	cleanup() { docker compose down >/dev/null 2>&1 || true; echo "postgres stopped"; }
	trap cleanup EXIT
	just pg-up
	CRATESTACK_TEST_DATABASE_URL='{{PG_URL}}' cargo test --workspace --exclude embedded_flutter_native --features cratestack-migrate/postgres-introspect {{args}}

# Run only the cratestack-pg integration tests against PG (faster inner loop).
# Targets the server-facade package explicitly — the workspace also
# ships a documentation-only `cratestack` vitrine crate, so
# `-p cratestack` would silently select the empty crate and return a
# false-green here.
test-pg-only *args='':
	#!/usr/bin/env bash
	set -euo pipefail
	cleanup() { docker compose down >/dev/null 2>&1 || true; echo "postgres stopped"; }
	trap cleanup EXIT
	just pg-up
	CRATESTACK_TEST_DATABASE_URL='{{PG_URL}}' cargo test -p cratestack-pg {{args}}

# Run the workspace test suite via testcontainers (per-binary ephemeral PG, recommended for CI).
test-pg-tc *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test --workspace --exclude embedded_flutter_native {{args}}

# --- CI test shards -------------------------------------------------------
# CI runs the suite as four parallel shards (see .github/workflows/ci.yml)
# so no single runner compiles the whole workspace — the tauri/wasm/napi
# example crates otherwise push the runner past its disk limit. Each shard
# is also usable locally.

# Shard: the Postgres-backed crate via testcontainers.
# (cratestack-redis no longer rides along here: it has its own blocking
# `tests-redis` job backed by the `test-ci-redis` recipe below.)
# `--features grpc` (cratestack#524 gap-closing test): without it, every
# `#![cfg(feature = "grpc")]`-gated integration test file (`transport_grpc.rs`,
# `grpc_auth_provider_extensions.rs`, `trusted_proxy_client_ip_grpc.rs`,
# `transport_grpc_crud_dispatch.rs`) still compiles — cargo builds every
# file under `tests/` regardless of an inner `#![cfg(...)]` — but as an
# EMPTY 0-test binary, so this whole gRPC test surface was silently never
# exercised by `tests-db` before this line existed. Confirmed via
# `cargo test -p cratestack-pg --test transport_grpc -- --list` printing
# `0 tests` without this flag vs. 5 with it.
test-ci-db *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-pg --features grpc {{args}}

# Shard addendum: the `decimal-bigdecimal` backend's own live-Postgres
# round-trip test (cratestack#421 AC3, cratestack#495/#496). This file is
# gated `required-features = ["postgres", "decimal-bigdecimal"]`
# (`crates/cratestack-pg/tests/decimal_bigdecimal_backend.rs`), so it is
# never even compiled by `test-ci-db` above, which runs under
# `cratestack-pg`'s *default* feature set (`decimal-rust-decimal`).
# `.ci/feature-matrix.sh` proves the backend *compiles* clean end to end;
# this proves it actually *works* — a `Decimal` field round-trips through
# real Postgres `NUMERIC` without precision loss, including a value beyond
# `rust_decimal`'s ~28-29 significant-digit capacity that only
# `decimal-bigdecimal` can represent at all. Without this recipe wired
# into CI, a regression in the bigdecimal codec/bind path would still pass
# every existing gate (compiles clean, no `rust_decimal` in the graph)
# while being silently broken at runtime.
test-ci-db-decimal-bigdecimal *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-pg --no-default-features --features postgres,decimal-bigdecimal --test decimal_bigdecimal_backend {{args}}

# Shard addendum: `cratestack-outbox`'s 5 live-Postgres tests (atomic
# persist/rollback, cursor-ordered drain, GC sweep) — a 2026-08 CI-coverage
# audit found no workflow ever invoked them (`grep -rn outbox
# .github/workflows/*.yml` matched nothing before this line), despite the
# crate correctly implementing the standard `connect_or_skip` +
# `CRATESTACK_REQUIRE_DB` shim (`crates/cratestack-outbox/tests/support/pg.rs`,
# copied from `cratestack-pg`'s). Confirmed via `cargo test -p
# cratestack-outbox --test outbox_roundtrip -- --list` printing `5 tests`
# while silently running none of them without a DB. Mirrors `test-ci-db`'s
# testcontainers pattern one-for-one.
test-ci-db-outbox *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-outbox --test outbox_roundtrip {{args}}

# Shard addendum: `cratestack-migrate`'s live-Postgres introspection tests
# (issue #204, `crates/cratestack-migrate/tests/postgres_introspect.rs`),
# gated `#![cfg(feature = "postgres-introspect")]`. A 2026-08 CI-coverage
# audit found the only recipe that ever passed that feature was `just
# test-pg`, which no workflow invokes at all (`grep -rn test-pg
# .github/workflows/*.yml` matched nothing before this line) — so these 7
# tests never ran in CI. `connect_or_skip` here now supports the same
# `CRATESTACK_USE_TESTCONTAINERS`/`CRATESTACK_REQUIRE_DB` shim every other
# PG-backed test in the workspace uses (it previously only checked
# `CRATESTACK_TEST_DATABASE_URL`, with no CI-reachable fallback).
test-ci-db-migrate-introspect *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-migrate --features postgres-introspect --test postgres_introspect {{args}}

# Shard addendum: `cratestack-cli`'s 5 `migrate baseline` integration tests
# (issue #205, `crates/cratestack-cli/src/migrate/tests_baseline/*.rs`,
# collected under `migrate::tests_baseline` in the `cratestack` unittests
# binary). A 2026-08 CI-coverage audit found `isolated_test_db` only ever
# checked `CRATESTACK_TEST_DATABASE_URL`, with no testcontainers fallback
# and no `CRATESTACK_REQUIRE_DB` hard-fail — unlike every other PG test in
# this repo — and CI never sets that variable, so 4 of the 5 tests (the
# ones that touch a database) silently skipped on every run. Now supports
# the standard shim, so this runs them for real. Scoped to the one test
# filter (`migrate::tests_baseline::`) so this doesn't re-run the whole
# `cratestack-cli` unit-test suite a second time (`test-ci-host` already
# does, with no DB, where the DB-touching subset just skips).
test-ci-db-cli-baseline *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-cli migrate::tests_baseline:: {{args}}

# Shard: the Redis-backed crate via testcontainers (issue #418). Idempotency
# and rate-limit stores are the primitives the `banking_*` fixtures lean on
# for correctness under retries/concurrency, so this mirrors `test-ci-db`'s
# testcontainers pattern one-for-one rather than riding along in the host
# shard, where the tests used to skip silently for lack of a Redis.
test-ci-redis *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-redis {{args}}

# Shard: the Studio crate, whose api_smoke tests assert the Trunk-built UI
# is embedded. CI runs `trunk build` first; no database needed.
test-ci-studio *args='':
	cargo test -p cratestack-studio {{args}}

# Shard addendum: cratestack-studio's four `tests/postgres_*.rs` files
# (postgres_explain, postgres_routed_writes, postgres_row_keys,
# postgres_unsafe_writes) — the live-Postgres coverage that, until CI
# started setting CRATESTACK_REQUIRE_DB/CRATESTACK_USE_TESTCONTAINERS for
# this recipe, skipped silently on every run (a coverage audit found this
# is how the duplicate-column bug PR #553 fixed shipped in the first
# place: its decisive test never actually ran in CI). Mirrors
# `test-ci-db`'s testcontainers pattern one-for-one, scoped to just these
# four test binaries so the plain `test-ci-studio` run above isn't
# duplicated wholesale.
test-ci-studio-db *args='':
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-studio \
		--test postgres_explain \
		--test postgres_routed_writes \
		--test postgres_row_keys \
		--test postgres_unsafe_writes \
		{{args}}

# Shard: everything else — the remaining framework crates + light example
# smoke tests, with no container, no wasm/desktop toolchain, and no GTK.
# Uses --exclude (a denylist) rather than -p so inline `#[cfg(test)]` unit
# tests in crates without a tests/ dir (core, parser, sqlx, macros, …) keep
# running. Excludes the three shards above, the flutter glue crate, and:
#
#   * `tauri-web-shell-example` / `tauri-native-shell-example` — genuine
#     environment constraint, not a "zero tests" claim (a prior version of
#     this comment said exactly that for all nine crates below, which a
#     2026-08 CI-coverage audit found false for seven of them). Both link
#     `webkit2gtk-sys`/`soup3-sys` on Linux, which fail to even *compile*
#     without `libgtk-3-dev`/`libwebkit2gtk-4.1-dev` installed (verified:
#     `cargo test -p tauri-web-shell-example` and `-p
#     tauri-native-shell-example` both fail at the `pkg-config` build-script
#     step on a stock runner) — no test job here installs those packages.
#     `tauri-native-shell-example` carries 2 real tests that would run fine
#     once that dependency is met; `tauri-web-shell-example` has none.
#   * `react-nextjs-daisyui-napi` — the one crate here that actually has
#     zero tests (`cargo test -p react-nextjs-daisyui-napi -- --list`
#     prints `0 tests`).
#
# Every other previously-excluded crate — `tauri-web-wasm-example`,
# `embedded-browser-vite-example`, `embedded-browser-vite-pwa-example`,
# `embedded-browser-webpack-example`, `react-vite-daisyui-example`,
# `react-nextjs-daisyui-wasm`, `embedded-expo-native` — carries real
# `#[cfg(test)] mod tests { #[test] ... }` coverage (CRUD round trips,
# cursor filtering, dispatcher error paths; ~12 tests total across the
# nine crates this comment used to wave away) that compiles and runs fine
# on the host target with no wasm32/GTK toolchain at all — their
# `wasm-bindgen`-only code lives behind `#[cfg(target_arch = "wasm32")]`
# and is simply absent from a native build, same as this shard's other
# members. They are no longer excluded. (They were, and still are,
# separately compiled by the `check` job and the `embedded-examples` gate
# — this shard is what actually *runs* their tests.)
test-ci-host *args='':
	#!/usr/bin/env bash
	set -euo pipefail
	cargo test --workspace \
		--exclude embedded_flutter_native \
		--exclude cratestack-pg \
		--exclude cratestack-redis \
		--exclude cratestack-studio \
		--exclude tauri-web-shell-example \
		--exclude tauri-native-shell-example \
		--exclude react-nextjs-daisyui-napi {{args}}
	# The three lines below close a `--features`-forwarding gap identical to
	# the one `test-ci-db`'s own `--features grpc` comment documents (a
	# 2026-08 CI-coverage audit found these three were missed by that same
	# sweep): each test file is gated `#![cfg(feature = "...")]` or a
	# Cargo-level `required-features`, so it compiles to an empty 0-test
	# binary under the plain `--workspace` run above. None needs a
	# database. `pgvector_distance_query.rs` is deliberately NOT included
	# here — it's self-documented as needing the `pgvector/pgvector`
	# Postgres image, not the stock one this shard (or any shard) runs.
	cargo test -p cratestack-pg --features rate_limit --test rate_limit_extension {{args}}
	cargo test -p cratestack-pg --features pgvector --test pgvector_feature_forwarding {{args}}
	cargo test -p cratestack-client --features pgvector,rate_limit --test extension_feature_forwarding {{args}}

# Report-only: surfaces the current pass/fail state of every `#[ignore]`d
# test without blocking CI (2026-08 policy-layer coverage audit, Phase 3 —
# nothing else in this repo ever runs or surfaces an ignored test, which is
# exactly how four policy-enforcement tests, two of them catching REAL
# authorization bugs, went unrun for months: `git grep -rn "\-\-include-ignored\|-- --ignored"`
# matched nothing anywhere in `.github/workflows/` or this justfile before
# this recipe). Reuses `test-ci-db`'s testcontainers Postgres (where every
# DB-backed `#[ignore]` lives) and `test-ci-host`'s exclude list (for
# no-DB ignores, e.g. cratestack-sqlx's characterization test for the
# auth-bypass bug found alongside this mechanism) — deliberately skips
# `cratestack-studio` and the wasm/tauri example crates as this recipe
# has no Trunk/GTK toolchain step of its own. Always exits 0: a red
# ignored test here is not a regression to fix in this job, it's a
# defect (real or stale) to triage in the test's own `#[ignore]` reason —
# see the top-level report this recipe prints for exactly which ones
# failed.
test-ci-ignored-report *args='':
	#!/usr/bin/env bash
	set -uo pipefail
	echo "=== Ignored tests: cratestack-pg (testcontainers Postgres) ==="
	CRATESTACK_USE_TESTCONTAINERS=1 cargo test -p cratestack-pg {{args}} -- --ignored --nocapture
	pg_status=$?
	echo ""
	echo "=== Ignored tests: workspace host shard (no DB, no wasm/desktop toolchain) ==="
	# Same exclude list as `test-ci-host` (see that recipe's comment for why
	# only these three stay excluded).
	cargo test --workspace \
		--exclude embedded_flutter_native \
		--exclude cratestack-pg \
		--exclude cratestack-studio \
		--exclude tauri-web-shell-example \
		--exclude tauri-native-shell-example \
		--exclude react-nextjs-daisyui-napi {{args}} -- --ignored --nocapture
	host_status=$?
	echo ""
	echo "=== Ignored-test report summary ==="
	if [ "$pg_status" -ne 0 ] || [ "$host_status" -ne 0 ]; then
		echo "One or more #[ignore]d tests failed to run cleanly (pg shard exit=$pg_status, host shard exit=$host_status)."
		echo "This is expected for any test whose #[ignore] reason says REAL BUG — read that reason string before treating a red result here as new."
	else
		echo "All #[ignore]d tests ran clean (0 failures) — every one of them is a candidate to have its #[ignore] removed in a follow-up PR."
	fi
	exit 0

# Verify the Dart client generator's OUTPUT actually compiles, not just
# that its generated text matches a Rust-side snapshot (issue #300).
# Generates a REST and an RPC package during the run from committed
# fixtures (crates/cratestack-client-dart/tests/fixtures/ci_{rest,rpc}.cstack
# — multiple models, an enum, a relation, and a procedure each) via the
# real `cratestack generate-dart` CLI, then runs `flutter analyze` on
# each. This is the same check CI's `dart (generated packages)` job runs.
#
# Issue #301 extends this to also cover `--preset riverpod`: the same
# ci_rest/ci_rpc fixtures (proving the fan-out layout compiles under both
# transports) plus riverpod_shared_ownership.cstack (a dedicated fixture
# for the ownership rule — an enum genuinely shared by two models, a
# nested type reached only through a procedure, and a User -> Post[] ->
# User relation cycle across two per-model files).
#
# Issue #302 extends the riverpod-preset loop further: every riverpod
# fixture now also runs `dart run build_runner build
# --delete-conflicting-outputs` BEFORE `flutter analyze` — the ticket's
# load-bearing check, since a malformed `@riverpod` annotation surfaces
# as a `build_runner` error, not a `dart analyze` one, so analyze alone
# would not catch it — and `flutter test` after, which actually exercises
# the generated `test/*_test.dart`'s override-propagation proof (a fake
# adapter overrides the existing `xAdapterProvider`, then a generated
# operation provider is read and asserted to have gone through it).
# `riverpod_provider_collision.cstack` is a new fixture in this set: two
# models whose *naive* per-operation provider names would collide, plus a
# procedure that collides with one of the models' own controller name —
# proving the collision escalation in `provider_naming.rs` produces
# distinct names that still compile end to end (not just distinct in a
# Rust-side text assertion).
#
# Issue #303: `build_runner` is no longer invoked as a separate bash line
# here — every riverpod fixture regenerates with `generate-dart`'s own
# `--run-build-runner` flag instead, so this recipe is also the CI proof
# that the flag itself (not just a hand-rolled `dart run build_runner
# build`) actually works end to end against the real pinned toolchain.
# `flutter pub get` still runs as its own step first: `--run-build-runner`
# deliberately runs only the one command the acceptance criteria specify
# (`dart run build_runner build --delete-conflicting-outputs`), not an
# implicit `pub get`, so dependencies must already be resolved before it.
#
# Requires the Flutter SDK on PATH, not just the Dart SDK: the generated
# `pubspec.yaml` depends on `sdk: flutter` (the `flutter`/`flutter_test`
# packages) and `flutter_riverpod` — a standalone Dart SDK install has no
# Flutter pub cache to resolve those against (verified empirically before
# choosing this over `dart-lang/setup-dart`).
verify-dart:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v flutter >/dev/null; then
	  echo "flutter not found on PATH — install the Flutter SDK: https://docs.flutter.dev/get-started/install" >&2
	  exit 1
	fi
	out=target/dart-verify
	rm -rf "$out"

	verify_pkg() {
	  local pkg="$1"
	  echo "=== flutter pub get: $pkg ==="
	  (cd "$pkg" && flutter pub get)
	  echo "=== flutter analyze: $pkg ==="
	  # --fatal-warnings (Dart's own default): a warning-level finding
	  # fails the build — unused imports, dead code, deprecated API use
	  # are real signal on generated code that should never carry them.
	  # --no-fatal-infos: info-level style suggestions don't fail the
	  # build here. `flutter analyze` (unlike plain `dart analyze`)
	  # defaults `--fatal-infos` to ON; the two pre-existing info
	  # findings this surfaced on today's templates (a doc-comment
	  # angle-bracket lint in runtime.dart, and a nullable-narrowing
	  # suggestion on constants.dart's schema-hash constant that's a
	  # structural false positive — the field is `String?` because it
	  # can be null for hash-less configs, even though this particular
	  # generated instance's literal happens to be non-null) are noise,
	  # not evidence the generator is broken, so they don't gate the
	  # build. See the PR that introduced this recipe for the follow-up
	  # issue tracking them.
	  (cd "$pkg" && flutter analyze --fatal-warnings --no-fatal-infos)
	}

	# riverpod-preset-only: deliberately does NOT call `verify_pkg` (which
	# runs `flutter analyze` first) — `flutter analyze` on a freshly
	# generated riverpod package, before `build_runner` has run, reports
	# real `uri_has_not_been_generated`/`undefined_identifier` errors for
	# every `part '<file>.g.dart'` directive and every `@riverpod`
	# annotation's `ref`/`state` usage (verified empirically; this is
	# exactly the ticket's "a malformed annotation surfaces as a
	# build_runner error, not an analyzer error" risk, but the inverse
	# also holds — analyze alone, run too early, is *always* red here,
	# which would make this recipe permanently fail). Order is therefore
	# pub get -> build_runner -> analyze -> test, matching the acceptance
	# criteria's own "dart analyze is clean AFTER build_runner" wording.
	verify_riverpod_pkg() {
	  local pkg="$1"
	  local schema="$2"
	  local library_name="$3"
	  echo "=== flutter pub get: $pkg ==="
	  (cd "$pkg" && flutter pub get)
	  echo "=== generate-dart --preset riverpod --run-build-runner: $pkg ==="
	  cargo run --quiet -p cratestack-cli -- generate-dart \
	    --schema "$schema" \
	    --out "$pkg" \
	    --library-name "$library_name" \
	    --preset riverpod \
	    --run-build-runner
	  echo "=== flutter analyze (post build_runner): $pkg ==="
	  (cd "$pkg" && flutter analyze --fatal-warnings --no-fatal-infos)
	  echo "=== flutter test: $pkg ==="
	  (cd "$pkg" && flutter test)
	}

	fixtures=(ci_rest ci_rpc)
	for fixture in "${fixtures[@]}"; do
	  pkg="$out/default/$fixture"
	  echo "=== generate-dart --preset default: $fixture -> $pkg ==="
	  cargo run --quiet -p cratestack-cli -- generate-dart \
	    --schema "crates/cratestack-client-dart/tests/fixtures/$fixture.cstack" \
	    --out "$pkg" \
	    --library-name "dart_verify_${fixture}"
	  verify_pkg "$pkg"
	done

	riverpod_fixtures=(ci_rest ci_rpc riverpod_shared_ownership riverpod_provider_collision)
	for fixture in "${riverpod_fixtures[@]}"; do
	  pkg="$out/riverpod/$fixture"
	  schema="crates/cratestack-client-dart/tests/fixtures/$fixture.cstack"
	  library_name="dart_verify_riverpod_${fixture}"
	  echo "=== generate-dart --preset riverpod: $fixture -> $pkg ==="
	  cargo run --quiet -p cratestack-cli -- generate-dart \
	    --schema "$schema" \
	    --out "$pkg" \
	    --library-name "$library_name" \
	    --preset riverpod
	  verify_riverpod_pkg "$pkg" "$schema" "$library_name"
	done

	# cratestack#407 (AC5): the last open acceptance criterion — prove,
	# don't merely inspect, that the generated Dart client treats a
	# declared `@status(202)` REST success status as success. The Rust
	# client was already proven this way
	# (crates/cratestack-client/tests/status_attribute_client_round_trip.rs);
	# the Dart half was inspected (no explicit `validateStatus` override
	# found in the REST-runtime templates) but never run — that inference
	# is exactly what this checks instead of repeating. Both `default` and
	# `riverpod` presets are generated from the same fixture with the same
	# `--library-name` on purpose: both derive identical class/import names
	# from it, so the one hand-written test file
	# (status_override_202_test.dart) runs unmodified against either
	# package. RPC transport is out of scope here — `@status` is rejected
	# at schema-compile time under `transport rpc`, so there is no RPC
	# generated-client path to check.
	status_schema="crates/cratestack-client-dart/tests/fixtures/status_override.cstack"
	status_test="crates/cratestack-client-dart/tests/fixtures/status_override_202_test.dart"
	status_library="dart_status_verify"

	status_default_pkg="$out/status-202/default"
	echo "=== generate-dart --preset default: status_override -> $status_default_pkg ==="
	cargo run --quiet -p cratestack-cli -- generate-dart \
	  --schema "$status_schema" \
	  --out "$status_default_pkg" \
	  --library-name "$status_library"
	(cd "$status_default_pkg" && flutter pub get)
	mkdir -p "$status_default_pkg/test"
	cp "$status_test" "$status_default_pkg/test/status_202_test.dart"
	echo "=== flutter test (real HTTP round trip, @status(202) proof): $status_default_pkg ==="
	(cd "$status_default_pkg" && flutter test test/status_202_test.dart)

	status_riverpod_pkg="$out/status-202/riverpod"
	echo "=== generate-dart --preset riverpod: status_override -> $status_riverpod_pkg ==="
	cargo run --quiet -p cratestack-cli -- generate-dart \
	  --schema "$status_schema" \
	  --out "$status_riverpod_pkg" \
	  --library-name "$status_library" \
	  --preset riverpod
	(cd "$status_riverpod_pkg" && flutter pub get)
	echo "=== generate-dart --preset riverpod --run-build-runner: $status_riverpod_pkg ==="
	cargo run --quiet -p cratestack-cli -- generate-dart \
	  --schema "$status_schema" \
	  --out "$status_riverpod_pkg" \
	  --library-name "$status_library" \
	  --preset riverpod \
	  --run-build-runner
	mkdir -p "$status_riverpod_pkg/test"
	cp "$status_test" "$status_riverpod_pkg/test/status_202_test.dart"
	echo "=== flutter test (real HTTP round trip, @status(202) proof): $status_riverpod_pkg ==="
	(cd "$status_riverpod_pkg" && flutter test test/status_202_test.dart)

# Verify the TypeScript client generator's OUTPUT actually typechecks,
# not just that its generated text matches a Rust-side snapshot (issue #419).
# Generates a REST and an RPC package during the run from committed
# fixtures (crates/cratestack-client-typescript/tests/fixtures/ci_{rest,rpc}.cstack
# and examples/react-vite-swr/schema.cstack — which uses --swr over REST)
# via the real `cratestack generate-typescript` CLI, then runs `pnpm build`
# (which invokes `tsc`) on each.
#
# Unlike `dart-verify` which generates on-the-fly from fixtures, the
# REST/--swr example already has committed generated output under
# examples/react-vite-swr/client/. That fixture exercises `--swr` over
# REST; this recipe adds an RPC fixture to prove RPC templates typecheck
# too.
verify-typescript:
	#!/usr/bin/env bash
	set -euo pipefail
	out=target/typescript-verify
	rm -rf "$out"

	# Generate and typecheck REST fixture
	pkg="$out/default/rest"
	echo "=== generate-typescript (REST): ci_rest.cstack -> $pkg ==="
	cargo run --quiet -p cratestack-cli -- generate-typescript \
	  --schema "crates/cratestack-client-typescript/tests/fixtures/ci_rest.cstack" \
	  --out "$pkg" \
	  --package-name typescript-verify-rest
	echo "=== npm install and build (typechecks with tsc): $pkg ==="
	(cd "$pkg" && npm install && npm run build)

	# Generate and typecheck RPC fixture
	pkg="$out/default/rpc"
	echo "=== generate-typescript (RPC): ci_rpc.cstack -> $pkg ==="
	cargo run --quiet -p cratestack-cli -- generate-typescript \
	  --schema "crates/cratestack-client-typescript/tests/fixtures/ci_rpc.cstack" \
	  --out "$pkg" \
	  --package-name typescript-verify-rpc
	echo "=== npm install and build (typechecks with tsc): $pkg ==="
	(cd "$pkg" && npm install && npm run build)

	echo ""
	echo "✓ TypeScript REST and RPC fixtures generated and typechecked successfully"

# Regenerate the two committed example clients in place (issue #471).
#
# `examples/flutter-riverpod/client` (via `generate-dart --preset riverpod`)
# and `examples/react-vite-swr/client` (via `generate-typescript --swr`) are
# committed generated output, guarded only by a CI `--check` step
# (the `flutter (flutter-riverpod example)` and `js (react-vite-swr
# example)` jobs in `.github/workflows/ci.yml`). Before this recipe existed
# there was no local command that could reconcile a template change
# against them — the only way to find out a template edit had drifted the
# committed examples was to push and read CI (see #444/#470/#471).
#
# `ci.yml`'s `flutter-riverpod-example`/`react-vite-swr-example` drift-check
# steps call this same recipe as `just regen-examples --check` — one
# mechanism, not a hand-copied third invocation — so the recipe and CI
# cannot copy-paste diverge (same `*args=''` passthrough shape as `check`
# above, which CI calls as `just check --locked`). Local, no-arg use
# defaults to write mode.
#
# Unlike `verify-dart`/`verify-typescript` above (which generate throwaway
# packages from fixtures into `target/`), this recipe overwrites the
# committed example directories directly. Run it with no args, review
# `git diff`, and commit the result — a non-empty diff on an otherwise-
# unmodified checkout of `main` means the committed examples have already
# drifted from their templates.
regen-examples *args='':
	cargo run -p cratestack-cli -- generate-dart \
	  --schema examples/react-vite-swr/schema.cstack \
	  --out examples/flutter-riverpod/client \
	  --library-name flutter_riverpod_client \
	  --preset riverpod {{args}}
	cargo run -p cratestack-cli -- generate-typescript \
	  --schema examples/react-vite-swr/schema.cstack \
	  --out examples/react-vite-swr/client \
	  --swr \
	  --package-name react-vite-swr-client {{args}}

# Generates @cratestack/refine's test fixture (cratestack#571/#577): a REAL
# TypeScript client, produced by the real `cratestack generate-typescript`
# CLI from packages/cratestack-refine/tests/fixtures/refine_fixture.cstack,
# into packages/cratestack-refine/tests/fixtures/generated-client — so the
# package's tests drive an actual generated client rather than a
# hand-written stand-in for one.
#
# Unlike `regen-examples` above, this is NOT committed output — it's
# gitignored (cratestack#577 maintainer feedback: don't commit generated
# build output). CI's `js (@cratestack/refine)` job (the one Rust-toolchain
# JS job, mirroring `js-cbor-napi`/`js-cbor-web`'s carve-out for a real npm
# package that needs a Rust step the toolchain-free `js` job can't provide)
# runs this recipe before testing. Local devs need it too — the test
# suite's own `tests/support/assert-fixture-present.ts` (a vitest
# `globalSetup`) throws with this recipe's name if the fixture is missing,
# rather than silently skipping.
#
# `--refine` is load-bearing here, not decoration: it makes the generator
# emit `src/refine.ts`, the `ResourceMap` for this schema. Two things in
# the package depend on it being there — `tests/generated-manifest.test.ts`
# drives it at runtime, and `tsc --noEmit -p tsconfig.typecheck.json` (the
# first half of the package's `test` script) proves it actually satisfies
# `ResourceConfig`, which no string assertion over generated source could.
refine-fixture:
	rm -rf packages/cratestack-refine/tests/fixtures/generated-client
	cargo run -p cratestack-cli -- generate-typescript \
	  --schema packages/cratestack-refine/tests/fixtures/refine_fixture.cstack \
	  --out packages/cratestack-refine/tests/fixtures/generated-client \
	  --refine \
	  --package-name refine-fixture-client

# Generates @cratestack/refine's SECOND test fixture: a REAL `transport rpc`
# TypeScript client, produced by the real `cratestack generate-typescript`
# CLI from packages/cratestack-refine/tests/fixtures/refine_fixture_rpc.cstack
# — the RPC sibling of `refine-fixture` above, proving
# `createCratestackRpcDataProvider` drives an actual generated RPC client
# rather than a hand-written stand-in for one.
#
# Same "not committed" discipline as `refine-fixture` (cratestack#577) —
# gitignored, regenerated by CI's `js (@cratestack/refine)` job and by
# `tests/support/assert-fixture-present.ts`'s local-dev check.
#
# `--refine` IS passed here, same as `refine-fixture` above: issue #571's
# RPC follow-up (#586) lifted `TypeScriptGeneratorError::RefineRequiresRest`
# to `RefineRequiresRestOrRpc` — the generator has emitted a real
# `src/refine.ts` (typed to `RpcResourceMap`) for `transport rpc` schemas
# since then. A prior version of this comment said otherwise; a 2026-08
# CI-coverage audit found that made this recipe (and therefore CI's `js
# (@cratestack/refine)` job) never generate or typecheck that file at all —
# `tests/typecheck/generated-manifest-rpc.ts` is the round-trip proof this
# unlocks, the RPC sibling of `tests/typecheck/generated-manifest.ts`.
# `tests/typecheck/rpc-manifest.ts`'s hand-written `RpcResourceMap` stays
# alongside it — it proves the generated model classes themselves satisfy
# `CratestackRpcModelApi` independent of the manifest generator, same as
# every hand-written example in the package README.
refine-rpc-fixture:
	rm -rf packages/cratestack-refine/tests/fixtures/generated-client-rpc
	cargo run -p cratestack-cli -- generate-typescript \
	  --schema packages/cratestack-refine/tests/fixtures/refine_fixture_rpc.cstack \
	  --out packages/cratestack-refine/tests/fixtures/generated-client-rpc \
	  --refine \
	  --package-name refine-fixture-rpc-client

# Generates BOTH build-output artifacts `examples/react-vite-refine/web`
# needs: the `--refine` TypeScript client (into `web/generated/`) and the
# WireMock stub mappings (into `wiremock/`). Neither is committed
# (cratestack#577's "don't commit generated build output" instruction,
# same discipline as `refine-fixture`/`refine-rpc-fixture` above) — both
# directories are gitignored, and `web/`'s `predev`/`prebuild`/
# `pretypecheck` npm scripts fail loudly (not silently) if this recipe
# hasn't been run yet, via `web/scripts/assert-fixture-present.mjs`.
#
# `transport rest` (the schema's default — no `transport rpc` line) is
# load-bearing here, not incidental: `cratestack-mock-wiremock`'s
# stateful model-CRUD stubs only exist for REST (its own README's
# "Scope" section) — a `transport rpc` schema's model stubs stay static,
# which would make every create/update/delete in the app silently no-op.
# See `examples/react-vite-refine/README.md` for the full explanation,
# including the confirmed gap this fixture's WireMock half has no
# workaround for: the generated stubs don't validate `If-Match`, so the
# `Post` model's `@version` optimistic-locking demo can show the client
# SENDING it but not the mock REJECTING a stale one — see that README's
# "What this demo can't prove" section.
react-vite-refine-fixture:
	rm -rf examples/react-vite-refine/web/generated
	cargo run -p cratestack-cli -- generate-typescript \
	  --schema examples/react-vite-refine/schema.cstack \
	  --out examples/react-vite-refine/web/generated \
	  --refine \
	  --package-name react-vite-refine-client
	rm -rf examples/react-vite-refine/wiremock
	cargo run -p cratestack-cli -- generate-wiremock \
	  --schema examples/react-vite-refine/schema.cstack \
	  --out examples/react-vite-refine/wiremock

# Layer-direction check (ADR 0014, docs/adr/0014-layer-direction-enforcement.md)
# — blocking CI gate. Asserts every NORMAL cratestack-* -> cratestack-* edge
# among the crates under `crates/` satisfies `dep.layer <= self.layer`
# against `docs/adr/layers.toml`, with target-gated normal dependencies
# included and dev-/build-dependencies exempt. Known violations are tracked
# in `.ci/layer-direction-allowlist.toml` (currently empty — #475, the
# client-store-{sqlite,redis} -> client-rust back-edge, was the only entry
# and is fixed) and don't fail the build; an allowlist entry that no longer
# matches a real violation does. See `.ci/layer-direction-check.sh` for the
# full rationale.
verify-layering:
	./.ci/layer-direction-check.sh

# Workspace-lints opt-in check (cratestack#523) — blocking CI gate. Asserts
# every root workspace member declares `[lints]\nworkspace = true`, so the
# root `[workspace.lints.rust] unsafe_code = "forbid"` table (which Cargo
# otherwise silently ignores for any non-opted-in member) actually applies.
# The three FFI-boundary crates that manually override `unsafe_code =
# "allow"` instead (napi-derive/wasm-bindgen trampolines, raw C-ABI
# exports — Cargo rejects combining `workspace = true` with a per-package
# override in the same manifest) are checked for that override instead of
# the opt-in. Standalone example/vitrine workspaces excluded from the root
# `[workspace] members` list (`cratestack-studio-ui`, the `no-database-
# verification*` crates, `client-only-verification`) are checked for their
# own local `[workspace.lints.rust] unsafe_code = "forbid"` declaration,
# since the root workspace's table can't reach a disjoint workspace. See
# `.ci/lints-workspace-check.sh` for the full rationale.
verify-lints-optin:
	./.ci/lints-workspace-check.sh

# Changelog verification: detect unedited seeds.
#
# Ensures that CHANGELOG.md contains no auto-generated seeds with the
# TODO marker still present. This is load-bearing: an unedited seed reaching
# main silently degrades the changelog from prose to a commit list, which is
# worse than today's honest gap (it looks maintained, but isn't).
#
# Blocking CI gate for any PR that touches CHANGELOG.md.
verify-changelog:
	./.ci/changelog-check.sh

# Test changelog-seed.sh and changelog-check.sh against an isolated sandbox
# copy of CHANGELOG.md (never the real, tracked file). Wired into CI so the
# test suite actually runs instead of silently rotting.
changelog-seed-test:
	./.ci/changelog-seed-tests.sh

# Regenerate flutter_rust_bridge glue (Rust `frb_generated.rs` plus the
# Dart bindings a `flutter_rust_bridge.yaml` in DIR points at) for one
# frb-bridged crate/example. Glue is deliberately NOT committed
# (cratestack#563 decision — see the `--exclude embedded_flutter_native`
# comment on `all-checks` above for the full rationale and which crates
# this applies to); this recipe is the "generate locally" half of that
# decision, CI's regeneration step is the other half.
#
# Usage: `just frb-generate examples/embedded-flutter`
frb-generate DIR:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v flutter_rust_bridge_codegen >/dev/null; then
	  echo "flutter_rust_bridge_codegen not found. Run: cargo install flutter_rust_bridge_codegen" >&2
	  exit 1
	fi
	(cd "{{DIR}}" && flutter_rust_bridge_codegen generate)

# CI's regeneration step for crates/cratestack-client-flutter (cratestack#563
# decision c: "CI must prove the generated glue is current" — see the
# ticket's third maintainer-decision comment). Unlike a committed-output
# drift check (`--check` against tracked generated files), NOTHING
# generated here is committed, so "drift" instead means: can the glue
# still be produced at all, does it still compile against the crate (the
# `frb-glue` feature build), and does the hand-written
# `dart/verify_round_trip.dart` harness — which calls specific generated
# function/type names (`cbor.encodeJson`, `cbor.decodeJson`,
# `FlutterRuntimeError`) — still run against it. A Rust-side rename or
# signature change that silently breaks the Dart-facing API surface fails
# this recipe, not just `frb-generate` succeeding.
#
# Requires: `flutter_rust_bridge_codegen` (=2.12.0, pinned to match
# `crates/cratestack-client-flutter/Cargo.toml`) and the Dart SDK on PATH.
frb-verify-client-flutter:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v flutter_rust_bridge_codegen >/dev/null; then
	  echo "flutter_rust_bridge_codegen not found. Run: cargo install --locked flutter_rust_bridge_codegen --version 2.12.0" >&2
	  exit 1
	fi
	if ! command -v dart >/dev/null; then
	  echo "dart not found on PATH — install the Dart SDK: https://dart.dev/get-dart" >&2
	  exit 1
	fi
	dir=crates/cratestack-client-flutter
	echo "=== flutter_rust_bridge_codegen generate: $dir ==="
	(cd "$dir" && flutter_rust_bridge_codegen generate)
	echo "=== cargo build --features frb-glue: $dir ==="
	cargo build -p cratestack-client-flutter --features frb-glue
	echo "=== dart pub get: $dir/dart ==="
	(cd "$dir/dart" && dart pub get)
	echo "=== dart run verify_round_trip.dart: $dir/dart ==="
	# `.so`: this recipe only targets Linux today (CI's runner and the
	# common local dev platform for this workspace). A cross-platform
	# version would need `.dylib`/`.dll` naming too — out of scope for
	# this slice (see the ticket's "cross-platform binary matrix" scope
	# note).
	target_dir="$(cargo metadata --no-deps --format-version=1 | python3 -c "import json,sys;print(json.load(sys.stdin)['target_directory'])")"
	lib="$target_dir/debug/libcratestack_client_flutter.so"
	(cd "$dir/dart" && CRATESTACK_CLIENT_FLUTTER_NATIVE_LIB="$lib" dart run verify_round_trip.dart)
	echo ""
	echo "✓ flutter_rust_bridge glue for cratestack-client-flutter regenerated, compiled, and round-tripped from Dart"

# ---- dart-packages/cratestack_cbor (cratestack#563) ----------------------
# Regenerates the package's vendored NATIVE artifacts: the
# flutter_rust_bridge Dart glue (committed inside the package — unlike
# crates/cratestack-client-flutter's own gitignored verification-harness
# glue, this IS the shipped product; a pub.dev consumer has no
# flutter_rust_bridge_codegen to run themselves) and a stripped release
# build of the vendored native library (`blobs/linux-x64/`, Linux x86_64
# only — a deliberate one-platform spike, see the package's README).
#
# Requires: `flutter_rust_bridge_codegen` (=2.12.0, matching
# crates/cratestack-client-flutter/Cargo.toml) and `strip` on PATH.
cbor-vendor-native:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v flutter_rust_bridge_codegen >/dev/null; then
	  echo "flutter_rust_bridge_codegen not found. Run: cargo install --locked flutter_rust_bridge_codegen --version 2.12.0" >&2
	  exit 1
	fi
	pkg=dart-packages/cratestack_cbor
	echo "=== flutter_rust_bridge_codegen generate -> $pkg/lib/src/native/rust ==="
	(cd crates/cratestack-client-flutter && flutter_rust_bridge_codegen generate \
	  --rust-input crate::cbor \
	  --rust-root ./ \
	  --rust-output src/frb_generated.rs \
	  --rust-features frb-glue \
	  --dart-output "../../$pkg/lib/src/native/rust" \
	  --dart-entrypoint-class-name CratestackCborRustLib)
	# frb codegen's Dart output is not `dart format`-clean (unlike the Rust
	# side, this one is safe and cheap to fix here rather than working
	# around: `dart format` is idempotent, touches only the freshly
	# generated files under lib/src/native/rust/ — never anything this repo
	# tracks — and formatting has no effect on behavior, only on `pana`'s
	# "code has no ... formatting issues" score (verified: `pana` flagged
	# exactly frb_generated.dart/frb_generated.io.dart before this line
	# existed). Best-effort: skip quietly if `dart` isn't on PATH yet,
	# same tolerance `cbor-vendor-web`'s wasm-pack step gives other
	# optional tooling — a later `just cbor-verify-package`/publish step
	# needs `dart` anyway and will fail loudly there if it's truly absent.
	if command -v dart >/dev/null; then
	  dart format "$pkg/lib/src/native/rust" >/dev/null
	fi
	echo "=== cargo build --release --features frb-glue: cratestack-client-flutter ==="
	cargo build -p cratestack-client-flutter --features frb-glue --release
	target_dir="$(cargo metadata --no-deps --format-version=1 | python3 -c "import json,sys;print(json.load(sys.stdin)['target_directory'])")"
	mkdir -p "$pkg/blobs/linux-x64"
	cp "$target_dir/release/libcratestack_client_flutter.so" "$pkg/blobs/linux-x64/libcratestack_client_flutter.so"
	strip --strip-unneeded "$pkg/blobs/linux-x64/libcratestack_client_flutter.so"
	echo "✓ vendored $(du -h "$pkg/blobs/linux-x64/libcratestack_client_flutter.so" | cut -f1) native library + Dart glue at $pkg/lib/src/native/"

# Regenerates the package's vendored WEB artifact: a `wasm-pack --target
# web` build of the EXISTING crates/cratestack-cbor-wasm crate (the same
# Rust wasm-bindgen crate already bound to npm as @cratestack/cbor-web —
# cratestack#563 maintainer decision: reuse it, no new codec binding).
#
# Requires: `wasm-pack` and the `wasm32-unknown-unknown` target (installed
# by rustup from rust-toolchain.toml's `targets` for the pinned channel).
cbor-vendor-web:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v wasm-pack >/dev/null; then
	  echo "wasm-pack not found. Run: cargo install wasm-pack" >&2
	  exit 1
	fi
	pkg=dart-packages/cratestack_cbor
	out_dir="$(pwd)/$pkg/lib/src/web/wasm-pkg"
	rm -rf "$out_dir"
	mkdir -p "$out_dir"
	(cd crates/cratestack-cbor-wasm && wasm-pack build --target web --out-dir "$out_dir")
	# Only the .js glue + .wasm binary ship in the package — wasm-pack's
	# own package.json/README/.gitignore/TS types are npm-package
	# scaffolding this Dart package doesn't use.
	find "$out_dir" -mindepth 1 -maxdepth 1 \
	  ! -name '*.js' ! -name '*.wasm' -exec rm -rf {} +
	echo "✓ vendored $(du -sh "$out_dir" | cut -f1) wasm-bindgen build at $out_dir"

# Regenerates the package's vendored ANDROID artifact: a `cargo ndk`
# cross-compile of crates/cratestack-client-flutter's cdylib for every
# Android ABI this package claims (cratestack#563 platform-matrix slice).
# Deliberately does NOT regenerate the flutter_rust_bridge Dart glue itself
# — that glue is platform-independent (frb codegen introspects Rust source,
# not a target triple) and `cbor-vendor-native` already produces it as a
# side effect of building the Linux host library. Run `cbor-vendor-native`
# at least once before this recipe on a fresh checkout.
#
# ABIs: arm64-v8a (every real device) and x86_64 (the emulator) are the
# floor — without both, nobody can actually test this on either a device or
# the emulator. armeabi-v7a is included too: cross-compiling it is cheap
# (~14s incremental, measured; the three ABIs together take well under a
# minute from a warm cargo cache) so there's no reason to leave 32-bit ARM
# devices unsupported. Not included: iOS/macOS/Windows (out of scope for
# this slice — see docs/tooling/cratestack-cbor-development.md).
#
# Platform level 24 matches Flutter's own default `minSdk` for consuming
# apps (see android/build.gradle's comment) — keeping `cargo ndk -P` and
# the plugin's `minSdk` in lockstep avoids linking against libc symbols
# newer than what a consumer's `minSdk` guarantees.
#
# Requires: `cargo-ndk` (`cargo install cargo-ndk`), the three
# `*-linux-android*`/`*-linux-androideabi` rustup targets, `ANDROID_HOME`
# and `ANDROID_NDK_HOME` set (this repo pins Flutter's own default NDK,
# 28.2.13676358 — see docs/tooling/cratestack-cbor-development.md), and
# that NDK's own `llvm-strip` (used instead of the host `strip`, which does
# not reliably understand cross-arch ELF `--strip-unneeded` for AArch64).
cbor-vendor-android:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v cargo-ndk >/dev/null; then
	  echo "cargo-ndk not found. Run: cargo install cargo-ndk" >&2
	  exit 1
	fi
	if [ -z "${ANDROID_HOME:-}" ]; then
	  echo "ANDROID_HOME is not set. Point it at your Android SDK (e.g. ~/Android/Sdk)." >&2
	  exit 1
	fi
	if [ -z "${ANDROID_NDK_HOME:-}" ]; then
	  echo "ANDROID_NDK_HOME is not set. Point it at an installed NDK under \$ANDROID_HOME/ndk/<version> (e.g. 28.2.13676358, matching Flutter's own default)." >&2
	  exit 1
	fi
	if [ ! -d "$ANDROID_NDK_HOME" ]; then
	  echo "ANDROID_NDK_HOME ($ANDROID_NDK_HOME) does not exist." >&2
	  exit 1
	fi
	missing_targets=""
	for t in aarch64-linux-android x86_64-linux-android armv7-linux-androideabi; do
	  if ! rustup target list --installed | grep -qx "$t"; then
	    missing_targets="$missing_targets $t"
	  fi
	done
	if [ -n "$missing_targets" ]; then
	  echo "Missing rustup target(s):$missing_targets" >&2
	  echo "Run: rustup target add$missing_targets" >&2
	  exit 1
	fi
	pkg=dart-packages/cratestack_cbor
	if [ ! -f "$pkg/lib/src/native/rust/frb_generated.dart" ]; then
	  echo "flutter_rust_bridge Dart glue not found at $pkg/lib/src/native/rust/." >&2
	  echo "Run: just cbor-vendor-native (it produces the platform-independent glue this recipe reuses)" >&2
	  exit 1
	fi
	out_dir="$pkg/blobs/android"
	rm -rf "$out_dir"
	mkdir -p "$out_dir"
	echo "=== cargo ndk build --release --features frb-glue: cratestack-client-flutter (arm64-v8a, x86_64, armeabi-v7a) ==="
	cargo ndk -t arm64-v8a -t x86_64 -t armeabi-v7a -o "$out_dir" -P 24 \
	  build -p cratestack-client-flutter --features frb-glue --release
	strip_tool="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip"
	if [ ! -x "$strip_tool" ]; then
	  echo "llvm-strip not found at $strip_tool — is ANDROID_NDK_HOME pointed at a Linux-hosted NDK?" >&2
	  exit 1
	fi
	for abi in arm64-v8a x86_64 armeabi-v7a; do
	  "$strip_tool" --strip-unneeded "$out_dir/$abi/libcratestack_client_flutter.so"
	done
	echo "✓ vendored Android libraries at $out_dir:"
	for abi in arm64-v8a x86_64 armeabi-v7a; do
	  echo "    $abi: $(du -h "$out_dir/$abi/libcratestack_client_flutter.so" | cut -f1)"
	done

# Verifies BOTH cratestack_cbor backends against the vendored artifacts
# `cbor-vendor-native`/`cbor-vendor-web` produce — the CI-facing recipe
# (cratestack#563), mirroring `frb-verify-client-flutter`'s "regenerate,
# compile, execute for real" discipline rather than stopping at "codegen
# exited 0". Does NOT regenerate the vendored artifacts itself (run the two
# recipes above first, or rely on what's already committed) — this is the
# fast inner loop plus what CI runs after its own vendoring step.
#
# Requires: Dart SDK on PATH, and Chrome/Chromium for the web half
# (`CHROME_EXECUTABLE` if not auto-detected — see `dart test`'s docs).
cbor-verify-package:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v dart >/dev/null; then
	  echo "dart not found on PATH — install the Dart SDK: https://dart.dev/get-dart" >&2
	  exit 1
	fi
	pkg=dart-packages/cratestack_cbor
	echo "=== dart pub get: $pkg ==="
	(cd "$pkg" && dart pub get)
	echo "=== dart test (native backend, @TestOn('vm')): $pkg ==="
	(cd "$pkg" && dart test)
	echo "=== dart test -p chrome (web backend, @TestOn('browser')): $pkg ==="
	(cd "$pkg" && dart test -p chrome)
	echo ""
	echo "✓ cratestack_cbor: both backends round-trip against the vendored artifacts"

# Real Flutter-app proof for cratestack_cbor (cratestack#563 "Flutter app
# integration" slice) — builds dart-packages/cratestack_cbor/example for
# Linux desktop AND web (RELEASE builds, not `flutter run`'s dev server),
# then actually RUNS both and asserts the same shared-fixture CBOR hex the
# package's own `dart test`/`dart test -p chrome` suites assert
# (`test/shared_fixtures.dart`). This is the check `dart test` cannot
# provide on its own: a build that merely compiles proves nothing about
# whether the built app can find its own vendored artifacts at runtime —
# see docs/tooling/cratestack-cbor-development.md.
#
# - Linux: `flutter build linux`, then the built binary is run headless
#   (`xvfb-run` — Flutter's GTK embedder needs a display even with nothing
#   to interact with) and its STDOUT is grepped for the app's
#   `CRATESTACK_CBOR_EXAMPLE_RESULT: OK <hex>` marker
#   (`example/lib/main.dart`). Also asserts the vendored `.so` actually
#   landed inside the built bundle's `lib/` — see `linux/CMakeLists.txt`.
# - Web: `flutter build web` (release), served with a plain static file
#   server (deliberately NOT `flutter run -d chrome`'s dev server — that
#   has a `packages/...` URL route a release deploy does not have, see
#   `lib/src/web/web_cbor_codec.dart`), then driven with a real headless
#   Chrome via the DevTools Protocol
#   (`example/tool/verify_web_console.dart` — plain `dart:io`, no extra
#   package) to capture the same marker from the browser console. Also
#   asserts the vendored `.wasm` landed inside `build/web/assets/`.
#
# Does NOT regenerate the vendored artifacts itself — run
# `just cbor-vendor-native cbor-vendor-web` first (or rely on what's
# already vendored from a prior step, as CI does).
#
# Requires: Flutter SDK (3.44.1 pinned — see the package README), the
# Linux desktop toolchain (GTK3 dev headers, ninja, cmake — see this
# repo's CLAUDE.md), `xvfb-run`, Python 3 (for the static file server), and
# Chrome/Chromium (`CHROME_EXECUTABLE`, defaults to `google-chrome`).
cbor-example-verify:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v flutter >/dev/null; then
	  echo "flutter not found on PATH — install the Flutter SDK: https://docs.flutter.dev/get-started/install" >&2
	  exit 1
	fi
	if ! command -v xvfb-run >/dev/null; then
	  echo "xvfb-run not found — install it (e.g. apt-get install -y xvfb)" >&2
	  exit 1
	fi
	example=dart-packages/cratestack_cbor/example
	expected_hex="a36a6372617465737461636b8264636f6f6c65737461636b616e182a626f6bf5"
	marker="CRATESTACK_CBOR_EXAMPLE_RESULT:"

	# `flutter clean` before anything else: Flutter's incremental-build file
	# store lives in `.dart_tool/flutter_build/`, OUTSIDE `build/`. If
	# `build/` is ever removed independently (a plain `rm -rf build`, as a
	# local rerun of this recipe might do) while that cache survives,
	# Flutter's build system trusts its stale "up to date" record and SKIPS
	# regenerating `build/native_assets/linux/` — an empty directory the
	# generated `linux/CMakeLists.txt` unconditionally installs — so the
	# build fails with a CMake "file INSTALL cannot find ... native_assets/
	# linux" error that has nothing to do with this package. Found the hard
	# way in this PR's own verification; `flutter clean` removes both
	# `build/` and the stale cache together, so there is nothing to
	# desynchronize. CI runners start clean anyway, so this only matters
	# for local reruns, but it costs nothing to always do it.
	echo "=== flutter clean: $example ==="
	(cd "$example" && flutter clean)

	echo "=== flutter pub get: $example ==="
	(cd "$example" && flutter pub get)

	echo "=== flutter analyze: $example ==="
	(cd "$example" && flutter analyze --fatal-warnings --no-fatal-infos)

	echo "=== flutter build linux (release): $example ==="
	(cd "$example" && flutter build linux)
	bin="$example/build/linux/x64/release/bundle/cratestack_cbor_example"
	lib="$example/build/linux/x64/release/bundle/lib/libcratestack_client_flutter.so"
	if [ ! -f "$lib" ]; then
	  echo "FAIL: vendored library not found inside the built bundle at $lib — the Linux plugin scaffolding (linux/CMakeLists.txt) did not bundle it." >&2
	  exit 1
	fi
	echo "✓ vendored library present in the built bundle: $lib"

	echo "=== running the built Linux binary (headless via xvfb-run) ==="
	linux_log="$(mktemp)"
	timeout 15 xvfb-run -a "$bin" > "$linux_log" 2>&1 || true
	if ! grep -q "$marker OK $expected_hex" "$linux_log"; then
	  echo "FAIL: built Linux binary did not print the expected round-trip marker. Captured output:" >&2
	  cat "$linux_log" >&2
	  rm -f "$linux_log"
	  exit 1
	fi
	echo "✓ Linux binary round-tripped CBOR: $(grep "$marker" "$linux_log")"
	rm -f "$linux_log"

	echo "=== flutter build web (release): $example ==="
	(cd "$example" && flutter build web)
	wasm="$example/build/web/assets/packages/cratestack_cbor/lib/src/web/wasm-pkg/cratestack_cbor_wasm_bg.wasm"
	if [ ! -f "$wasm" ]; then
	  echo "FAIL: vendored wasm artifact not found inside the built web bundle at $wasm — the flutter: assets: declaration did not bundle it." >&2
	  exit 1
	fi
	echo "✓ vendored wasm artifact present in the built bundle: $wasm"

	echo "=== serving build/web and driving it with headless Chrome ==="
	port=8934
	(cd "$example/build/web" && python3 -m http.server "$port" >/dev/null 2>&1) &
	server_pid=$!
	trap 'kill "$server_pid" 2>/dev/null || true' EXIT
	ready=0
	for _ in $(seq 1 50); do
	  if curl -sf "http://127.0.0.1:$port/index.html" >/dev/null 2>&1; then
	    ready=1
	    break
	  fi
	  sleep 0.2
	done
	if [ "$ready" -ne 1 ]; then
	  echo "FAIL: static file server for build/web never became ready on port $port" >&2
	  exit 1
	fi
	(cd "$example" && dart run tool/verify_web_console.dart \
	  --url "http://127.0.0.1:$port/index.html" \
	  --expect-hex "$expected_hex")
	kill "$server_pid" 2>/dev/null || true

	echo ""
	echo "✓ cratestack_cbor example: real flutter build linux + flutter build web both round-trip CBOR in a running app"

# Real APK-build proof for cratestack_cbor's Android platform (cratestack#563
# platform-matrix slice). Deliberately does NOT drive an emulator — see the
# "CI cost" note below and docs/tooling/cratestack-cbor-development.md for
# why the emulator run is a separate, local-only recipe
# (`cbor-example-verify-android-emulator`).
#
# `flutter build apk` compiling is necessary but not sufficient: a plugin
# that silently ships no native library still builds fine (that's exactly
# what this ticket exists to catch, per its own acceptance bar), so this
# recipe additionally unzips the built APK and asserts
# `libcratestack_client_flutter.so` is present under `lib/<abi>/` for every
# ABI `cbor-vendor-android` vendors (arm64-v8a, x86_64, armeabi-v7a) —
# mirroring `cbor-example-verify`'s "assert the vendored library is inside
# the built bundle" check for Linux.
#
# CI cost: an NDK cross-compile (`cbor-vendor-android`, 3 ABIs) plus a full
# Gradle `assembleRelease` is real cost on top of what `cratestack-cbor-
# example` (Linux+web) already pays, but it is bounded and finishes in well
# under the emulator alternative — see the emulator recipe's own comment
# for why THAT stays local/manual rather than also running here.
#
# Does NOT regenerate the vendored artifacts itself — run
# `just cbor-vendor-native cbor-vendor-android` first (or rely on what's
# already vendored, as CI does).
#
# Requires: Flutter SDK with the Android toolchain configured
# (`flutter doctor` reporting "Android toolchain" as OK — SDK, a
# build-tools/platform matching this repo's pinned compileSdk, and
# accepted licenses).
cbor-example-verify-android:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v flutter >/dev/null; then
	  echo "flutter not found on PATH — install the Flutter SDK: https://docs.flutter.dev/get-started/install" >&2
	  exit 1
	fi
	example=dart-packages/cratestack_cbor/example

	echo "=== flutter clean: $example ==="
	(cd "$example" && flutter clean)

	echo "=== flutter pub get: $example ==="
	(cd "$example" && flutter pub get)

	echo "=== flutter analyze: $example ==="
	(cd "$example" && flutter analyze --fatal-warnings --no-fatal-infos)

	echo "=== flutter build apk (release): $example ==="
	(cd "$example" && flutter build apk)
	apk="$example/build/app/outputs/flutter-apk/app-release.apk"
	if [ ! -f "$apk" ]; then
	  echo "FAIL: expected APK not found at $apk" >&2
	  exit 1
	fi

	# Captured into a variable rather than piped straight into `grep -q`:
	# under `pipefail`, `unzip -l ... | grep -q pattern` can spuriously
	# report pipeline failure even on a MATCH, because `-q` exits as soon
	# as it finds one, which can send `unzip` a SIGPIPE before it finishes
	# writing — and pipefail then reports that non-zero `unzip` exit as the
	# pipeline's status. Capturing first sidesteps the whole class of bug.
	listing="$(unzip -l "$apk")"
	missing=0
	for abi in arm64-v8a x86_64 armeabi-v7a; do
	  if [[ "$listing" == *"lib/$abi/libcratestack_client_flutter.so"* ]]; then
	    echo "✓ vendored library present in the built APK: lib/$abi/libcratestack_client_flutter.so"
	  else
	    echo "FAIL: vendored library not found inside the built APK for ABI $abi (lib/$abi/libcratestack_client_flutter.so) — the Android plugin scaffolding (android/build.gradle's jniLibs.srcDirs) did not bundle it." >&2
	    missing=1
	  fi
	done
	if [ "$missing" -ne 0 ]; then
	  exit 1
	fi

	echo ""
	echo "✓ cratestack_cbor example: real flutter build apk, vendored library present for every claimed ABI"

# Real ON-DEVICE proof for cratestack_cbor's Android platform: installs the
# release APK built by `cbor-example-verify-android` on a connected
# device/emulator, launches the example app, and asserts it prints the SAME
# CBOR-hex round-trip marker Linux/web print (`test/shared_fixtures.dart`) —
# the one thing an APK build cannot prove on its own (a build that merely
# COMPILES proves nothing about whether the installed app can actually
# `dlopen` its own bundled library at runtime; see cratestack#563's own
# acceptance bar and the "an APK that installs but crashes on
# DynamicLibrary.open" failure mode it names explicitly).
#
# Deliberately LOCAL/MANUAL ONLY — not wired into CI. Running an Android
# emulator in CI is substantially heavier than the (already expensive)
# `cratestack-cbor-example` Linux+web job, and flaky in ways an NDK
# cross-compile + Gradle build is not (boot time, KVM/nested-virtualization
# availability on hosted runners, occasional hangs). The APK-build proof
# above (`cbor-example-verify-android`) is what runs in CI; this recipe is
# the local trust-but-verify companion for a human to run before relying on
# a change, same spirit as `just cbor-vendor-android`'s own "run this
# yourself" posture. See docs/tooling/cratestack-cbor-development.md for
# the full CI-cost writeup.
#
# Requires: `adb` on PATH, `ANDROID_HOME`/`ANDROID_SDK_ROOT` set, and either
# a running emulator or a connected device already visible to `adb devices`
# (`flutter emulators --launch <id>` starts one — see `flutter emulators`
# for the list). Does NOT launch an emulator itself: which one to boot (or
# whether to use a physical device) is a human decision, not something this
# recipe should silently pick.
cbor-example-verify-android-emulator:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v adb >/dev/null; then
	  echo "adb not found on PATH — add \$ANDROID_HOME/platform-tools to PATH" >&2
	  exit 1
	fi
	if ! adb devices | grep -qE '\bdevice$'; then
	  echo "No Android device/emulator visible to 'adb devices'. Start one first, e.g.:" >&2
	  echo "    flutter emulators --launch <id>   # see: flutter emulators" >&2
	  exit 1
	fi
	example=dart-packages/cratestack_cbor/example
	apk="$example/build/app/outputs/flutter-apk/app-release.apk"
	# Build FIRST, every time — do not install whatever APK happens to be
	# lying around. An earlier version of this recipe required the caller to
	# have run `cbor-example-verify-android` beforehand and merely errored if
	# the APK was missing. That is a false-green generator: corrupt a vendored
	# `.so`, run this recipe, and it installs the STALE pre-corruption APK and
	# reports a happy round-trip. Reproduced exactly that way — the run
	# finished 18 seconds after the previous one, far too fast to have rebuilt
	# anything, and passed against a library that had been overwritten with
	# `NOT-AN-ELF`.
	#
	# That matters more here than for most recipes, because this one exists
	# specifically to be the trustworthy on-device check. A verification step
	# that can validate an artifact other than the one on disk is worse than
	# no verification, since it produces confident wrong answers.
	just cbor-example-verify-android
	if [ ! -f "$apk" ]; then
	  echo "$apk missing even after cbor-example-verify-android — that recipe should have built it." >&2
	  exit 1
	fi
	appId="dev.cratestack.examples.cratestack_cbor_example"
	expected_hex="a36a6372617465737461636b8264636f6f6c65737461636b616e182a626f6bf5"
	marker="CRATESTACK_CBOR_EXAMPLE_RESULT:"

	echo "=== installing $apk ==="
	adb install -r "$apk"
	adb shell am force-stop "$appId" || true
	adb logcat -c
	echo "=== launching $appId ==="
	adb shell am start -n "$appId/$appId.MainActivity"

	echo "=== waiting for the round-trip marker in logcat ==="
	found=""
	for _ in $(seq 1 60); do
	  found="$(adb logcat -d | grep "$marker" || true)"
	  if [ -n "$found" ]; then
	    break
	  fi
	  sleep 1
	done
	if [ -z "$found" ]; then
	  echo "FAIL: never saw '$marker' in logcat within the timeout." >&2
	  exit 1
	fi
	echo "$found"
	if ! echo "$found" | grep -q "$marker OK $expected_hex"; then
	  echo "FAIL: app did not report the expected round-trip marker. Captured:" >&2
	  echo "$found" >&2
	  exit 1
	fi

	echo ""
	echo "✓ cratestack_cbor example: real flutter build apk, installed and run on a real Android device/emulator, round-tripped CBOR"

# Bundle the Studio UI for publishing: source tarball (for `studio
# eject --with-ui`) and the Trunk-built wasm/JS dist (embedded into
# the served binary so `cratestack studio run` ships a real admin app
# out of the box). Both files are gitignored; cargo packages them via
# the explicit `include` list in cratestack-studio's Cargo.toml.
#
# Requires the wasm toolchain:
#   cargo install --locked trunk
#   rustup target add wasm32-unknown-unknown
bundle-studio-ui:
	#!/usr/bin/env bash
	set -euo pipefail
	if ! command -v trunk >/dev/null; then
	  echo "trunk not found. Run: cargo install --locked trunk" >&2
	  exit 1
	fi
	src=crates/cratestack-studio/embedded-ui.tar.gz
	dist=crates/cratestack-studio/embedded-ui-dist.tar.gz
	(cd crates/cratestack-studio-ui && trunk build --release)
	tar --exclude='target' \
	    --exclude='Cargo.lock' \
	    --exclude='.gitignore' \
	    --exclude='.trunk' \
	    --exclude='dist' \
	    -czf "$src" \
	    -C crates cratestack-studio-ui
	tar -czf "$dist" -C crates/cratestack-studio-ui/dist .
	echo "wrote $src ($(du -h "$src" | cut -f1))"
	echo "wrote $dist ($(du -h "$dist" | cut -f1))"

# End-to-end publish for cratestack-studio: refresh the embedded UI
# tarball, then publish. `--allow-dirty` is needed because the
# regenerated tarball is gitignored by design (binary, derived from
# the cratestack-studio-ui sibling); we guard the flag by refusing to
# publish if anything else in the crate is dirty.
publish-studio *args='':
	#!/usr/bin/env bash
	set -euo pipefail
	just bundle-studio-ui
	dirty=$(git status --porcelain -- crates/cratestack-studio crates/cratestack-studio-ui \
	        | grep -vE 'crates/cratestack-studio/embedded-ui(-dist)?\.tar\.gz$' || true)
	if [ -n "$dirty" ]; then
	  echo "refusing to publish: uncommitted changes besides embedded-ui tarballs:" >&2
	  echo "$dirty" >&2
	  exit 1
	fi
	cargo publish -p cratestack-studio --allow-dirty {{args}}

# Rewrite every workspace version literal `0.x.y` -> the given NEW
# version. Reads the current version from the workspace `Cargo.toml`,
# applies the substitution to every `Cargo.toml` in the repo (root +
# crates + examples + studio-ui sibling), and refreshes `Cargo.lock`.
# Idempotent: re-running with the same NEW is a no-op.
bump NEW:
	#!/usr/bin/env bash
	set -euo pipefail
	current=$(awk -F'"' '/^version = /{print $2; exit}' Cargo.toml)
	if [ -z "$current" ]; then
	  echo "could not read current version from Cargo.toml" >&2
	  exit 1
	fi
	if [ "$current" = "{{NEW}}" ]; then
	  echo "already at {{NEW}}; nothing to do"
	  exit 0
	fi
	echo "bumping $current -> {{NEW}}"
	# `perl -i` instead of `sed -i` for portability: BSD sed (macOS)
	# requires `-i ''` while GNU sed (Linux/CI) rejects the empty arg,
	# so a single recipe can't satisfy both. perl's in-place edit is
	# identical across platforms. `quotemeta` on the current version makes
	# its dots match literally rather than as `.` wildcards.
	#
	# Scoped to the VALUE OF A `version =` KEY, on either a package-version
	# line (`^version = "X"`, i.e. the root workspace package and the
	# excluded studio-ui sibling) or a workspace inter-crate dependency line
	# (which always carries `path = "crates/"`). Replacing the bare literal
	# `"X"` everywhere instead — as this recipe used to — also rewrites
	# unrelated third-party dependencies that happen to sit at the same
	# version: bumping 0.7.1 -> 0.7.2 turned `serde_urlencoded = "0.7.1"`
	# (root Cargo.toml) into `"0.7.2"`, which does not exist on crates.io,
	# and the release failed at `cargo update` with "failed to select a
	# version for the requirement `serde_urlencoded = ^0.7.2`". The bug is
	# dormant for most bumps — it only fires when the new workspace version
	# collides with some dependency's — so scope this narrowly rather than
	# relying on the collision not recurring.
	find . -name Cargo.toml \
	  -not -path './target/*' \
	  -not -path '*/node_modules/*' \
	  -print0 | CS_CUR="$current" CS_NEW="{{NEW}}" xargs -0 perl -i -pe '
	    BEGIN { $cur = quotemeta $ENV{CS_CUR}; $new = $ENV{CS_NEW}; }
	    if (/^version = "$cur"/ || m{path = "crates/}) {
	      s/version = "$cur"/version = "$new"/g;
	    }'
	# Keep every package this repo ships under `packages/` in lockstep with
	# the workspace version: the @cratestack/cli npm wrapper (and the
	# release asset tag it downloads), the split @cratestack/api family
	# (ts-types, link-*, runtime-*, validator-*, adapter-*, and the api
	# compat shim), the @cratestack/cbor family (cbor, cbor-node,
	# cbor-web), @cratestack/refine, and the cratestack-vscode extension.
	# vscode's vsix is built and versioned per release tag
	# (release-vscode.yml attaches it to the same GitHub Release as the CLI
	# binaries), so it moves in lockstep like the rest rather than staying
	# pinned independently.
	#
	# DISCOVERED by glob, not enumerated. The previous hardcoded list went
	# stale the moment `packages/cratestack-refine` landed (#577): the new
	# package kept its old version through a bump, which would then make
	# release-cli.yml's publish job re-publish an already-live version and
	# hard-fail the release. Every directory under `packages/` is
	# version-locked to the workspace today; if one ever must NOT be, add
	# an explicit exclusion here rather than reverting to a manual list.
	# `packages/*/package.json` is one level deep, so it can't reach into a
	# package's own `node_modules/`. The glob is scoped to `packages/`, not
	# the unrelated example apps' package.json files.
	#
	# A single literal-string replace (not just the `"version": "..."` key)
	# also catches each package's own pinned `"@cratestack/xyz": "$current"`
	# cross-references to its siblings, which need to move in lockstep too.
	perl -i -pe "s/\Q\"$current\"\E/\"{{NEW}}\"/g" packages/*/package.json
	# Refresh pnpm-lock.yaml so the version-literal edits above (which change
	# specifiers like `"@cratestack/ts-types": "{{NEW}}"`) are reflected in the
	# lockfile's `specifier:` entries too — otherwise a later `pnpm install
	# --frozen-lockfile` (every CI job, including release-cli.yml's npm
	# publish) fails with ERR_PNPM_OUTDATED_LOCKFILE. CRATESTACK_CLI_SKIP_DOWNLOAD
	# skips cratestack-cli-npm's postinstall download of a release binary that
	# doesn't exist yet at bump time (nothing has been tagged/published).
	# `--no-frozen-lockfile` is required explicitly: pnpm auto-detects CI
	# environments and defaults to frozen-lockfile there even without the
	# flag, which would make this step fail on the exact staleness it's
	# meant to fix (confirmed the hard way — this recipe's own first version
	# broke `prepare-release.yml`'s "Bump workspace version" step in CI).
	CRATESTACK_CLI_SKIP_DOWNLOAD=1 pnpm install --no-frozen-lockfile
	# Same lockstep treatment for dart-packages/cratestack_cbor (cratestack#563
	# pub.dev publish slice) — this recipe used to touch only `packages/`
	# (npm) and Cargo.toml, leaving `dart-packages/cratestack_cbor/pubspec.yaml`
	# at whatever version it last carried. That is exactly the drift class
	# the `packages/*/package.json` comment above warns about, just for a
	# third registry: the pub.dev publish workflow version-locks to the
	# workspace version the same way the npm packages do (see
	# docs/tooling/dart-publishing.md), so an un-bumped pubspec.yaml would
	# make `publish-pubdev-cbor` in release-cli.yml try to republish an
	# already-live version on the next tag and hard-fail (pub.dev has no
	# skip-if-already-published path, unlike `publish-crates`).
	#
	# `pubspec.yaml`'s version key is unquoted YAML (`version: 0.8.0`, not
	# `"version": "0.8.0"`), so this is a separate substitution from the
	# npm one above, not a shared regex. Glob is one level deep
	# (`dart-packages/*/pubspec.yaml`) so it can't reach
	# `dart-packages/cratestack_cbor/example/pubspec.yaml` — that's an
	# application target with its own independent `1.0.0+1` build-number
	# scheme (see its own pubspec's comment), not a published package, and
	# must NOT move in lockstep with the workspace version.
	perl -i -pe "s/^version: \Q$current\E\$/version: {{NEW}}/" dart-packages/*/pubspec.yaml
	# Refresh Cargo.lock so all entries pick up the new version.
	# Exclude the Flutter crate (uncommitted frb_generated glue → E0583).
	cargo check --workspace --exclude embedded_flutter_native --quiet
	# cratestack-studio-ui is its own separate `[workspace]` (excluded from
	# the root one so contributors aren't forced onto the wasm32 toolchain),
	# so it has its own Cargo.lock that the check above never touches. Left
	# unrefreshed here, it silently drifts stale — its own recorded version
	# stays behind Cargo.toml's — which then breaks any `--locked` build of
	# that crate until someone notices and hand-fixes it (see #242). A plain
	# `cargo check` on the host target is enough to update the lock; it
	# doesn't need the wasm32 target or a wasm-capable clang for that.
	#
	# Subshell, not a bare `cd`: this recipe continues below with more
	# repo-root-relative paths, and a bare `cd` here leaks its directory
	# change into every one of them. That is exactly what broke `just bump
	# 0.7.9` in `prepare-release.yml` — the next line failed with `cd:
	# examples/no-database-verification: No such file or directory`, because
	# the shell was still sitting in `crates/cratestack-studio-ui`.
	(cd crates/cratestack-studio-ui && cargo check --quiet)
	# `examples/no-database-verification`, `-api`, and
	# `client-only-verification` are each their own `[workspace]` root
	# (excluded from the root one so a real `cargo tree` proves facade
	# disjointness for an external consumer — see their READMEs), so like
	# cratestack-studio-ui above they have their own Cargo.lock that the
	# root `cargo check` never touches. Left unrefreshed here, their locked
	# `cratestack-pg`/`cratestack-api`/`cratestack-client` path-dependency
	# versions silently drift behind the workspace version, which then
	# breaks any `--locked` build/`cargo tree` in either directory — this is
	# exactly the staleness that left them at 0.6.3/0.6.4 against 0.7.8
	# (cratestack#422), and what CI's `facade-disjointness` job now asserts
	# against with `cargo metadata --locked`.
	#
	# DISCOVERED, NOT LISTED. This used to be three hardcoded `cd` lines
	# with a comment warning that "every standalone workspace under
	# examples/ must be listed here; adding one without a line below is a
	# latent CI break that only fires on the next bump". That is precisely
	# what happened: `examples/db-transaction-verification` arrived with
	# cratestack#539, was never added to the list, and v0.7.13 shipped with
	# its Cargo.lock still pinned to 0.7.12 — turning `main` red on the
	# `facade-disjointness` job ("cannot update the lock file ... because
	# --locked was passed") and blocking the next release. A warning
	# comment is not a mechanism; globbing for `[workspace]` is.
	#
	# Subshells (not a bare `cd`) so each step's directory change doesn't
	# leak into the next, same as the cratestack-studio-ui step above —
	# every directory-changing step in this recipe must be a subshell, since
	# each is followed by more repo-root-relative paths. A plain
	# `cargo check` in each is enough
	# to refresh the lock; Cargo.lock records the full optional-dependency
	# graph regardless of which features are active, so this also picks up
	# the `postgres`-gated cratestack-sqlx entry in no-database-verification
	# without needing `--features postgres` here.
	found_standalone=0
	for manifest in examples/*/Cargo.toml; do
	  grep -q '^\[workspace\]' "$manifest" || continue
	  dir=$(dirname "$manifest")
	  found_standalone=$((found_standalone + 1))
	  echo "refreshing standalone workspace lockfile: $dir"
	  (cd "$dir" && cargo check --quiet)
	done
	# Positive assertion: if the glob ever matches nothing (layout change,
	# a `for` loop that silently iterated over a literal `examples/*`),
	# fail loudly rather than bumping with every standalone lockfile left
	# stale — the silent-skip failure mode this block exists to prevent.
	if [ "$found_standalone" -eq 0 ]; then
	  echo "no standalone [workspace] found under examples/ — the discovery glob is broken" >&2
	  exit 1
	fi
	echo "bumped to {{NEW}}. Review with: git diff -- '**/Cargo.toml' Cargo.lock"

# Seed a CHANGELOG.md section for the given VERSION.
#
# Writes a new `## X.Y.Z (YYYY-MM-DD)` section to CHANGELOG.md, positioned
# above the current newest entry, seeded from the commit range since the last
# release and grouped by conventional-commit type. The section is marked as
# unedited (with a placeholder TODO comment) so CI/tooling can detect it and
# block the merge until a human rewrites it into narrative prose.
#
# Usage: `just changelog-seed 0.7.9`
#
# Non-negotiables (enforced by the script):
#   1. Refuse to write if a section for that version already exists
#   2. The generated section must be detected and rejected by CI if unedited
#
# This script mirrors `.github/workflows/prepare-release.yml:202`'s existing
# commit-range machinery, but outputs to a persistent file instead of
# discarding it.
changelog-seed VERSION:
	./.ci/changelog-seed.sh {{VERSION}}

# Workspace-wide validation gate. Mirrors what `just release` runs
# before publishing. Skips fmt + clippy because `all-checks` is the
# canonical pre-PR gate for those (it auto-fixes); release-check
# focuses on what must hold for a clean publish.
#
# Bundles the Studio UI first (requires trunk + wasm32-unknown-unknown,
# same as `just release-publish`'s own cratestack-studio step needs
# later): without it, `cratestack-studio`'s build.rs falls back to a
# placeholder admin UI, and its own `api_smoke` tests
# (`root_serves_bundled_ui_index_when_feature_on`,
# `unknown_static_path_falls_back_to_index_html`) assert on the REAL
# trunk-built UI and fail on a fresh checkout with no prior local Trunk
# build lying around. On a dev machine that already runs `trunk serve`
# regularly this is usually masked by leftover build artifacts — it only
# reliably surfaces on a clean environment (e.g. CI).
#
# Emergency override: `SKIP_TESTS=1 just release-check` bypasses the
# test stage entirely.
release-check:
	#!/usr/bin/env bash
	set -euo pipefail
	just bundle-studio-ui
	cargo check --workspace --exclude embedded_flutter_native --all-targets
	if [ "${SKIP_TESTS:-0}" = "1" ]; then
	  echo "release-check: SKIP_TESTS=1 — bypassing workspace tests." >&2
	  exit 0
	fi
	cargo test --workspace --exclude embedded_flutter_native

# Publish every workspace crate to crates.io in dependency order.
#
# The order is computed at recipe-time by topologically sorting the
# workspace graph from `cargo metadata`, so it can't drift when a new
# inter-crate dependency lands. Previously a hand-maintained list in
# this file (and in RELEASE.md) silently broke when cratestack-studio
# took on a cratestack-migrate dep but migrate stayed later in the list.
#
# Idempotent: each crate is checked against the crates.io API for the
# current workspace version before publishing — already-uploaded
# versions are skipped, so reruns after a partial failure pick up
# where they left off. Use `FROM=cratestack-studio just release-publish`
# to skip straight to a specific crate without hitting crates.io for
# the earlier ones.
#
# `dry` mode runs `cargo publish --dry-run` (packages + verifies each
# but skips upload). Pairs with `just bump` for the version step and
# `just release` for the full end-to-end flow.
release-publish mode='real':
	#!/usr/bin/env bash
	# Note: `set +e` here — we want to detect "already uploaded" errors
	# rather than abort the whole loop on them. Each command's exit
	# status is checked explicitly.
	set -uo pipefail
	if [ "{{mode}}" != "real" ] && [ "{{mode}}" != "dry" ]; then
	  echo "usage: just release-publish [real|dry]" >&2
	  exit 2
	fi
	# Compute the publish order by topo-sorting cratestack-* workspace
	# packages from `cargo metadata`. Requires python3 (ubiquitous on
	# dev machines). On failure (parse, cycle, missing python) the
	# error is loud and the recipe aborts before touching crates.io.
	#
	# Also computes `dry_safe_packages`: the packages with NO internal
	# cratestack-* dependency at all (currently just `cratestack` and
	# `cratestack-core`). This is the actual set `dry` mode can ever
	# meaningfully package-check for a version that has never been
	# published anywhere before — see the `--allow-dirty`/dry-run
	# handling below for why every other crate is structurally
	# unpackageable in that situation, no matter what flags are passed.
	topo_output=$(cargo metadata --format-version=1 --no-deps | \
	  python3 -c "$(cat <<'PYEOF'
	import json, sys, copy
	m = json.load(sys.stdin)
	pkgs = {p["name"]: p for p in m["packages"]
	        if p["name"].startswith("cratestack") and p.get("publish") != []}
	# What constrains publish order is NOT the dependency's kind — it is
	# whether the edge survives into the published manifest. `cargo
	# publish` strips a path-only dependency (no `version` field), which
	# `cargo metadata` reports as `req == "*"`. Any edge carrying a real
	# version requirement must resolve from the registry at package time,
	# so the dependency has to be published first — dev-dependencies very
	# much included.
	#
	# Both mistakes have now been made here, so both are worth recording:
	#
	#   - Counting every edge (original): read the legitimate pair
	#     `cratestack-macros --dev--> cratestack-api` (path-only, req="*")
	#     against `cratestack-api -> cratestack-macros` (normal) as a hard
	#     cycle, and aborted the whole publish.
	#   - Excluding every dev edge (cratestack#564): dropped the real
	#     constraint `cratestack-client-store-sqlite --dev--> cratestack-
	#     client-rust` (req="^0.7.x", inherited from `[workspace.
	#     dependencies]`, which carries a version), producing an order that
	#     published store-sqlite before client-rust. cargo then failed with
	#     "failed to select a version for the requirement
	#     cratestack-client-rust = ^0.7.14" — after three crates had
	#     already uploaded.
	#
	# So: keep every edge with a concrete version requirement regardless of
	# kind, and drop only the path-only ones cargo will strip anyway.
	graph = {n: {d["name"] for d in p["dependencies"]
	             if d["name"] in pkgs and d["name"] != n
	             and d["req"] != "*"}
	         for n, p in pkgs.items()}
	dry_safe = sorted(n for n, d in graph.items() if not d)
	order, remaining = [], copy.deepcopy(graph)
	while remaining:
	    leaves = sorted(n for n, d in remaining.items() if not d)
	    if not leaves:
	        sys.exit(f"dependency cycle: {remaining}")
	    for n in leaves:
	        order.append(n); del remaining[n]
	    for d in remaining.values():
	        d.difference_update(leaves)
	# NOTE on verification: there is deliberately no post-sort
	# "publishability" assertion here. One was written and removed during
	# review — it iterated the same edge set the graph is built from, and
	# Kahn's sort already guarantees that ordering, so it could never fire.
	# It looked like a safety net and was not one, which is the same class
	# of mistake cratestack#564 shipped (a change "verified" by observing
	# that the sort still produced output). The protection here is the edge
	# predicate above being correct, not a check downstream of it. A
	# genuinely independent check would have to compare against cargo's own
	# behaviour — `cargo publish --dry-run` in order — which needs the
	# network and a registry state, and is not something this recipe can do
	# offline.
	print(" ".join(order))
	print(" ".join(dry_safe))
	PYEOF
	)")
	publish_order=$(printf '%s\n' "$topo_output" | sed -n '1p')
	dry_safe_packages=$(printf '%s\n' "$topo_output" | sed -n '2p')
	if [ -z "$publish_order" ]; then
	  echo "failed to compute publish order from cargo metadata" >&2
	  exit 1
	fi
	dry=""
	# --no-verify alongside --dry-run: for the handful of packages dry
	# mode does attempt (see dry_safe_packages above), skip the
	# compile-verification step — it's redundant with `release-check`'s
	# own `cargo check --workspace` earlier in the same pipeline, and
	# just wastes time. Real mode is unaffected and still fully
	# verifies each crate.
	[ "{{mode}}" = "dry" ] && dry="--dry-run --no-verify"
	version=$(awk -F'"' '/^version = /{print $2; exit}' Cargo.toml)
	from="${FROM:-}"
	skipping=true
	[ -z "$from" ] && skipping=false

	# Returns 0 if `crate@version` is already published on crates.io.
	# Uses the JSON API; falls back to "not published" on any network
	# error so we surface a fresh publish failure rather than masking it.
	is_published() {
	  local pkg=$1 ver=$2
	  curl -fsS -A "cratestack-release/1.0" \
	    "https://crates.io/api/v1/crates/$pkg/$ver" \
	    -o /dev/null 2>/dev/null
	}

	# Run a single `cargo publish` and classify the outcome:
	#   0 = published or already uploaded (idempotent success)
	#   1 = real failure (caller decides retry vs abort)
	publish_once() {
	  local pkg=$1 extra=$2
	  local out rc
	  out=$(cargo publish -p "$pkg" $extra $dry 2>&1)
	  rc=$?
	  printf '%s\n' "$out"
	  if [ $rc -eq 0 ]; then
	    return 0
	  fi
	  if printf '%s' "$out" | grep -qE 'already (uploaded|exists)'; then
	    echo "  → already uploaded, treating as success"
	    return 0
	  fi
	  return 1
	}

	bundled=false
	bundle_studio() {
	  if [ "$bundled" = "false" ]; then
	    just bundle-studio-ui >&2
	    bundled=true
	  fi
	}

	failed=""
	for pkg in $publish_order; do
	  if [ "$skipping" = "true" ]; then
	    if [ "$pkg" = "$from" ]; then
	      skipping=false
	    else
	      echo "skipping $pkg (before FROM=$from)"
	      continue
	    fi
	  fi

	  echo ""
	  echo "=== $pkg @ $version ==="

	  # Cheap pre-check: if already on crates.io, skip the cargo publish
	  # round-trip entirely. Only meaningful in real mode; dry runs
	  # always want to exercise the package + verify path.
	  if [ "{{mode}}" = "real" ] && is_published "$pkg" "$version"; then
	    echo "  → already on crates.io, skipping"
	    continue
	  fi

	  # A crate with an internal cratestack-* dependency can NEVER be
	  # packaged in dry mode for a version that has never been published
	  # anywhere before: cargo resolves path+version workspace deps
	  # against the REAL crates.io index even just to build the package
	  # manifest (not only to verify/compile it), and a dry-run publish
	  # always "aborts upload" — so an earlier crate's new version never
	  # actually lands in that index for a later one to resolve against.
	  # This is a structural cargo limitation, not fixable with
	  # --allow-dirty/--no-verify/any other flag (confirmed locally: even
	  # RELEASE.md's own `cargo package --allow-dirty --no-verify`
	  # recipe fails identically). Only the packages with zero internal
	  # deps (dry_safe_packages, computed above) can ever be meaningfully
	  # dry-run in this situation — skip everything else with a clear
	  # explanation instead of attempting a guaranteed failure.
	  if [ "{{mode}}" = "dry" ]; then
	    case " $dry_safe_packages " in
	      *" $pkg "*) ;;
	      *)
	        echo "  → skipping dry-run package check: $pkg depends on another"
	        echo "    cratestack-* crate whose new version was never actually"
	        echo "    published (dry-run never uploads) — cargo can't resolve"
	        echo "    that dependency, no matter what flags are passed. See"
	        echo "    release-publish's comments in the justfile for detail."
	        continue
	        ;;
	    esac
	  fi

	  extra=""
	  if [ "{{mode}}" = "dry" ]; then
	    # Dry-run packaging verification is meant to work against an
	    # uncommitted version bump too — e.g. a CI dry-run rehearsal that
	    # deliberately never commits (unlike `just release VERSION dry`,
	    # which always commits the bump first regardless of mode). Never
	    # uploads anything, so allowing a dirty tree here is safe.
	    extra="--allow-dirty"
	  fi
	  if [ "$pkg" = "cratestack-studio" ]; then
	    # Re-bundle right before studio's publish so OUT_DIR matches the
	    # current sibling state, even if a prior loop iteration cleaned it.
	    bundle_studio
	    extra="--allow-dirty"
	  fi

	  if publish_once "$pkg" "$extra"; then
	    continue
	  fi
	  echo "  → first attempt failed; sleeping 30s and retrying once..." >&2
	  sleep 30
	  if publish_once "$pkg" "$extra"; then
	    continue
	  fi
	  failed="$pkg"
	  break
	done

	if [ -n "$failed" ]; then
	  echo "" >&2
	  echo "release-publish failed at $failed." >&2
	  echo "Resume with: FROM=$failed just release-publish {{mode}}" >&2
	  exit 1
	fi

# End-to-end release: bump version, validate, publish all crates, tag,
# and push. Refuses to run on a dirty working tree (besides the
# studio's regenerated tarballs). Tag push is opt-in via PUSH=1.
#
# Usage:
#   just release 0.3.4          # bump, validate, publish, tag locally
#   PUSH=1 just release 0.3.4   # also push commit + tag to origin
#   just release 0.3.4 dry      # rehearsal: dry-run publishes, no tag
release VERSION mode='real':
	#!/usr/bin/env bash
	set -euo pipefail
	if [ "{{mode}}" != "real" ] && [ "{{mode}}" != "dry" ]; then
	  echo "usage: just release VERSION [real|dry]" >&2
	  exit 2
	fi
	just bump {{VERSION}}
	just release-check
	# Commit the bump (unless already committed). Studio tarballs are
	# gitignored by design and don't get staged.
	#
	# `':(glob)packages/*/package.json'`, NOT a hand-listed pair. `bump`
	# rewrites EVERY `packages/*/package.json` (see its own comment on why
	# the hardcoded list there was replaced), so naming only cli-npm and
	# api left the other 14 packages' version bumps uncommitted — silently,
	# since `bump` really did rewrite them in the working tree. A release
	# cut through this path then tags a tree where most packages still
	# carry the previous version, and the next CI publish hits
	# EPUBLISHCONFLICT on whichever ones did move.
	#
	# prepare-release.yml already carries the identical glob fix (#581) with
	# the same reasoning; it was never backported here, so the documented
	# local fallback in RELEASE.md kept the bug the CI path had shed.
	#
	# `':(glob)dart-packages/*/pubspec.yaml'` for the same reason, one
	# registry later (cratestack#563): `just bump` above now rewrites
	# `dart-packages/cratestack_cbor/pubspec.yaml` in the working tree, and
	# missing it here would silently drop that bump from the release
	# commit — same failure shape as the `packages/*/package.json` bug this
	# comment already describes.
	if ! git diff --quiet -- '**/Cargo.toml' Cargo.lock ':(glob)packages/*/package.json' ':(glob)dart-packages/*/pubspec.yaml'; then
	  git add ':(glob)**/Cargo.toml' Cargo.lock pnpm-lock.yaml \
	    ':(glob)packages/*/package.json' ':(glob)dart-packages/*/pubspec.yaml'
	  git commit -m "chore: bump workspace to v{{VERSION}}"
	fi
	just release-publish {{mode}}
	if [ "{{mode}}" = "real" ]; then
	  git tag "v{{VERSION}}"
	  if [ "${PUSH:-0}" = "1" ]; then
	    git push origin HEAD "v{{VERSION}}"
	  else
	    echo "tagged v{{VERSION}} locally. Push with: git push origin HEAD v{{VERSION}}"
	  fi
	fi
