//! End-to-end test for the `@readonly` / `@server_only` field attributes.
//!
//! The two attributes share a server-controls-the-value purpose but differ
//! in what they hide:
//! - `@readonly` is absent from Create/Update inputs at the *type level* —
//!   verified at compile time by the input-construction tests below
//!   (omitting the field is the only way to build the struct).
//! - `@server_only` adds JSON skip-serializing on top, so the value is
//!   readable from server-side Rust but invisible to clients.

use cratestack::axum::body::{Body, to_bytes};
use cratestack::axum::http::{Request, StatusCode};
use cratestack::include_schema;
use cratestack::sqlx::postgres::PgPoolOptions;
use cratestack::sqlx::query;
use cratestack::{AuthProvider, CoolCodec, CoolContext, CoolError, RequestContext, Value};
use cratestack_codec_json::JsonCodec;
use tower::util::ServiceExt;

include_schema!("tests/fixtures/banking_field_policy.cstack");

async fn serial_guard() -> tokio::sync::MutexGuard<'static, ()> {
    static M: tokio::sync::Mutex<()> = tokio::sync::Mutex::const_new(());
    M.lock().await
}

async fn connect_or_skip() -> Option<cratestack::sqlx::PgPool> {
    let database_url = std::env::var("CRATESTACK_TEST_DATABASE_URL").ok()?;
    PgPoolOptions::new()
        .max_connections(2)
        .connect(&database_url)
        .await
        .ok()
}

async fn reset_schema(pool: &cratestack::sqlx::PgPool) {
    query("DROP TABLE IF EXISTS cratestack_event_outbox, vaults")
        .execute(pool)
        .await
        .expect("drop");
    // Real banking shape: server-controlled columns get defaults so the
    // INSERT generated by the macro (which omits readonly/server_only
    // columns) still satisfies the schema.
    query(
        "CREATE TABLE vaults (
            id BIGINT PRIMARY KEY,
            name TEXT NOT NULL,
            balance BIGINT NOT NULL DEFAULT 0,
            internal_score BIGINT NOT NULL DEFAULT 0
        )",
    )
    .execute(pool)
    .await
    .expect("create account");
}

fn ctx() -> CoolContext {
    CoolContext::authenticated([("id".to_owned(), Value::Int(1))])
}

#[derive(Clone)]
struct PassThroughAuth;

impl AuthProvider for PassThroughAuth {
    type Error = CoolError;
    fn authenticate(
        &self,
        _request: &RequestContext<'_>,
    ) -> impl core::future::Future<Output = Result<CoolContext, Self::Error>> + Send {
        core::future::ready(Ok(ctx()))
    }
}

/// Build a Create input — proves at compile time that `balance` and
/// `internalScore` are NOT part of the input struct, because we don't set
/// them and the struct is non-exhaustive only through field-by-field
/// initialisation.
#[allow(dead_code)]
fn build_create_input() -> cratestack_schema::CreateVaultInput {
    cratestack_schema::CreateVaultInput {
        id: 1,
        name: "test".to_owned(),
        // intentionally NO `balance` or `internalScore` — they're not on
        // the type. If they were, this expression would fail to compile.
    }
}

/// Same for the Update input. PATCH bodies must not be allowed to set
/// either field even with `Some(value)` — they're absent from the struct.
#[allow(dead_code)]
fn build_update_input() -> cratestack_schema::UpdateVaultInput {
    cratestack_schema::UpdateVaultInput {
        name: Some("updated".to_owned()),
    }
}

#[tokio::test]
async fn server_only_field_is_stripped_from_json_responses() {
    let _guard = serial_guard().await;
    let Some(pool) = connect_or_skip().await else {
        return;
    };
    reset_schema(&pool).await;
    query(
        "INSERT INTO vaults (id, name, balance, internal_score) \
         VALUES (1, 'Audited', 1000, 87)",
    )
    .execute(&pool)
    .await
    .expect("seed");

    let cool = cratestack_schema::Cratestack::builder(pool.clone()).build();

    // Server-side: the Rust struct still surfaces the field, so backend
    // code can use it for risk decisions.
    let row = cool
        .vault()
        .find_unique(1)
        .run(&ctx())
        .await
        .expect("fetch")
        .expect("exists");
    assert_eq!(row.internalScore, 87);

    // Client-side: the same record encoded as JSON via the codec must
    // never include `internalScore`.
    let router = cratestack_schema::axum::model_router(cool, JsonCodec, PassThroughAuth);
    let response = router
        .oneshot(
            Request::get("/vaults/1")
                .header("accept", JsonCodec::CONTENT_TYPE)
                .body(Body::empty())
                .expect("req"),
        )
        .await
        .expect("get");
    assert_eq!(response.status(), StatusCode::OK);
    let bytes = to_bytes(response.into_body(), 1024 * 1024)
        .await
        .expect("body");
    let text = std::str::from_utf8(&bytes).expect("utf8");
    assert!(
        !text.contains("internalScore"),
        "server_only field must not appear in JSON response: {text}",
    );
    assert!(
        text.contains("name"),
        "non-classified fields must still be present: {text}",
    );
}

#[tokio::test]
async fn requesting_server_only_field_via_fields_query_is_rejected() {
    let _guard = serial_guard().await;
    let Some(pool) = connect_or_skip().await else {
        return;
    };
    reset_schema(&pool).await;
    query("INSERT INTO vaults (id, name) VALUES (1, 'X')")
        .execute(&pool)
        .await
        .expect("seed");

    let cool = cratestack_schema::Cratestack::builder(pool.clone()).build();
    let router = cratestack_schema::axum::model_router(cool, JsonCodec, PassThroughAuth);

    let response = router
        .oneshot(
            Request::get("/vaults/1?fields=internalScore")
                .header("accept", JsonCodec::CONTENT_TYPE)
                .body(Body::empty())
                .expect("req"),
        )
        .await
        .expect("get");

    // Selection validation rejects unknown fields with 400/422 — either
    // is acceptable, both communicate the same intent.
    assert!(
        matches!(
            response.status(),
            StatusCode::BAD_REQUEST | StatusCode::UNPROCESSABLE_ENTITY
        ),
        "selecting server_only field should be rejected, got {}",
        response.status(),
    );
}

#[tokio::test]
async fn readonly_field_is_not_writable_via_http_patch() {
    let _guard = serial_guard().await;
    let Some(pool) = connect_or_skip().await else {
        return;
    };
    reset_schema(&pool).await;
    query("INSERT INTO vaults (id, name, balance) VALUES (1, 'Locked', 100)")
        .execute(&pool)
        .await
        .expect("seed");

    let cool = cratestack_schema::Cratestack::builder(pool.clone()).build();
    let router = cratestack_schema::axum::model_router(cool, JsonCodec, PassThroughAuth);

    // The PATCH body tries to set `balance` (which is `@readonly`). The
    // generated `UpdateAccountInput` doesn't have that field, so JSON
    // deserialization either ignores it (silent) or errors. Either way,
    // the underlying `balance` must remain unchanged.
    let _ = router
        .oneshot(
            Request::patch("/vaults/1")
                .header("content-type", JsonCodec::CONTENT_TYPE)
                .header("accept", JsonCodec::CONTENT_TYPE)
                .body(Body::from(r#"{"balance": 999, "name": "Renamed"}"#))
                .expect("req"),
        )
        .await
        .expect("patch");

    let row = query("SELECT balance, name FROM vaults WHERE id = 1")
        .fetch_one(&pool)
        .await
        .expect("read");
    let balance: i64 = cratestack::sqlx::Row::get(&row, "balance");
    let name: String = cratestack::sqlx::Row::get(&row, "name");
    assert_eq!(
        balance, 100,
        "balance must not change through PATCH because it is @readonly",
    );
    // The name update may or may not have been applied depending on how
    // strict the codec is about unknown keys; either way, the readonly
    // column must be untouched.
    let _ = name;
}
