use cratestack::axum::body::{Body, to_bytes};
use cratestack::axum::http::{Request, StatusCode};
use cratestack::include_schema;
use cratestack::sqlx::postgres::PgPoolOptions;
use cratestack::{AuthProvider, CoolCodec, CoolContext, CoolError, RequestContext, Value};
use cratestack_codec_cbor::CborCodec;
use std::sync::{
    Arc, Mutex,
    atomic::{AtomicBool, Ordering},
};
use tower::util::ServiceExt;

include_schema!("tests/fixtures/blog.cstack");

#[derive(Clone)]
struct PolicyDbAuthProvider;

impl AuthProvider for PolicyDbAuthProvider {
    type Error = cratestack::CoolError;

    fn authenticate(
        &self,
        request: &RequestContext<'_>,
    ) -> impl core::future::Future<Output = Result<CoolContext, Self::Error>> + Send {
        let id = request
            .headers
            .get("x-auth-id")
            .and_then(|value| value.to_str().ok())
            .and_then(|value| value.parse::<i64>().ok());

        core::future::ready(Ok(match id {
            Some(id) => CoolContext::authenticated([("id".to_owned(), Value::Int(id))]),
            None => CoolContext::anonymous(),
        }))
    }
}

#[tokio::test]
async fn db_backed_policy_enforcement() {
    let database_url = match std::env::var("CRATESTACK_TEST_DATABASE_URL") {
        Ok(url) => url,
        Err(_) => return,
    };

    let pool = match PgPoolOptions::new()
        .max_connections(1)
        .connect(&database_url)
        .await
    {
        Ok(pool) => pool,
        Err(_) => return,
    };

    cratestack::sqlx::query("DROP TABLE IF EXISTS cratestack_event_outbox, posts, users, profiles")
        .execute(&pool)
        .await
        .expect("eventing test tables should reset");

    cratestack::sqlx::query(
        "CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY, email TEXT NOT NULL, role TEXT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("users table should exist");
    cratestack::sqlx::query(
        "CREATE TABLE IF NOT EXISTS profiles (id BIGINT PRIMARY KEY, nickname TEXT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("profiles table should exist");
    cratestack::sqlx::query(
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_id BIGINT NOT NULL DEFAULT 1",
    )
    .execute(&pool)
    .await
    .expect("users profile_id column should exist");
    cratestack::sqlx::query(
        "CREATE TABLE IF NOT EXISTS posts (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title TEXT NOT NULL, subtitle TEXT, published BOOLEAN NOT NULL, author_id BIGINT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("posts table should exist");
    cratestack::sqlx::query(
        "CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, external_id UUID NOT NULL, label TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, user_id BIGINT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("sessions table should exist");
    cratestack::sqlx::query("TRUNCATE TABLE posts, users, sessions, profiles")
        .execute(&pool)
        .await
        .expect("tables should be truncated");

    cratestack::sqlx::query("INSERT INTO profiles (id, nickname) VALUES (1, 'Zulu'), (2, 'Alpha')")
        .execute(&pool)
        .await
        .expect("profiles should seed");
    cratestack::sqlx::query("INSERT INTO users (id, email, role, profile_id) VALUES (1, 'owner@example.com', 'member', 1), (2, 'other@example.com', 'member', 2)")
        .execute(&pool)
        .await
        .expect("users should seed");
    cratestack::sqlx::query(
        "INSERT INTO posts (id, title, subtitle, published, author_id) VALUES (1, 'Published', NULL, TRUE, 1), (2, 'Draft', NULL, FALSE, 1), (3, 'Other Draft', NULL, FALSE, 2)",
    )
    .execute(&pool)
    .await
    .expect("posts should seed");
    cratestack::sqlx::query(
        "INSERT INTO sessions (id, external_id, label, created_at, revoked_at, user_id) VALUES ('cprimarysession1', '11111111-1111-1111-1111-111111111111', 'Primary Session', '2026-01-01T00:00:00Z', NULL, 1), ('crevokedsession2', '22222222-2222-2222-2222-222222222222', 'Revoked Session', '2026-01-02T00:00:00Z', '2026-01-03T00:00:00Z', 2)",
    )
    .execute(&pool)
    .await
    .expect("sessions should seed");

    let cool = cratestack_schema::Cratestack::builder(pool.clone()).build();
    let anonymous = CoolContext::anonymous();
    let owner = CoolContext::authenticated([("id".to_owned(), Value::Int(1))]);
    let other = CoolContext::authenticated([("id".to_owned(), Value::Int(2))]);

    let anonymous_posts = cool
        .post()
        .find_many()
        .order_by(cratestack_schema::post::id().asc())
        .run(&anonymous)
        .await
        .expect("anonymous read should succeed");
    assert_eq!(anonymous_posts.len(), 1);
    assert_eq!(anonymous_posts[0].id, 1);

    let owner_posts = cool
        .post()
        .find_many()
        .order_by(cratestack_schema::post::id().asc())
        .run(&owner)
        .await
        .expect("owner read should succeed");
    assert_eq!(
        owner_posts.iter().map(|post| post.id).collect::<Vec<_>>(),
        vec![1, 2]
    );

    let typed_relation_order_posts = cool
        .post()
        .find_many()
        .order_by(
            cratestack_schema::post::author()
                .profile()
                .nickname()
                .desc(),
        )
        .run(&owner)
        .await
        .expect("typed relation order should succeed");
    assert_eq!(
        typed_relation_order_posts
            .iter()
            .map(|post| post.id)
            .collect::<Vec<_>>(),
        vec![2, 1]
    );

    let typed_relation_filtered_posts = cool
        .post()
        .find_many()
        .where_expr(
            cratestack_schema::post::author()
                .profile()
                .nickname()
                .eq("Zulu"),
        )
        .order_by(cratestack_schema::post::id().asc())
        .run(&owner)
        .await
        .expect("typed relation filter should succeed");
    assert_eq!(
        typed_relation_filtered_posts
            .iter()
            .map(|post| post.id)
            .collect::<Vec<_>>(),
        vec![1, 2]
    );

    let typed_quantified_users = cool
        .user()
        .find_many()
        .where_expr(
            cratestack_schema::user::sessions()
                .some()
                .label()
                .contains("Revoked"),
        )
        .order_by(cratestack_schema::user::id().asc())
        .run(&owner)
        .await
        .expect("typed quantified relation filter should succeed");
    assert_eq!(typed_quantified_users.len(), 1);
    assert_eq!(typed_quantified_users[0].email, "other@example.com");

    let typed_every_users = cool
        .user()
        .find_many()
        .where_expr(
            cratestack_schema::user::sessions()
                .every()
                .revokedAt()
                .is_null(),
        )
        .order_by(cratestack_schema::user::id().asc())
        .run(&owner)
        .await
        .expect("typed every relation filter should succeed");
    assert_eq!(typed_every_users.len(), 1);
    assert_eq!(typed_every_users[0].email, "owner@example.com");

    let typed_none_users = cool
        .user()
        .find_many()
        .where_expr(
            cratestack_schema::user::sessions()
                .none()
                .revokedAt()
                .is_null(),
        )
        .order_by(cratestack_schema::user::id().asc())
        .run(&owner)
        .await
        .expect("typed none relation filter should succeed");
    assert_eq!(typed_none_users.len(), 1);
    assert_eq!(typed_none_users[0].email, "other@example.com");

    let composed_quantified_users = cool
        .user()
        .find_many()
        .where_expr(
            cratestack_schema::user::sessions()
                .some()
                .label()
                .contains("Primary")
                .and(
                    cratestack_schema::user::sessions()
                        .every()
                        .revokedAt()
                        .is_null(),
                )
                .or(cratestack_schema::user::email().contains("other")),
        )
        .order_by(cratestack_schema::user::id().asc())
        .run(&owner)
        .await
        .expect("composed quantified filter should succeed");
    assert_eq!(
        composed_quantified_users
            .iter()
            .map(|user| user.email.as_str())
            .collect::<Vec<_>>(),
        vec!["owner@example.com", "other@example.com"]
    );

    let negated_quantified_users = cool
        .user()
        .find_many()
        .where_expr(
            cratestack_schema::user::sessions()
                .some()
                .label()
                .contains("Primary")
                .and(
                    cratestack_schema::user::sessions()
                        .every()
                        .revokedAt()
                        .is_null(),
                )
                .not(),
        )
        .order_by(cratestack_schema::user::id().asc())
        .run(&owner)
        .await
        .expect("negated quantified filter should succeed");
    assert_eq!(negated_quantified_users.len(), 1);
    assert_eq!(negated_quantified_users[0].email, "other@example.com");

    let composed_posts = cool
        .post()
        .find_many()
        .where_expr(
            cratestack_schema::post::author()
                .profile()
                .nickname()
                .eq("Zulu")
                .and(cratestack_schema::post::published().is_true())
                .or(cratestack_schema::post::title().contains("Draft")),
        )
        .order_by(cratestack_schema::post::id().asc())
        .run(&owner)
        .await
        .expect("composed typed filter should succeed");
    assert_eq!(
        composed_posts
            .iter()
            .map(|post| post.id)
            .collect::<Vec<_>>(),
        vec![1, 2]
    );

    let negated_posts = cool
        .post()
        .find_many()
        .where_expr(
            cratestack_schema::post::author()
                .profile()
                .nickname()
                .eq("Zulu")
                .and(cratestack_schema::post::published().is_true())
                .not(),
        )
        .order_by(cratestack_schema::post::id().asc())
        .run(&owner)
        .await
        .expect("negated typed filter should succeed");
    assert_eq!(
        negated_posts.iter().map(|post| post.id).collect::<Vec<_>>(),
        vec![2]
    );

    let hidden_post = cool
        .post()
        .find_unique(2_i64)
        .run(&anonymous)
        .await
        .expect("anonymous scoped find_unique should succeed");
    assert!(hidden_post.is_none());

    let created = cool
        .post()
        .create(cratestack_schema::CreatePostInput {
            id: 4,
            title: "Created".to_owned(),
            subtitle: Some("fresh".to_owned()),
            published: false,
            authorId: 1,
        })
        .run(&owner)
        .await
        .expect("authenticated create should succeed");
    assert_eq!(created.authorId, 1);

    let create_error = cool
        .post()
        .create(cratestack_schema::CreatePostInput {
            id: 5,
            title: "Blocked".to_owned(),
            subtitle: None,
            published: false,
            authorId: 2,
        })
        .run(&anonymous)
        .await
        .expect_err("anonymous create should fail");
    assert!(matches!(create_error, CoolError::Forbidden(_)));

    let updated = cool
        .post()
        .update(2_i64)
        .set(cratestack_schema::UpdatePostInput {
            title: Some("Updated Draft".to_owned()),
            subtitle: None,
            published: Some(true),
            authorId: None,
        })
        .run(&owner)
        .await
        .expect("owner update should succeed");
    assert_eq!(updated.title, "Updated Draft");

    let update_error = cool
        .post()
        .update(2_i64)
        .set(cratestack_schema::UpdatePostInput {
            title: Some("Nope".to_owned()),
            subtitle: None,
            published: None,
            authorId: None,
        })
        .run(&other)
        .await
        .expect_err("non-owner update should fail");
    assert!(matches!(update_error, CoolError::Forbidden(_)));

    let delete_error = cool
        .post()
        .delete(2_i64)
        .run(&other)
        .await
        .expect_err("non-owner delete should fail");
    assert!(matches!(delete_error, CoolError::Forbidden(_)));

    let deleted = cool
        .post()
        .delete(2_i64)
        .run(&owner)
        .await
        .expect("owner delete should succeed");
    assert_eq!(deleted.id, 2);

    let codec = CborCodec;
    let router = cratestack_schema::axum::model_router(
        cratestack_schema::Cratestack::builder(pool.clone()).build(),
        codec.clone(),
        PolicyDbAuthProvider,
    );

    let anonymous_response = router
        .clone()
        .oneshot(
            Request::get("/posts")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("anonymous list request should succeed");
    assert_eq!(anonymous_response.status(), StatusCode::OK);
    let anonymous_body = to_bytes(anonymous_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let anonymous_posts: Vec<cratestack_schema::Post> = codec
        .decode(&anonymous_body)
        .expect("anonymous response should decode");
    assert_eq!(anonymous_posts.len(), 1);
    assert_eq!(anonymous_posts[0].id, 1);

    let filtered_response = router
        .clone()
        .oneshot(
            Request::get("/posts?published=false&authorId=1&sort=-id&limit=1")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("filtered list request should succeed");
    assert_eq!(filtered_response.status(), StatusCode::OK);
    let filtered_body = to_bytes(filtered_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let filtered_posts: Vec<cratestack_schema::Post> = codec
        .decode(&filtered_body)
        .expect("filtered response should decode");
    assert_eq!(filtered_posts.len(), 1);
    assert_eq!(filtered_posts[0].id, 2);

    let advanced_filtered_response = router
        .clone()
        .oneshot(
            Request::get(
                "/posts?title__startsWith=Dr&subtitle__isNull=true&authorId__in=1,2&sort=-id",
            )
            .header("x-auth-id", "1")
            .body(Body::empty())
            .expect("request should build"),
        )
        .await
        .expect("advanced filtered list request should succeed");
    assert_eq!(advanced_filtered_response.status(), StatusCode::OK);
    let advanced_filtered_body = to_bytes(advanced_filtered_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let advanced_filtered_posts: Vec<cratestack_schema::Post> = codec
        .decode(&advanced_filtered_body)
        .expect("advanced filtered response should decode");
    assert_eq!(advanced_filtered_posts.len(), 1);
    assert_eq!(advanced_filtered_posts[0].id, 2);

    let relation_filtered_response = router
        .clone()
        .oneshot(
            Request::get("/posts?author.email=owner@example.com")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("relation filtered list request should succeed");
    assert_eq!(relation_filtered_response.status(), StatusCode::OK);
    let relation_filtered_body = to_bytes(relation_filtered_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let relation_filtered_posts: Vec<cratestack_schema::Post> = codec
        .decode(&relation_filtered_body)
        .expect("relation filtered response should decode");
    assert_eq!(relation_filtered_posts.len(), 2);
    assert_eq!(relation_filtered_posts[0].authorId, 1);

    let or_group_response = router
        .clone()
        .oneshot(
            Request::get("/posts?or=title__startsWith=Pub|author.email=owner@example.com&sort=id")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("or group list request should succeed");
    assert_eq!(or_group_response.status(), StatusCode::OK);
    let or_group_body = to_bytes(or_group_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let or_group_posts: Vec<cratestack_schema::Post> = codec
        .decode(&or_group_body)
        .expect("or group response should decode");
    assert_eq!(
        or_group_posts
            .iter()
            .map(|post| post.id)
            .collect::<Vec<_>>(),
        vec![1, 2]
    );

    let nested_where_response = router
        .clone()
        .oneshot(
            Request::get(
                "/sessions?where=(label__startsWith=Primary|label__startsWith=Revoked),createdAt__gt=2026-01-01T12:00:00Z",
            )
            .header("x-auth-id", "1")
            .body(Body::empty())
            .expect("request should build"),
        )
        .await
        .expect("nested where request should succeed");
    assert_eq!(nested_where_response.status(), StatusCode::OK);
    let nested_where_body = to_bytes(nested_where_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let nested_where_sessions: Vec<cratestack_schema::Session> = codec
        .decode(&nested_where_body)
        .expect("nested where response should decode");
    assert_eq!(nested_where_sessions.len(), 1);
    assert_eq!(nested_where_sessions[0].label, "Revoked Session");

    let negated_where_response = router
        .clone()
        .oneshot(
            Request::get("/posts?where=not(author.profile.nickname=Zulu,published=true)")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("negated where request should succeed");
    assert_eq!(negated_where_response.status(), StatusCode::OK);
    let negated_where_body = to_bytes(negated_where_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let negated_where_posts: Vec<cratestack_schema::Post> = codec
        .decode(&negated_where_body)
        .expect("negated where response should decode");
    assert_eq!(negated_where_posts.len(), 1);
    assert_eq!(negated_where_posts[0].id, 2);

    let user_sessions_response = router
        .clone()
        .oneshot(
            Request::get("/users?sessions.some.label__contains=Revoked")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("to-many relation filter request should succeed");
    assert_eq!(user_sessions_response.status(), StatusCode::OK);
    let user_sessions_body = to_bytes(user_sessions_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let users: Vec<cratestack_schema::User> = codec
        .decode(&user_sessions_body)
        .expect("to-many relation response should decode");
    assert_eq!(users.len(), 1);
    assert_eq!(users[0].email, "other@example.com");

    let every_sessions_response = router
        .clone()
        .oneshot(
            Request::get("/users?sessions.every.revokedAt__isNull=true")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("to-many every relation filter request should succeed");
    assert_eq!(every_sessions_response.status(), StatusCode::OK);
    let every_sessions_body = to_bytes(every_sessions_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let every_users: Vec<cratestack_schema::User> = codec
        .decode(&every_sessions_body)
        .expect("to-many every relation response should decode");
    assert_eq!(every_users.len(), 1);
    assert_eq!(every_users[0].email, "owner@example.com");

    let none_sessions_response = router
        .clone()
        .oneshot(
            Request::get("/users?sessions.none.revokedAt__isNull=true")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("to-many none relation filter request should succeed");
    assert_eq!(none_sessions_response.status(), StatusCode::OK);
    let none_sessions_body = to_bytes(none_sessions_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let none_users: Vec<cratestack_schema::User> = codec
        .decode(&none_sessions_body)
        .expect("to-many none relation response should decode");
    assert_eq!(none_users.len(), 1);
    assert_eq!(none_users[0].email, "other@example.com");

    let projected_response = router
        .clone()
        .oneshot(
            Request::get("/posts?fields=id,title&sort=id")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("projected list request should succeed");
    assert_eq!(projected_response.status(), StatusCode::OK);
    let projected_body = to_bytes(projected_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let projected_posts: Vec<cratestack::serde_json::Value> = codec
        .decode(&projected_body)
        .expect("projected response should decode");
    assert_eq!(projected_posts.len(), 2);
    let first_projected = projected_posts[0]
        .as_object()
        .expect("projected post should be an object");
    assert_eq!(first_projected.len(), 2);
    assert_eq!(
        first_projected.get("id"),
        Some(&cratestack::serde_json::Value::from(1))
    );
    assert_eq!(
        first_projected.get("title"),
        Some(&cratestack::serde_json::Value::from("Published Post"))
    );

    let included_list_response = router
        .clone()
        .oneshot(
            Request::get("/posts?include=author&sort=id")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("included list request should succeed");
    assert_eq!(included_list_response.status(), StatusCode::OK);
    let included_list_body = to_bytes(included_list_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let included_posts: Vec<cratestack::serde_json::Value> = codec
        .decode(&included_list_body)
        .expect("included response should decode");
    let included_author = included_posts[0]
        .as_object()
        .and_then(|post| post.get("author"))
        .and_then(|value| value.as_object())
        .expect("included author should be present");
    assert_eq!(
        included_author.get("email"),
        Some(&cratestack::serde_json::Value::from("owner@example.com"))
    );

    let projected_include_list_response = router
        .clone()
        .oneshot(
            Request::get("/posts?include=author&includeFields%5Bauthor%5D=email&sort=id")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("projected include list request should succeed");
    assert_eq!(projected_include_list_response.status(), StatusCode::OK);
    let projected_include_list_body =
        to_bytes(projected_include_list_response.into_body(), usize::MAX)
            .await
            .expect("response body should decode");
    let projected_include_posts: Vec<cratestack::serde_json::Value> = codec
        .decode(&projected_include_list_body)
        .expect("projected include response should decode");
    let projected_include_author = projected_include_posts[0]
        .as_object()
        .and_then(|post| post.get("author"))
        .and_then(|value| value.as_object())
        .expect("projected included author should be present");
    assert_eq!(projected_include_author.len(), 1);
    assert_eq!(
        projected_include_author.get("email"),
        Some(&cratestack::serde_json::Value::from("owner@example.com"))
    );

    let nested_include_list_response = router
        .clone()
        .oneshot(
            Request::get(
                "/posts?include=author.profile&includeFields%5Bauthor%5D=email&includeFields%5Bauthor.profile%5D=nickname&sort=id",
            )
            .header("x-auth-id", "1")
            .body(Body::empty())
            .expect("request should build"),
        )
        .await
        .expect("nested include list request should succeed");
    assert_eq!(nested_include_list_response.status(), StatusCode::OK);
    let nested_include_list_body = to_bytes(nested_include_list_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let nested_include_posts: Vec<cratestack::serde_json::Value> = codec
        .decode(&nested_include_list_body)
        .expect("nested include response should decode");
    let nested_include_author = nested_include_posts[0]
        .as_object()
        .and_then(|post| post.get("author"))
        .and_then(|value| value.as_object())
        .expect("nested included author should be present");
    assert_eq!(
        nested_include_author.get("email"),
        Some(&cratestack::serde_json::Value::from("owner@example.com"))
    );
    let nested_include_profile = nested_include_author
        .get("profile")
        .and_then(|value| value.as_object())
        .expect("nested included profile should be present");
    assert_eq!(nested_include_profile.len(), 1);
    assert_eq!(
        nested_include_profile.get("nickname"),
        Some(&cratestack::serde_json::Value::from("Zulu"))
    );

    let projected_to_many_include_response = router
        .clone()
        .oneshot(
            Request::get("/users?include=sessions&includeFields%5Bsessions%5D=id,label&sort=id")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("projected to-many include request should succeed");
    assert_eq!(projected_to_many_include_response.status(), StatusCode::OK);
    let projected_to_many_include_body =
        to_bytes(projected_to_many_include_response.into_body(), usize::MAX)
            .await
            .expect("response body should decode");
    let projected_users: Vec<cratestack::serde_json::Value> = codec
        .decode(&projected_to_many_include_body)
        .expect("projected to-many include response should decode");
    let projected_sessions = projected_users[0]
        .as_object()
        .and_then(|user| user.get("sessions"))
        .and_then(|value| value.as_array())
        .expect("projected included sessions should be present");
    let projected_session = projected_sessions[0]
        .as_object()
        .expect("projected included session should be an object");
    assert_eq!(projected_session.len(), 2);
    assert!(projected_session.get("id").is_some());
    assert!(projected_session.get("label").is_some());

    let nested_relation_response = router
        .clone()
        .oneshot(
            Request::get("/sessions?user.sessions.some.label__startsWith=Primary")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("nested relation filter request should succeed");
    assert_eq!(nested_relation_response.status(), StatusCode::OK);
    let nested_relation_body = to_bytes(nested_relation_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let nested_relation_sessions: Vec<cratestack_schema::Session> = codec
        .decode(&nested_relation_body)
        .expect("nested relation response should decode");
    assert_eq!(nested_relation_sessions.len(), 1);
    assert_eq!(nested_relation_sessions[0].id, "cprimarysession1");

    let session_list_response = router
        .clone()
        .oneshot(
            Request::get(
                "/sessions?id=cprimarysession1&externalId=11111111-1111-1111-1111-111111111111&createdAt=2026-01-01T00:00:00Z&revokedAt__isNull=true",
            )
            .header("x-auth-id", "1")
            .body(Body::empty())
            .expect("request should build"),
        )
        .await
        .expect("session list request should succeed");
    assert_eq!(session_list_response.status(), StatusCode::OK);
    let session_list_body = to_bytes(session_list_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let sessions: Vec<cratestack_schema::Session> = codec
        .decode(&session_list_body)
        .expect("session response should decode");
    assert_eq!(sessions.len(), 1);
    assert_eq!(sessions[0].label, "Primary Session");

    let session_advanced_response = router
        .clone()
        .oneshot(
            Request::get(
                "/sessions?label__contains=Session&id__in=cprimarysession1,crevokedsession2&sort=-createdAt",
            )
            .header("x-auth-id", "1")
            .body(Body::empty())
            .expect("request should build"),
        )
        .await
        .expect("advanced session list request should succeed");
    assert_eq!(session_advanced_response.status(), StatusCode::OK);
    let session_advanced_body = to_bytes(session_advanced_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let ordered_sessions: Vec<cratestack_schema::Session> = codec
        .decode(&session_advanced_body)
        .expect("advanced session response should decode");
    assert_eq!(ordered_sessions.len(), 2);
    assert_eq!(ordered_sessions[0].label, "Revoked Session");

    cratestack::sqlx::query(
        "INSERT INTO posts (id, title, subtitle, published, author_id) VALUES (4, 'Orphan Published', NULL, TRUE, 999)",
    )
    .execute(&pool)
    .await
    .expect("orphan post should seed");

    let relation_order_response = router
        .clone()
        .oneshot(
            Request::get("/posts?sort=-author.email")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("relation order list request should succeed");
    assert_eq!(relation_order_response.status(), StatusCode::OK);
    let relation_order_body = to_bytes(relation_order_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let ordered_posts: Vec<cratestack_schema::Post> = codec
        .decode(&relation_order_body)
        .expect("relation ordered response should decode");
    assert_eq!(ordered_posts.len(), 3);
    assert_eq!(ordered_posts[0].id, 2);
    assert_eq!(ordered_posts[1].id, 1);
    assert_eq!(ordered_posts[2].id, 4);

    let nested_relation_order_response = router
        .clone()
        .oneshot(
            Request::get("/posts?sort=-author.profile.nickname")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("nested relation order list request should succeed");
    assert_eq!(nested_relation_order_response.status(), StatusCode::OK);
    let nested_relation_order_body =
        to_bytes(nested_relation_order_response.into_body(), usize::MAX)
            .await
            .expect("response body should decode");
    let nested_ordered_posts: Vec<cratestack_schema::Post> = codec
        .decode(&nested_relation_order_body)
        .expect("nested relation ordered response should decode");
    assert_eq!(nested_ordered_posts.len(), 3);
    assert_eq!(nested_ordered_posts[0].id, 2);
    assert_eq!(nested_ordered_posts[1].id, 1);
    assert_eq!(nested_ordered_posts[2].id, 4);

    let session_detail_response = router
        .clone()
        .oneshot(
            Request::get("/sessions/cprimarysession1")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("session detail request should succeed");
    assert_eq!(session_detail_response.status(), StatusCode::OK);
    let session_detail_body = to_bytes(session_detail_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let session: cratestack_schema::Session = codec
        .decode(&session_detail_body)
        .expect("session detail should decode");
    assert_eq!(session.label, "Primary Session");

    let owner_response = router
        .clone()
        .oneshot(
            Request::get("/posts/1?fields=id,title&include=author")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("owner detail request should succeed");
    assert_eq!(owner_response.status(), StatusCode::OK);
    let owner_body = to_bytes(owner_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let owner_post: cratestack::serde_json::Value = codec
        .decode(&owner_body)
        .expect("owner response should decode");
    let owner_post = owner_post
        .as_object()
        .expect("owner response should be an object");
    assert_eq!(owner_post.len(), 3);
    assert_eq!(
        owner_post.get("id"),
        Some(&cratestack::serde_json::Value::from(1))
    );
    assert_eq!(
        owner_post.get("title"),
        Some(&cratestack::serde_json::Value::from("Published Post"))
    );
    let owner_author = owner_post
        .get("author")
        .and_then(|value| value.as_object())
        .expect("owner response should include author");
    assert_eq!(
        owner_author.get("email"),
        Some(&cratestack::serde_json::Value::from("owner@example.com"))
    );

    let projected_owner_response = router
        .clone()
        .oneshot(
            Request::get("/posts/1?include=author&includeFields%5Bauthor%5D=email")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("projected owner detail request should succeed");
    assert_eq!(projected_owner_response.status(), StatusCode::OK);
    let projected_owner_body = to_bytes(projected_owner_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let projected_owner_post: cratestack::serde_json::Value = codec
        .decode(&projected_owner_body)
        .expect("projected owner response should decode");
    let projected_owner_author = projected_owner_post
        .as_object()
        .and_then(|post| post.get("author"))
        .and_then(|value| value.as_object())
        .expect("projected owner response should include author");
    assert_eq!(projected_owner_author.len(), 1);
    assert_eq!(
        projected_owner_author.get("email"),
        Some(&cratestack::serde_json::Value::from("owner@example.com"))
    );

    let nested_owner_response = router
        .clone()
        .oneshot(
            Request::get(
                "/posts/1?include=author.profile&includeFields%5Bauthor%5D=email&includeFields%5Bauthor.profile%5D=nickname",
            )
            .header("x-auth-id", "1")
            .body(Body::empty())
            .expect("request should build"),
        )
        .await
        .expect("nested owner detail request should succeed");
    assert_eq!(nested_owner_response.status(), StatusCode::OK);
    let nested_owner_body = to_bytes(nested_owner_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let nested_owner_post: cratestack::serde_json::Value = codec
        .decode(&nested_owner_body)
        .expect("nested owner response should decode");
    let nested_owner_profile = nested_owner_post
        .as_object()
        .and_then(|post| post.get("author"))
        .and_then(|value| value.as_object())
        .and_then(|author| author.get("profile"))
        .and_then(|value| value.as_object())
        .expect("nested owner response should include profile");
    assert_eq!(nested_owner_profile.len(), 1);
    assert_eq!(
        nested_owner_profile.get("nickname"),
        Some(&cratestack::serde_json::Value::from("Zulu"))
    );

    let missing_include_for_include_fields_response = router
        .clone()
        .oneshot(
            Request::get("/posts?includeFields%5Bauthor%5D=email")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("missing include validation request should succeed");
    assert_eq!(
        missing_include_for_include_fields_response.status(),
        StatusCode::BAD_REQUEST
    );

    let hidden_response = router
        .clone()
        .oneshot(
            Request::get("/posts/3")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("hidden detail request should succeed");
    assert_eq!(hidden_response.status(), StatusCode::NOT_FOUND);

    let create_body = codec
        .encode(&cratestack_schema::CreatePostInput {
            id: 4,
            title: "Route Created".to_owned(),
            subtitle: Some("from route".to_owned()),
            published: false,
            authorId: 1,
        })
        .expect("create request should encode");
    let create_response = router
        .clone()
        .oneshot(
            Request::post("/posts")
                .header("content-type", CborCodec::CONTENT_TYPE)
                .header("x-auth-id", "1")
                .body(Body::from(create_body))
                .expect("request should build"),
        )
        .await
        .expect("create route should succeed");
    assert_eq!(create_response.status(), StatusCode::CREATED);
    let create_response_body = to_bytes(create_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let created_post: cratestack_schema::Post = codec
        .decode(&create_response_body)
        .expect("created post should decode");
    assert_eq!(created_post.authorId, 1);

    let blocked_create_body = codec
        .encode(&cratestack_schema::CreatePostInput {
            id: 5,
            title: "Blocked Route Create".to_owned(),
            subtitle: None,
            published: false,
            authorId: 2,
        })
        .expect("blocked create request should encode");
    let blocked_create_response = router
        .clone()
        .oneshot(
            Request::post("/posts")
                .header("content-type", CborCodec::CONTENT_TYPE)
                .body(Body::from(blocked_create_body))
                .expect("request should build"),
        )
        .await
        .expect("blocked create route should succeed");
    assert_eq!(blocked_create_response.status(), StatusCode::FORBIDDEN);

    let update_body = codec
        .encode(&cratestack_schema::UpdatePostInput {
            title: Some("Route Updated".to_owned()),
            subtitle: None,
            published: Some(true),
            authorId: None,
        })
        .expect("update request should encode");
    let update_response = router
        .clone()
        .oneshot(
            Request::patch("/posts/3")
                .header("content-type", CborCodec::CONTENT_TYPE)
                .header("x-auth-id", "2")
                .body(Body::from(update_body))
                .expect("request should build"),
        )
        .await
        .expect("update route should succeed");
    assert_eq!(update_response.status(), StatusCode::OK);
    let update_response_body = to_bytes(update_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let updated_post: cratestack_schema::Post = codec
        .decode(&update_response_body)
        .expect("updated post should decode");
    assert_eq!(updated_post.title, "Route Updated");

    let blocked_update_body = codec
        .encode(&cratestack_schema::UpdatePostInput {
            title: Some("Blocked Route Update".to_owned()),
            subtitle: None,
            published: None,
            authorId: None,
        })
        .expect("blocked update request should encode");
    let blocked_update_response = router
        .clone()
        .oneshot(
            Request::patch("/posts/3")
                .header("content-type", CborCodec::CONTENT_TYPE)
                .header("x-auth-id", "1")
                .body(Body::from(blocked_update_body))
                .expect("request should build"),
        )
        .await
        .expect("blocked update route should succeed");
    assert_eq!(blocked_update_response.status(), StatusCode::FORBIDDEN);

    let blocked_delete_response = router
        .clone()
        .oneshot(
            Request::delete("/posts/3")
                .header("x-auth-id", "1")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("blocked delete route should succeed");
    assert_eq!(blocked_delete_response.status(), StatusCode::FORBIDDEN);

    let delete_response = router
        .oneshot(
            Request::delete("/posts/3")
                .header("x-auth-id", "2")
                .body(Body::empty())
                .expect("request should build"),
        )
        .await
        .expect("delete route should succeed");
    assert_eq!(delete_response.status(), StatusCode::OK);
    let delete_response_body = to_bytes(delete_response.into_body(), usize::MAX)
        .await
        .expect("response body should decode");
    let deleted_post: cratestack_schema::Post = codec
        .decode(&delete_response_body)
        .expect("deleted post should decode");
    assert_eq!(deleted_post.id, 3);
}

#[tokio::test]
async fn db_backed_model_events_use_outbox_and_isolate_subscriber_failures() {
    let database_url = match std::env::var("CRATESTACK_TEST_DATABASE_URL") {
        Ok(url) => url,
        Err(_) => return,
    };

    let pool = match PgPoolOptions::new()
        .max_connections(1)
        .connect(&database_url)
        .await
    {
        Ok(pool) => pool,
        Err(_) => return,
    };

    cratestack::sqlx::query(
        "CREATE TABLE IF NOT EXISTS users (id BIGINT PRIMARY KEY, email TEXT NOT NULL, role TEXT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("users table should exist");
    cratestack::sqlx::query(
        "CREATE TABLE IF NOT EXISTS profiles (id BIGINT PRIMARY KEY, nickname TEXT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("profiles table should exist");
    cratestack::sqlx::query(
        "ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_id BIGINT NOT NULL DEFAULT 1",
    )
    .execute(&pool)
    .await
    .expect("users profile_id column should exist");
    cratestack::sqlx::query(
        "CREATE TABLE IF NOT EXISTS posts (id BIGINT PRIMARY KEY, title TEXT NOT NULL, subtitle TEXT, published BOOLEAN NOT NULL, author_id BIGINT NOT NULL)",
    )
    .execute(&pool)
    .await
    .expect("posts table should exist");
    cratestack::sqlx::query("TRUNCATE TABLE posts, users, profiles")
        .execute(&pool)
        .await
        .expect("tables should be truncated");
    cratestack::sqlx::query("INSERT INTO profiles (id, nickname) VALUES (1, 'Zulu')")
        .execute(&pool)
        .await
        .expect("profiles should seed");
    cratestack::sqlx::query(
        "INSERT INTO users (id, email, role, profile_id) VALUES (1, 'owner@example.com', 'member', 1)",
    )
    .execute(&pool)
    .await
    .expect("users should seed");
    cratestack::sqlx::query(
        "INSERT INTO posts (id, title, subtitle, published, author_id) VALUES (2, 'Draft', NULL, FALSE, 1)",
    )
    .execute(&pool)
    .await
    .expect("posts should seed");

    let cool = cratestack_schema::Cratestack::builder(pool.clone()).build();
    let seen = Arc::new(Mutex::new(Vec::new()));
    let fail_once = Arc::new(AtomicBool::new(true));

    let failing = Arc::clone(&fail_once);
    cool.events().on_post_created(move |_event| {
        let failing = Arc::clone(&failing);
        async move {
            if failing.swap(false, Ordering::SeqCst) {
                return Err(cratestack::CoolError::Forbidden(
                    "subscriber failed once".to_owned(),
                ));
            }
            Ok(())
        }
    });

    let created_seen = Arc::clone(&seen);
    cool.events().on_post_created(move |event| {
        let created_seen = Arc::clone(&created_seen);
        async move {
            created_seen
                .lock()
                .expect("event capture lock should not be poisoned")
                .push(format!("created:{}:{}", event.data.id, event.data.title));
            Ok(())
        }
    });

    let updated_seen = Arc::clone(&seen);
    cool.events().on_post_updated(move |event| {
        let updated_seen = Arc::clone(&updated_seen);
        async move {
            updated_seen
                .lock()
                .expect("event capture lock should not be poisoned")
                .push(format!("updated:{}:{}", event.data.id, event.data.title));
            Ok(())
        }
    });

    let deleted_seen = Arc::clone(&seen);
    cool.events().on_post_deleted(move |event| {
        let deleted_seen = Arc::clone(&deleted_seen);
        async move {
            deleted_seen
                .lock()
                .expect("event capture lock should not be poisoned")
                .push(format!("deleted:{}:{}", event.data.id, event.data.title));
            Ok(())
        }
    });

    let owner = CoolContext::authenticated([("id".to_owned(), Value::Int(1))]);

    let created = cool
        .post()
        .bind(owner.clone())
        .create(cratestack_schema::CreatePostInput {
            id: 4,
            title: "Created Draft".to_owned(),
            subtitle: None,
            published: false,
            authorId: 1,
        })
        .run()
        .await
        .expect("create should still succeed when a subscriber fails after commit");
    assert_eq!(created.title, "Created Draft");

    let outbox_after_create: (i64,) = cratestack::sqlx::query_as(
        "SELECT COUNT(*) FROM cratestack_event_outbox WHERE delivered_at IS NULL",
    )
    .fetch_one(&pool)
    .await
    .expect("outbox count should query");
    assert_eq!(outbox_after_create.0, 1);

    let drained = cool
        .events()
        .drain()
        .await
        .expect("manual drain should succeed after subscriber recovers");
    assert_eq!(drained, 1);

    let updated = cool
        .post()
        .bind(owner.clone())
        .update(2)
        .set(cratestack_schema::UpdatePostInput {
            title: Some("Updated Draft".to_owned()),
            ..Default::default()
        })
        .run()
        .await
        .expect("owner update should succeed");
    assert_eq!(updated.title, "Updated Draft");

    let deleted = cool
        .post()
        .bind(owner)
        .delete(2)
        .run()
        .await
        .expect("owner delete should succeed");
    assert_eq!(deleted.id, 2);

    assert_eq!(
        seen.lock()
            .expect("event capture lock should not be poisoned")
            .as_slice(),
        [
            "created:1:Created Draft",
            "updated:2:Updated Draft",
            "deleted:2:Updated Draft",
        ]
    );

    let remaining_outbox: (i64,) = cratestack::sqlx::query_as(
        "SELECT COUNT(*) FROM cratestack_event_outbox WHERE delivered_at IS NULL",
    )
    .fetch_one(&pool)
    .await
    .expect("remaining outbox count should query");
    assert_eq!(remaining_outbox.0, 0);
}
