//! Env var names and default windows for signed-request verification.

pub const SIGNATURE_TRUSTED_KEYS_ENV: &str = "CRATESTACK_AUTH_SIGNATURE_TRUSTED_KEYS";
pub const SIGNATURE_TRUSTED_ISSUERS_ENV: &str = "CRATESTACK_AUTH_SIGNATURE_TRUSTED_ISSUERS";
pub const SIGNATURE_MAX_SKEW_SECONDS_ENV: &str = "CRATESTACK_AUTH_SIGNATURE_MAX_SKEW_SECONDS";
pub const SIGNATURE_REPLAY_WINDOW_SECONDS_ENV: &str =
    "CRATESTACK_AUTH_SIGNATURE_REPLAY_WINDOW_SECONDS";
pub const DEFAULT_SIGNATURE_MAX_SKEW_SECONDS: i64 = 300;
pub const DEFAULT_SIGNATURE_REPLAY_WINDOW_SECONDS: i64 = 300;
pub(super) const REDIS_NONCE_KEY_PREFIX: &str = "cratestack:signature-nonce";
