// The one hand-written line every generated function/hook needs: a
// `CratestackRuntime` instance. Everything downstream of this — types,
// fetch calls, SWR hooks, cache keys, invalidation — is generated by
// `--preset swr` (see `../../client/`); this file is not "data-fetching
// code", it's wiring a base URL, matching the ticket's zero-hand-written-
// data-fetching-code bar.
import { CratestackRuntime } from "react-vite-swr-client";

// Stand-in for real auth (a session cookie, a bearer token, an OAuth
// flow — anything a production app would use). The schema's
// `@@allow(..., auth() != null)` rules only need SOME authenticated
// caller, and the server's `HeaderAuthProvider` (`../../src/lib.rs`)
// reads this header as `auth().id` — so a fixed header is enough to
// demonstrate the generated surface without building a login screen,
// which is out of scope for this example.
export const runtime = new CratestackRuntime("http://127.0.0.1:3210", {
  basePath: "/api",
  headers: { "x-auth-id": "1" },
});
