// The one hand-written line every generated function/hook needs: a
// `CratestackRuntime` instance. Everything downstream of this — types,
// fetch calls, SWR hooks, cache keys, invalidation — is generated by
// `--swr` (see `../../client/`); this file is not "data-fetching code",
// it's wiring a base URL, matching the ticket's zero-hand-written-
// data-fetching-code bar.
//
// Imported from the `/swr` subpath, NOT the package root: `--swr` (issue
// #591) nests its own `CratestackRuntime` under `src/swr/runtime.ts`,
// generated from the same template as the default layout's
// `src/runtime.ts` but compiled to a structurally-identical, nominally
// *distinct* class (private fields make TypeScript treat the two as
// incompatible even though every field matches) — every hook this app
// imports (`react-vite-swr-client/swr/models/*.hooks`) expects the `/swr`
// one specifically, so the runtime instance handed to them has to come
// from there too, not the root.
import { CratestackRuntime } from "react-vite-swr-client/swr";

// Stand-in for real auth (a session cookie, a bearer token, an OAuth
// flow — anything a production app would use). The schema's
// `@@allow(..., auth() != null)` rules only need SOME authenticated
// caller, and the server's `HeaderAuthProvider` (`../../src/lib.rs`)
// reads this header as `auth().id` — so a fixed header is enough to
// demonstrate the generated surface without building a login screen,
// which is out of scope for this example.
export const runtime = new CratestackRuntime("http://127.0.0.1:3210", {
  basePath: "/api",
  headers: { "x-auth-id": "1" },
});
