import { defineConfig } from 'vite';

// OPFS SyncAccessHandle is only available inside a Dedicated Worker, and the
// worker file is loaded via `new Worker(url, { type: 'module' })`. Vite
// resolves the worker URL with `?worker&inline=false` style or `new URL(...,
// import.meta.url)` — we use the latter in src/main.ts. No extra config
// needed beyond what's below.
export default defineConfig({
  server: {
    // OPFS doesn't strictly require COOP/COEP, but enabling them here means
    // future demos that opt into SharedArrayBuffer (multithreaded wasm,
    // rayon, etc.) work out of the box.
    headers: {
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'require-corp',
    },
  },
  worker: {
    format: 'es',
  },
  // Treat the wasm pkg directory as a regular source so Vite serves
  // `tauri_web_wasm_example_bg.wasm` with the right MIME type during
  // dev. The pkg/ dir is generated by `wasm-pack` (via `pnpm run wasm:build`).
  optimizeDeps: {
    exclude: ['./pkg/tauri_web_wasm_example.js'],
  },
});
