// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `decode_bytes`, `encode_value`, `to_flutter_error`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `content_type`

/// flutter_rust_bridge entry point: JSON text -> CBOR bytes. See the
/// module doc comment for why the boundary type is `String`, not a
/// native dynamic value.
Uint8List encodeJson({required String json}) =>
    CratestackCborRustLib.instance.api.crateCborEncodeJson(json: json);

/// flutter_rust_bridge entry point: CBOR bytes -> JSON text. Malformed
/// input returns a catchable `Err`, matching the napi/wasm siblings'
/// "never a panic on bad input" contract.
String decodeJson({required List<int> bytes}) =>
    CratestackCborRustLib.instance.api.crateCborDecodeJson(bytes: bytes);
