// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FlutterRuntimeError implements FrbException {
  final int code;
  final int? httpStatus;
  final String message;
  final String? remoteCode;
  final Uint8List? remoteBody;

  const FlutterRuntimeError({
    required this.code,
    this.httpStatus,
    required this.message,
    this.remoteCode,
    this.remoteBody,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      httpStatus.hashCode ^
      message.hashCode ^
      remoteCode.hashCode ^
      remoteBody.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterRuntimeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          httpStatus == other.httpStatus &&
          message == other.message &&
          remoteCode == other.remoteCode &&
          remoteBody == other.remoteBody;
}
