//! Real npm/vitest proof that a schema `Bytes` field behaves as documented
//! in a generated TypeScript client — a `Uint8Array` in both directions,
//! carried on the wire as the integer array the server actually accepts
//! (cratestack#783 follow-up). Mirrors `tests/decimal_round_trip.rs`
//! exactly: generate a real package from `tests/fixtures/
//! bytes_round_trip.cstack`, copy this crate's own
//! `tests/js/bytes_round_trip/*` assets alongside it, `npm install`,
//! `npx vitest run`.
//!
//! Why this is a JS test and not a Rust string assertion: the two things
//! that can go wrong here corrupt data silently rather than failing
//! loudly. An `Int[]` field is byte-identical to a `Bytes` field on the
//! wire, so revival driven by anything other than the schema converts the
//! wrong one; and `JSON.stringify` turns a `Uint8Array` into an
//! index-keyed object that no server-side `Vec<u8>` can decode. Only
//! running the generated code proves either.
//!
//! Skips (printed, not silently swallowed) when `node`/`npm`/`npx` aren't
//! on `PATH` — same rationale as `decimal_round_trip.rs`: no Rust CI job
//! in this repo currently provisions Node.

use std::fs;
use std::process::Command;

use cratestack_client_typescript::{TypeScriptGeneratorConfig, generate_package};

/// Keep in lockstep with `tests/js/bytes_round_trip/bytes.test.ts` — a
/// successful vitest exit alone cannot tell a genuinely green run from an
/// accidentally-empty one (the same guard `decimal_round_trip.rs` uses).
const EXPECTED_PASSING: &str = "16 passed";

#[test]
fn bytes_round_trip_through_the_generated_rest_client() {
    if !node_npm_npx_available() {
        eprintln!(
            "skipping bytes_round_trip_through_the_generated_rest_client: \
             `node`/`npm`/`npx` not on PATH (expected in this repo's Rust-only CI jobs — \
             see tests/bytes_round_trip.rs's module doc)"
        );
        return;
    }

    let schema = cratestack_parser::parse_schema_file("tests/fixtures/bytes_round_trip.cstack")
        .expect("fixture should parse");
    let package = generate_package(&schema, &TypeScriptGeneratorConfig::default())
        .expect("default template should render");

    let dir = tempfile::tempdir().expect("tempdir");
    for file in &package.files {
        let path = dir.path().join(&file.file_name);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).expect("create parent dir");
        }
        fs::write(&path, &file.contents).expect("write generated file");
    }

    // Overwrite the generated package.json with this test's fixture one,
    // which adds the `vitest`/`typescript` devDependencies needed to
    // actually run the test below — same reason `decimal_round_trip.rs`
    // does this for its own fixture.
    let js_fixture_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/js/bytes_round_trip");
    for asset in ["package.json", "vitest.config.ts", "bytes.test.ts"] {
        fs::copy(format!("{js_fixture_dir}/{asset}"), dir.path().join(asset))
            .unwrap_or_else(|error| panic!("copy {asset} into generated package dir: {error}"));
    }

    let install = Command::new("npm")
        .args(["install", "--no-audit", "--no-fund"])
        .current_dir(dir.path())
        .output()
        .expect("run npm install");
    assert!(
        install.status.success(),
        "npm install failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&install.stdout),
        String::from_utf8_lossy(&install.stderr)
    );

    let test_run = Command::new("npx")
        .args(["--yes", "vitest", "run"])
        .current_dir(dir.path())
        .output()
        .expect("run npx vitest");

    let stdout = String::from_utf8_lossy(&test_run.stdout);
    let stderr = String::from_utf8_lossy(&test_run.stderr);
    assert!(
        test_run.status.success(),
        "vitest run against the generated Bytes client failed — this is the real \
         round-trip proof that a `Bytes` field is a `Uint8Array` in both directions \
         and still reaches the wire as an integer array:\nstdout: {stdout}\nstderr: {stderr}"
    );
    assert!(
        stdout.contains(EXPECTED_PASSING) || stderr.contains(EXPECTED_PASSING),
        "expected vitest to report exactly {EXPECTED_PASSING} tests (the round-trip proof \
         suite):\nstdout: {stdout}\nstderr: {stderr}"
    );
}

fn node_npm_npx_available() -> bool {
    ["node", "npm", "npx"].iter().all(|bin| {
        Command::new(bin)
            .arg("--version")
            .output()
            .is_ok_and(|output| output.status.success())
    })
}
