//! Captures real `application/cbor-seq` response bytes from this
//! example's actual generated router — not a hand-rolled fixture — for
//! `packages/cratestack-ts-types`'s TypeScript CBOR-seq boundary-scanner
//! tests (cratestack#277). Per that ticket's own risk mitigation: test
//! the scanner against byte-for-byte fixtures generated by the real
//! encoder, since a hand-constructed one risks encoding assumptions the
//! real wire format doesn't actually make.
//!
//! Both fixtures below are pinned as hex constants here AND checked into
//! `packages/cratestack-ts-types/tests/fixtures/*.hex` (plain hex text,
//! one line, no dependencies needed to consume it from either language).
//! If this test ever needs its `EXPECTED_*_HEX` updated (a real wire
//! format change), update the checked-in `.hex` file to match in the
//! same change — the two are intentionally kept in lockstep rather than
//! one being generated from the other at test time, so a silent drift
//! between the Rust-side pin and the TypeScript-side fixture fails loudly
//! here instead of only showing up as a confusing TS-side test failure.

use cratestack::CratestackCodec;
use cratestack::axum::body::{Body, to_bytes};
use cratestack::axum::http::{Request, StatusCode};
use cratestack_codec_cbor::CborCodec;
use rpc_streaming_example::{build_router, schema};
use tower::ServiceExt;

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// `procedure.ticks(start: 0, count: 3)` over `Accept:
/// application/cbor-seq`, driven through the real generated router
/// (`build_router`) — schema-generated dispatch, `@stream`
/// `ProcedureRegistry::ticks`, and `cratestack-axum`'s incremental
/// encoder, exactly as a real deployment would serve it.
const EXPECTED_SUCCESS_HEX: &str =
    "a265696e646578006576616c756500a265696e646578016576616c756501a265696e646578026576616c756502";

/// `procedure.flakyTicks(start: 100, count: 2)` — same op shape as
/// `ticks`, but `ProcedureRegistry::flaky_ticks` always yields a
/// trailing `Err` after its successful items, so the response ends in
/// the real CBOR-tagged error sentinel (cratestack#281) the production
/// encoder emits for a `@stream` procedure that fails partway through.
const EXPECTED_ERROR_HEX: &str = "a265696e646578006576616c75651864a265696e646578016576616c75651865d9bf04a264636f646568696e7465726e616c676d6573736167656e696e7465726e616c206572726f72";

#[tokio::test]
async fn ticks_success_fixture_bytes_are_stable() {
    let app = build_router();
    let body = CborCodec
        .encode(&schema::procedures::ticks::Args {
            args: schema::TickerArgs { start: 0, count: 3 },
        })
        .unwrap();
    let response = app
        .oneshot(
            Request::post("/rpc/procedure.ticks")
                .header("content-type", CborCodec::CONTENT_TYPE)
                .header("accept", cratestack::CBOR_SEQUENCE_CONTENT_TYPE)
                .header("x-auth-id", "1")
                .body(Body::from(body))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(response.status(), StatusCode::OK);
    let bytes = to_bytes(response.into_body(), usize::MAX).await.unwrap();
    let hex = to_hex(&bytes);
    // Sanity: the real bytes actually decode as three `Tick`s, so a
    // change here reflects a real wire-format change, not this test's
    // own bug.
    let ticks: Vec<schema::Tick> = rpc_streaming_example::decode_cbor_seq(&bytes);
    assert_eq!(ticks.len(), 3);
    assert_eq!(ticks[0].value, 0);
    assert_eq!(ticks[2].value, 2);
    assert_eq!(
        hex, EXPECTED_SUCCESS_HEX,
        "real ticks() cbor-seq bytes changed — update EXPECTED_SUCCESS_HEX above AND \
         packages/cratestack-ts-types/tests/fixtures/ticks-success.hex to match:\ngot: {hex}"
    );
}

#[tokio::test]
async fn flaky_ticks_error_fixture_bytes_are_stable() {
    let app = build_router();
    let body = CborCodec
        .encode(&schema::procedures::flaky_ticks::Args {
            args: schema::TickerArgs {
                start: 100,
                count: 2,
            },
        })
        .unwrap();
    let response = app
        .oneshot(
            Request::post("/rpc/procedure.flakyTicks")
                .header("content-type", CborCodec::CONTENT_TYPE)
                .header("accept", cratestack::CBOR_SEQUENCE_CONTENT_TYPE)
                .header("x-auth-id", "1")
                .body(Body::from(body))
                .unwrap(),
        )
        .await
        .unwrap();
    // Still 200 — the failure is in-band, not a status code (see
    // `cratestack-axum::transport::stream_sequence`'s own doc comment).
    assert_eq!(response.status(), StatusCode::OK);
    let bytes = to_bytes(response.into_body(), usize::MAX).await.unwrap();
    let hex = to_hex(&bytes);
    assert_eq!(
        hex, EXPECTED_ERROR_HEX,
        "real flakyTicks() cbor-seq bytes changed — update EXPECTED_ERROR_HEX above AND \
         packages/cratestack-ts-types/tests/fixtures/flaky-ticks-error.hex to match:\ngot: {hex}"
    );
}
