import type { CratestackRpcCodec } from "@cratestack/ts-types";
// Generated by `wasm-pack build --target web` from `crates/cratestack-cbor-wasm`
// (see `pnpm run wasm:build` / `../../examples/scripts/wasm-build.mjs`) — not
// hand-written, regenerated on every build, excluded from lint/format (see
// root `biome.json`) and from git (see `.gitignore`).
import init, { contentType, decode, encode } from "./wasm-pkg/cratestack_cbor_wasm.js";

// Memoized across calls so concurrent/repeated `createCborCodec()` callers
// share one WASM instantiation instead of re-fetching/re-compiling the
// module. Only a *successful* init is cached — a failed attempt (e.g. the
// `.wasm` asset 404s under a bundler misconfiguration) resets the memo so
// the next call gets a fresh chance rather than replaying the same
// rejection forever.
let initPromise: Promise<void> | null = null;

function ensureInitialized(): Promise<void> {
  if (!initPromise) {
    initPromise = init()
      .then(() => undefined)
      .catch((error: unknown) => {
        initPromise = null;
        throw error;
      });
  }
  return initPromise;
}

/**
 * Performs the one-time WASM module instantiation and resolves to a plain
 * object satisfying {@link CratestackRpcCodec}. Every `encode`/`decode`
 * call on the returned object is synchronous — the async cost is paid
 * once here, never per call, so this composes with the existing
 * (synchronous) `CratestackRpcCodec` contract without changing its shape.
 *
 * Safe to call more than once: later calls resolve once the same
 * in-flight (or already-completed) instantiation settles, they don't
 * re-instantiate the module.
 *
 * @example
 * ```ts
 * const codec = await createCborCodec();
 * const bytes = codec.encode({ hello: "world" });
 * const value = codec.decode(bytes);
 * ```
 */
export async function createCborCodec(): Promise<CratestackRpcCodec> {
  await ensureInitialized();

  return {
    contentType: contentType(),
    encode(value: unknown): BodyInit {
      // Malformed/unrepresentable input throws a real `Error` (see
      // crates/cratestack-cbor-wasm/src/wasm.rs) — never a wasm trap, so
      // it's a normal catchable exception here, not a poisoned module.
      //
      // The cast is TypeScript 5.7+ typed-array generics noise, not a
      // real type mismatch: `Uint8Array` satisfies `BufferSource`
      // (part of the `BodyInit` union) at runtime and per the DOM spec —
      // see the same pattern in
      // crates/cratestack-client-typescript/templates/src/grpc-web-runtime.ts.j2.
      return encode(value) as BodyInit;
    },
    decode(bytes: Uint8Array): unknown {
      return decode(bytes);
    },
  };
}
