// Behavioral proof for the `application/cbor-seq` boundary scanner
// (issue #277) — the ticket's own highest-risk piece: a subtly wrong
// structural walk (mishandling indefinite-length arrays/maps/byte
// strings, or the tag-detection logic) would silently misparse item
// boundaries rather than fail loudly, so this is deliberately thorough.
//
// `tests/fixtures/*.hex` are real `application/cbor-seq` response bytes
// captured from `examples/rpc-streaming`'s actual generated router (see
// `examples/rpc-streaming/tests/stream_ts_fixture_bytes.rs`) — not
// hand-rolled — per the ticket's own risk mitigation ("test against
// byte-for-byte fixtures generated by the actual Rust CBOR encoder").
// The hand-rolled cases below cover CBOR structural shapes (indefinite
// length forms) the real server never happens to emit but the scanner
// must still handle correctly, since it's a general-purpose CBOR
// structural walker, not one specialized to this server's output shape.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { readArgument, skipItem } from "../src/cbor-item.js";
import {
  CborSeqBoundaryScanner,
  MalformedCborSeqError,
  classifyCborSeqItem,
} from "../src/cbor-seq.js";
import { miniCborCodec } from "./helpers/mini-cbor-codec.js";

const fixturesDir = join(dirname(fileURLToPath(import.meta.url)), "fixtures");

function hexToBytes(hex: string): Uint8Array {
  const trimmed = hex.trim();
  const bytes = new Uint8Array(trimmed.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = Number.parseInt(trimmed.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

function loadFixture(name: string): Uint8Array {
  return hexToBytes(readFileSync(join(fixturesDir, name), "utf8"));
}

describe("CborSeqBoundaryScanner — definite-length structure", () => {
  it("splits three single-byte uint items fed in one chunk", () => {
    const scanner = new CborSeqBoundaryScanner();
    const items = scanner.feedChunk(Uint8Array.from([0x00, 0x01, 0x02]));
    expect(items).toHaveLength(3);
    expect(Array.from(items[0]!)).toEqual([0x00]);
    expect(Array.from(items[1]!)).toEqual([0x01]);
    expect(Array.from(items[2]!)).toEqual([0x02]);
    expect(scanner.pendingLength).toBe(0);
  });

  it("finds the boundary of a definite array item", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0x82 = array(2), then uint 1, uint 2 — one complete top-level item.
    const items = scanner.feedChunk(Uint8Array.from([0x82, 0x01, 0x02]));
    expect(items).toHaveLength(1);
    expect(Array.from(items[0]!)).toEqual([0x82, 0x01, 0x02]);
  });

  it("finds the boundary of a definite map item", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0xa1 = map(1), text "a" (0x61 0x61), uint 1.
    const items = scanner.feedChunk(Uint8Array.from([0xa1, 0x61, 0x61, 0x01]));
    expect(items).toHaveLength(1);
    expect(Array.from(items[0]!)).toEqual([0xa1, 0x61, 0x61, 0x01]);
  });
});

describe("CborSeqBoundaryScanner — indefinite-length structure (the named risk)", () => {
  it("finds the boundary of an indefinite-length array", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0x9f = array(indefinite), uint 1, uint 2, break.
    const bytes = Uint8Array.from([0x9f, 0x01, 0x02, 0xff]);
    const items = scanner.feedChunk(bytes);
    expect(items).toHaveLength(1);
    expect(Array.from(items[0]!)).toEqual(Array.from(bytes));
  });

  it("finds the boundary of an indefinite-length map", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0xbf = map(indefinite), "a" -> 1, break.
    const bytes = Uint8Array.from([0xbf, 0x61, 0x61, 0x01, 0xff]);
    const items = scanner.feedChunk(bytes);
    expect(items).toHaveLength(1);
    expect(Array.from(items[0]!)).toEqual(Array.from(bytes));
  });

  it("finds the boundary of an indefinite-length byte string", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0x5f = bytes(indefinite), one definite 2-byte chunk (0x42 0x01 0x02), break.
    const bytes = Uint8Array.from([0x5f, 0x42, 0x01, 0x02, 0xff]);
    const items = scanner.feedChunk(bytes);
    expect(items).toHaveLength(1);
    expect(Array.from(items[0]!)).toEqual(Array.from(bytes));
  });

  it("finds the boundary of an indefinite-length text string", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0x7f = text(indefinite), one definite 1-byte-length chunk "a" (0x61 0x61), break.
    const bytes = Uint8Array.from([0x7f, 0x61, 0x61, 0xff]);
    const items = scanner.feedChunk(bytes);
    expect(items).toHaveLength(1);
    expect(Array.from(items[0]!)).toEqual(Array.from(bytes));
  });

  it("handles an array containing a nested indefinite-length map", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0x81 = array(1) containing one indefinite map { "a": 1 }.
    const bytes = Uint8Array.from([0x81, 0xbf, 0x61, 0x61, 0x01, 0xff]);
    const items = scanner.feedChunk(bytes);
    expect(items).toHaveLength(1);
    expect(Array.from(items[0]!)).toEqual(Array.from(bytes));
  });
});

describe("CborSeqBoundaryScanner — malformed input fails loudly, not silently", () => {
  it("rejects an indefinite-length byte-string chunk of the wrong major type", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0x5f = bytes(indefinite), then a text-string chunk (major 3) instead
    // of a byte-string chunk (major 2) — malformed per RFC 8949 §3.2.3.
    const bytes = Uint8Array.from([0x5f, 0x61, 0x61, 0xff]);
    expect(() => scanner.feedChunk(bytes)).toThrow(MalformedCborSeqError);
  });

  it("rejects a nested indefinite-length chunk inside an indefinite-length string", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0x5f = bytes(indefinite), then ANOTHER indefinite bytes chunk (0x5f) —
    // chunks must be definite-length.
    const bytes = Uint8Array.from([0x5f, 0x5f, 0xff, 0xff]);
    expect(() => scanner.feedChunk(bytes)).toThrow(MalformedCborSeqError);
  });

  it("rejects indefinite-length encoding on an integer major type", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0x1f = major 0 (uint), additional info 31 (indefinite) — invalid.
    expect(() => scanner.feedChunk(Uint8Array.from([0x1f]))).toThrow(MalformedCborSeqError);
  });

  it("rejects a stray break byte with nothing open", () => {
    const scanner = new CborSeqBoundaryScanner();
    expect(() => scanner.feedChunk(Uint8Array.from([0xff]))).toThrow(MalformedCborSeqError);
  });

  it("rejects reserved additional-info values", () => {
    const scanner = new CborSeqBoundaryScanner();
    // 0x1c = major 0, additional info 28 (reserved).
    expect(() => scanner.feedChunk(Uint8Array.from([0x1c]))).toThrow(MalformedCborSeqError);
  });
});

describe("CborSeqBoundaryScanner — chunked / truncated input never hangs", () => {
  it("waits for more bytes rather than throwing when a multi-byte argument is split across chunks", () => {
    const scanner = new CborSeqBoundaryScanner();
    // uint with a 1-byte argument form: 0x18 0x2a = 42.
    expect(scanner.feedChunk(Uint8Array.from([0x18]))).toEqual([]);
    expect(scanner.pendingLength).toBe(1);
    const items = scanner.feedChunk(Uint8Array.from([0x2a]));
    expect(items).toHaveLength(1);
    expect(Array.from(items[0]!)).toEqual([0x18, 0x2a]);
    expect(scanner.pendingLength).toBe(0);
  });

  it("reports a non-zero pendingLength for a genuinely truncated final item (dropped connection)", () => {
    const scanner = new CborSeqBoundaryScanner();
    // A complete item (0x00) followed by the start of a truncated one
    // (0x19 needs 2 more bytes that never arrive).
    const items = scanner.feedChunk(Uint8Array.from([0x00, 0x19, 0x01]));
    expect(items).toHaveLength(1);
    expect(scanner.pendingLength).toBe(2);
  });

  it("yields items incrementally, one byte at a time, never batching until the whole body arrives", () => {
    const scanner = new CborSeqBoundaryScanner();
    // Three single-byte items fed one byte per feedChunk call.
    const allItems: Uint8Array[] = [];
    for (const byte of [0x00, 0x01, 0x02]) {
      const items = scanner.feedChunk(Uint8Array.from([byte]));
      allItems.push(...items);
    }
    expect(allItems).toHaveLength(3);
    expect(allItems.map((item) => item[0])).toEqual([0x00, 0x01, 0x02]);
  });
});

describe("classifyCborSeqItem", () => {
  it("classifies a plain map item as output, not error", () => {
    const bytes = Uint8Array.from([0xa1, 0x61, 0x61, 0x01]); // { a: 1 }
    const frame = classifyCborSeqItem(bytes, miniCborCodec);
    expect(frame).toEqual({ kind: "output", output: { a: 1 } });
  });

  it("classifies a Tag(48900, ...) item as the error sentinel", () => {
    // Tag 48900 (0xD9 0xBF 0x04) wrapping { code: "internal", message: "x" }.
    const inner = Uint8Array.from([
      0xa2, // map(2)
      0x64,
      0x63,
      0x6f,
      0x64,
      0x65, // "code"
      0x68,
      0x69,
      0x6e,
      0x74,
      0x65,
      0x72,
      0x6e,
      0x61,
      0x6c, // "internal"
      0x67,
      0x6d,
      0x65,
      0x73,
      0x73,
      0x61,
      0x67,
      0x65, // "message"
      0x61,
      0x78, // "x"
    ]);
    const tagged = Uint8Array.from([0xd9, 0xbf, 0x04, ...inner]);
    const frame = classifyCborSeqItem(tagged, miniCborCodec);
    expect(frame).toEqual({ kind: "error", error: { code: "internal", message: "x" } });
  });

  it("does not misclassify an unrelated tag as the error sentinel", () => {
    // Tag 0 (RFC 8949's own "standard date/time string" tag) around a
    // plain map — must decode as ordinary output, not an error frame.
    const inner = Uint8Array.from([0xa1, 0x61, 0x61, 0x01]); // { a: 1 }
    const tagged = Uint8Array.from([0xc0, ...inner]); // tag(0): 0xc0 = major 6, additional info 0
    const frame = classifyCborSeqItem(tagged, miniCborCodec);
    expect(frame.kind).toBe("output");
  });
});

describe("real server fixtures (examples/rpc-streaming, via the actual Rust encoder)", () => {
  it("decodes ticks-success.hex as three incremental output frames", () => {
    const scanner = new CborSeqBoundaryScanner();
    const items = scanner.feedChunk(loadFixture("ticks-success.hex"));
    expect(items).toHaveLength(3);
    expect(scanner.pendingLength).toBe(0);
    const frames = items.map((item) =>
      classifyCborSeqItem<{ index: number; value: number }>(item, miniCborCodec),
    );
    expect(frames).toEqual([
      { kind: "output", output: { index: 0, value: 0 } },
      { kind: "output", output: { index: 1, value: 1 } },
      { kind: "output", output: { index: 2, value: 2 } },
    ]);
  });

  it("decodes flaky-ticks-error.hex as two outputs then the error sentinel, and stops there", () => {
    const scanner = new CborSeqBoundaryScanner();
    const items = scanner.feedChunk(loadFixture("flaky-ticks-error.hex"));
    expect(items).toHaveLength(3);
    expect(scanner.pendingLength).toBe(0);
    const frames = items.map((item) =>
      classifyCborSeqItem<{ index: number; value: number }>(item, miniCborCodec),
    );
    expect(frames[0]).toEqual({ kind: "output", output: { index: 0, value: 100 } });
    expect(frames[1]).toEqual({ kind: "output", output: { index: 1, value: 101 } });
    expect(frames[2]!.kind).toBe("error");
    if (frames[2]!.kind === "error") {
      expect(frames[2]!.error.code).toBe("internal");
      // `CoolError::Internal`'s `public_message()` deliberately redacts
      // the real message to a generic "internal error" (see
      // `cratestack-core/src/error.rs`) — this is the server correctly
      // NOT leaking internal error text to clients, not a scanner bug.
      expect(frames[2]!.error.message).toBe("internal error");
    }
  });

  it("yields the real fixture's items incrementally, byte by byte, not only after the full body arrives", () => {
    const bytes = loadFixture("flaky-ticks-error.hex");
    const scanner = new CborSeqBoundaryScanner();
    const items: Uint8Array[] = [];
    for (const byte of bytes) {
      items.push(...scanner.feedChunk(Uint8Array.from([byte])));
    }
    expect(items).toHaveLength(3);
    const frames = items.map((item) => classifyCborSeqItem(item, miniCborCodec));
    expect(frames[2]!.kind).toBe("error");
  });
});

describe("cbor-item internals — argument decoding", () => {
  it("decodes the 2-byte, 4-byte, and 8-byte argument forms", () => {
    // uint with a 2-byte argument: 0x19 0x01 0x00 = 256.
    expect(skipItem(Uint8Array.from([0x19, 0x01, 0x00]), 0)).toBe(3);
    // uint with a 4-byte argument: 0x1a 0x00 0x01 0x00 0x00 = 65536.
    expect(skipItem(Uint8Array.from([0x1a, 0x00, 0x01, 0x00, 0x00]), 0)).toBe(5);
    // uint with an 8-byte argument (small value, just exercising the form).
    expect(skipItem(Uint8Array.from([0x1b, 0, 0, 0, 0, 0, 0, 0, 1]), 0)).toBe(9);
  });

  it("readArgument surfaces the raw tag number for the tag-header path", () => {
    // Tag 48900 header: 0xD9 0xBF 0x04 (additional info 25 == 2-byte form).
    const { value, next } = readArgument(Uint8Array.from([0xbf, 0x04]), 0, 25);
    expect(value).toBe(48900);
    expect(next).toBe(2);
  });
});
