//! Unit tests for the derived ceiling.
//!
//! These exist so the *integration* tests may derive it. That split is
//! deliberate and is the same reasoning cratestack#779 applied to floors:
//! a check that computes its expectation the same way the code under test
//! does agrees by construction and observes nothing. Here the expectations
//! are a hand-written table, so the arithmetic is pinned to values a human
//! chose — which is what makes it safe for
//! `tests/native_cbor_generator.rs` to compose a ceiling rather than
//! hardcode one, and keep its hand-written *floor* literal as the tripwire.

use super::{ceiling, requirement};

/// The table is the point. Each row was chosen for a reason, not
/// generated: the current version, a two-digit minor (the case a naive
/// string bump gets wrong), a minor rolling into a new tens boundary, the
/// 0.0.x line, and a post-1.0 version to pin the documented conservative
/// behaviour rather than leave it accidental.
#[test]
fn ceiling_is_the_next_minor() {
    for (version, expected) in [
        ("0.9.4", "0.10.0"),
        ("0.10.2", "0.11.0"),
        ("0.19.9", "0.20.0"),
        ("0.99.1", "0.100.0"),
        ("0.0.3", "0.1.0"),
        ("1.2.3", "1.3.0"),
    ] {
        assert_eq!(
            ceiling(version),
            expected,
            "ceiling({version:?}) should be {expected:?}"
        );
    }
}

/// `0.10.0` is the case a lexical or single-digit-assuming implementation
/// gets wrong, and it is not hypothetical — it is the next minor this repo
/// will cut. Called out separately so a regression names itself rather
/// than appearing as one row of the table above.
#[test]
fn the_two_digit_minor_does_not_regress_to_a_lower_line() {
    assert_eq!(ceiling("0.10.0"), "0.11.0");
    assert_ne!(
        ceiling("0.10.0"),
        "0.2.0",
        "a lexical bump of the minor would produce this"
    );
}

/// A pre-release suffix must not leak into the ceiling. `just bump` does
/// not produce one today; semver permits it, and the failure would be a
/// constraint string no resolver accepts.
#[test]
fn a_prerelease_suffix_is_ignored() {
    assert_eq!(ceiling("0.9.4-rc1"), "0.10.0");
    assert_eq!(ceiling("0.9.4+build7"), "0.10.0");
}

/// The composed shape, including that the floor is passed through
/// verbatim — a floor and ceiling on different minors is the
/// `CRATESTACK_ANNOTATIONS_FLOOR` case and must survive composition.
#[test]
fn requirement_pairs_the_floor_with_the_derived_ceiling() {
    assert_eq!(requirement("0.8.10", "0.9.4"), ">=0.8.10 <0.10.0");
    assert_eq!(requirement("0.9.3", "0.9.4"), ">=0.9.3 <0.10.0");
    assert_eq!(requirement("0.9.3", "0.10.0"), ">=0.9.3 <0.11.0");
}

/// The ceiling must be strictly above the version it was derived from,
/// or a client generated at that version could not resolve the very
/// release it was generated by. Stated as a property over the same table
/// rather than trusting the literals above to have covered it.
#[test]
fn the_ceiling_always_exceeds_its_own_version() {
    for version in ["0.9.4", "0.10.2", "0.19.9", "0.0.3", "1.2.3"] {
        let parsed = |v: &str| -> Vec<u64> {
            v.split('.')
                .map(|p| {
                    p.chars()
                        .take_while(char::is_ascii_digit)
                        .collect::<String>()
                        .parse()
                        .unwrap()
                })
                .collect()
        };
        assert!(
            parsed(&ceiling(version)) > parsed(version),
            "ceiling({version:?}) = {:?} must exceed {version:?}",
            ceiling(version)
        );
    }
}

#[test]
#[should_panic(expected = "has no minor component")]
fn an_unparseable_version_panics_by_name() {
    ceiling("0");
}
