import 'server-only';
import path from 'node:path';

// Loader for the napi-rs native addon.
//
// `react-nextjs-daisyui-napi`'s package.json `main` points at `index.js`
// generated by `napi build`; that JS shim loads the right `.node` binary
// for the current platform. We call `init(dbPath)` once per server process
// — the addon stores the runtime in a Rust `OnceLock`, so repeated init
// calls are no-ops.
//
// `process.env.CRATESTACK_NEXT_DB` lets you point the SQLite file
// anywhere; defaults to `./data/notes.db` at the project root.

type NoteRow = {
  id: string;
  title: string;
  body: string;
  pinned: boolean;
  completed: boolean;
  createdAt: string;
  updatedAt: string;
};

type ArticleRow = {
  id: number;
  title: string;
  body: string;
  published: boolean;
  createdAt: string;
};

type Addon = {
  init: (dbPath: string) => void;
  listNotes: () => NoteRow[];
  upsertNote: (note: NoteRow) => NoteRow;
  notesSince: (cursor: string) => NoteRow[];
  fetchRemoteArticles: (baseUrl: string) => Promise<ArticleRow[]>;
};

let cached: Addon | null = null;

export function loadAddon(): Addon {
  if (cached) return cached;
  // Resolve at runtime — Next's serverExternalPackages keeps this out of
  // the bundle. The require call sees the real `index.js` shim on disk.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const addon = require('react-nextjs-daisyui-napi') as Addon;
  const dbPath =
    process.env.CRATESTACK_NEXT_DB ?? path.resolve(process.cwd(), 'data/notes.db');
  addon.init(dbPath);
  cached = addon;
  return addon;
}

export type { NoteRow, ArticleRow };
