import 'server-only';
import path from 'node:path';
import { createRequire } from 'node:module';

// Loader for the napi-rs native addon.
//
// `react-nextjs-daisyui-napi`'s package.json `main` points at `index.js`
// generated by `napi build`; that JS shim loads the right `.node` binary
// for the current platform. We call `init(dbPath)` once per server process
// — the addon stores the runtime in a Rust `OnceLock`, so repeated init
// calls are no-ops.
//
// Why `createRequire` instead of a top-level `require()`: webpack would
// statically analyze `require('react-nextjs-daisyui-napi')`, follow the
// pnpm workspace symlink into `napi/index.js`, and then try to parse the
// `.node` binary as JavaScript and choke. `createRequire(import.meta.url)`
// is a runtime call that webpack treats opaquely — the `.node` resolution
// happens at run time via Node.js's own loader, exactly as intended.
//
// `process.env.CRATESTACK_NEXT_DB` lets you point the SQLite file
// anywhere; defaults to `./data/notes.db` at the project root.

const requireFromHere = createRequire(import.meta.url);

type NoteRow = {
  id: string;
  title: string;
  body: string;
  pinned: boolean;
  completed: boolean;
  createdAt: string;
  updatedAt: string;
};

type ArticleRow = {
  id: number;
  title: string;
  body: string;
  published: boolean;
  createdAt: string;
};

type Addon = {
  init: (dbPath: string) => void;
  listNotes: () => NoteRow[];
  upsertNote: (note: NoteRow) => NoteRow;
  notesSince: (cursor: string) => NoteRow[];
  fetchRemoteArticles: (baseUrl: string) => Promise<ArticleRow[]>;
};

let cached: Addon | null = null;

export function loadAddon(): Addon {
  if (cached) return cached;
  const addon = requireFromHere('react-nextjs-daisyui-napi') as Addon;
  const dbPath =
    process.env.CRATESTACK_NEXT_DB ?? path.resolve(process.cwd(), 'data/notes.db');
  addon.init(dbPath);
  cached = addon;
  return addon;
}

export type { NoteRow, ArticleRow };
