//! Client-side companion to `rpc-procedures-example`.
//!
//! Consumes a `transport rpc` server through the typed client generated by
//! `include_client_schema!`. This is the pure-client counterpart to the
//! server example: it owns no database and never emits a router — it only
//! speaks `POST /rpc/{op_id}` and `POST /rpc/batch` over HTTP/CBOR.
//!
//! Two call surfaces are demonstrated (both in `main.rs` and wired into
//! `tests/smoke.rs`):
//!
//! - **Unary** — `client.procedures().greet(&args)` returns a
//!   [`BatchableCall`](cratestack_client_rust::BatchableCall) that fires
//!   one `POST /rpc/procedure.greet` the moment you `.await` it.
//! - **Batch** — `client.batch()` returns a
//!   [`BatchBuilder`](cratestack_client_rust::BatchBuilder); prepare a few
//!   `BatchableCall`s, `.queue()` each into the same builder, then one
//!   `POST /rpc/batch` round-trip fan-outs and you collect each result by
//!   its [`BatchHandle`](cratestack_client_rust::BatchHandle).
//!
//! Because the schema is `transport rpc`, the macro emits a
//! `cratestack_schema::client::Client` whose procedure accessors are all
//! batchable — there is no REST surface here at all.
//!
//! Note this crate depends on `cratestack-client` (the pure HTTP-client
//! facade), not `cratestack-pg`. See the `Cargo.toml` for why.

use cratestack::include_client_schema;
use cratestack_client_rust::{AuthorizationRequest, ClientError, RequestAuthorizer};

include_client_schema!("schema.cstack");

/// Re-export the generated module so tests + binary share one path to the
/// `procedures::greet::Args`, `GreetReply`, etc. types.
pub use cratestack_schema as schema;

/// Injects the `x-auth-id` header on every request. The server example
/// reads it via a `HeaderAuthProvider` so any positive integer
/// authenticates as that caller id. Real apps replace this with a signing
/// authorizer (`HmacEnvelope`, JWT, etc.).
pub struct StaticAuthId(pub i64);

#[async_trait::async_trait]
impl RequestAuthorizer for StaticAuthId {
    async fn authorize(
        &self,
        _request: &AuthorizationRequest,
    ) -> Result<Vec<(String, String)>, ClientError> {
        Ok(vec![("x-auth-id".to_owned(), self.0.to_string())])
    }
}
