//! Compile-fail UI tests for `extension_gate.rs`'s "missing Cargo feature"
//! `compile_error!` diagnostics (cratestack#161) — trybuild spawns an
//! isolated `rustc` build per fixture and asserts it fails, without
//! hard-failing this crate's own `cargo test -p cratestack-macros` run the
//! way a plain `tests/*.rs` integration test invoking the same schema
//! would (that file would simply never compile, taking the whole `cargo
//! test` invocation down with it — the entire reason `trybuild` exists
//! rather than a checked-in fixture under `tests/`).
//!
//! The fixture `.rs` files under `tests/ui/generated/` are generated by
//! this driver at test time rather than checked in directly, because
//! `include_server_schema!` resolves its schema-path argument relative to
//! `CARGO_MANIFEST_DIR` of the crate being *compiled* (see
//! `include/parse.rs`'s `parse_schema_literal`), and trybuild compiles each
//! fixture as its own standalone crate in a generated temp directory — so a
//! relative path baked into a checked-in fixture would resolve against the
//! wrong directory there.
//!
//! **CI regression (cratestack#161 follow-up):** the first version of this
//! file substituted in an absolute path computed from *this* crate's own
//! `CARGO_MANIFEST_DIR` (i.e. the real checkout path). That resolved the
//! file correctly everywhere, but broke trybuild's exact-stderr snapshot
//! matching: the checkout path's *length* differs by environment (a deeply
//! nested local worktree vs. CI's shorter `/home/runner/work/...`), so the
//! generated source line's total length differed too — and rustc's
//! "cutting a long source line for display" logic (the `...` truncation
//! visible around the span in `-->`/`|` diagnostic lines) picks a different
//! truncation window depending on that length, not just on terminal width.
//! Two real `rustc` runs against *semantically* identical fixtures (same
//! macro call, same error) then render *different* snippet text, which is
//! exactly the "mismatch" CI reported even though the error message itself
//! was byte-identical. Fixed by copying each fixture into
//! [`FIXTURE_STAGING_DIR`] — a hardcoded absolute path with a fixed length
//! on every machine, not derived from any environment-dependent value — and
//! writing *that* path into the generated source instead. Unix-only by
//! construction (`/tmp`), which is fine: `tests-host` in `ci.yml` pins
//! `ubuntu-latest` for this job, and local development on this codebase is
//! macOS/Linux (see root `CLAUDE.md`'s Linux-prerequisite note).
//!
//! Terminal width itself was never actually the variable here, despite how
//! it looked: `trybuild`'s own `cargo.rs` (`build_test`/`build_all_tests`)
//! already calls `cmd.env_remove("RUSTFLAGS")` and unconditionally passes
//! `--diagnostic-width=140` via `--config=build.rustflags=...` for every
//! compile-fail build, in every environment — so rustc's line-wrapping
//! budget was already fixed and identical in both places. The only
//! remaining variable was the fixture source's own length, per above.
//!
//! `tests/ui/generated/` is gitignored (see
//! `crates/cratestack-macros/tests/ui/generated/.gitignore`) — it's build
//! output, not a fixture worth checking in; the `.stderr` snapshots next to
//! it are the actual checked-in fixtures.
//!
//! The pass side of this ticket's acceptance criteria ("feature enabled ->
//! the check succeeds") is covered by `include/extension_gate.rs`'s own
//! `#[cfg(feature = "rate_limit")]` / `#[cfg(feature = "pgvector")]` unit
//! tests instead of a second trybuild case here: once the guard clears, a
//! real `include_server_schema!` expansion continues into codegen that
//! references `::cratestack::*` paths only the real `cratestack-pg`/
//! `cratestack-sqlite` facade provides — exactly the "can't fully exercise
//! codegen runs" gap this ticket's own acceptance criteria calls out,
//! since no extension has real codegen yet (that's cratestack#154/#155).

use std::fs;
use std::path::{Path, PathBuf};

/// Fixed, environment-independent staging location for fixture `.cstack`
/// files referenced by the generated trybuild sources — see the module doc
/// for why this can't just be `CARGO_MANIFEST_DIR`-relative. Not
/// `std::env::temp_dir()`: that resolves to different, differently-sized
/// paths per OS (`/tmp` on Linux vs. a long per-process `/var/folders/...`
/// path on macOS), which would reintroduce the exact problem this constant
/// exists to avoid. A literal `/tmp/...` string is the same length
/// everywhere this test actually runs (see the module doc's Unix-only
/// note).
const FIXTURE_STAGING_DIR: &str = "/tmp/cratestack-macros-ui-161";

#[test]
fn extension_feature_gate_compile_fail() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let generated_dir = manifest_dir.join("tests/ui/generated");
    fs::create_dir_all(&generated_dir).expect("create tests/ui/generated");

    let staging_dir = Path::new(FIXTURE_STAGING_DIR);
    fs::create_dir_all(staging_dir).expect("create fixture staging dir");

    let t = trybuild::TestCases::new();

    // trybuild's generated crate inherits this crate's own active Cargo
    // features (confirmed empirically: running this test under
    // `--features pgvector` makes the pgvector fixture below compile
    // *successfully*, since the guard has nothing to reject once the
    // feature really is on). Skip each ordinary missing-feature fixture
    // once its feature is enabled — CI running this suite a second and
    // third time with `--features rate_limit` / `--features pgvector`
    // (see `include/extension_gate.rs`'s cfg-gated unit tests) is what
    // covers the pass side for those, not this file.
    if !cfg!(feature = "pgvector") {
        write_fixture(
            &manifest_dir,
            staging_dir,
            &generated_dir,
            "pgvector_feature_missing.rs",
            "tests/fixtures/pgvector_extension.cstack",
        );
        t.compile_fail(generated_dir.join("pgvector_feature_missing.rs"));
    }
    if !cfg!(feature = "rate_limit") {
        write_fixture(
            &manifest_dir,
            staging_dir,
            &generated_dir,
            "rate_limit_feature_missing.rs",
            "tests/fixtures/rate_limit_extension.cstack",
        );
        t.compile_fail(generated_dir.join("rate_limit_feature_missing.rs"));
    }

    // Distinct scenario from the two above, and run unconditionally: on
    // `include_embedded_schema!`, `pgvector` is rejected regardless of
    // the `pgvector` feature (docs/design/extensions.md §6) — the fixture
    // stays a compile failure no matter which of this crate's own
    // features are active.
    write_embedded_pgvector_fixture(
        &manifest_dir,
        staging_dir,
        &generated_dir,
        "pgvector_rejected_on_embedded.rs",
        "tests/fixtures/pgvector_extension_embedded.cstack",
    );
    t.compile_fail(generated_dir.join("pgvector_rejected_on_embedded.rs"));

    // Same guard, second Postgres-only extension (cratestack#842). Worth
    // its own case rather than trusting the pgvector one: the embedded
    // guard was generalised from a `pgvector` special case to an
    // `is_postgres_only` predicate, and this is what proves the new arm
    // actually fires instead of falling through to the ordinary
    // "feature not enabled" message.
    write_embedded_pgvector_fixture(
        &manifest_dir,
        staging_dir,
        &generated_dir,
        "postgis_rejected_on_embedded.rs",
        "tests/fixtures/postgis_extension_embedded.cstack",
    );
    t.compile_fail(generated_dir.join("postgis_rejected_on_embedded.rs"));

    // Distinct scenario again (cratestack computed-fields feature,
    // docs/design/computed-fields.md decision 3): `@computed` fields are
    // response-composition resolvers, and `include_embedded_schema!` has
    // no response boundary to resolve one against — rejected
    // unconditionally, same shape as the pgvector-on-embedded case above.
    write_embedded_computed_field_fixture(
        &manifest_dir,
        staging_dir,
        &generated_dir,
        "computed_field_rejected_on_embedded.rs",
        "tests/fixtures/computed_field_embedded_rejected.cstack",
    );
    t.compile_fail(generated_dir.join("computed_field_rejected_on_embedded.rs"));
}

/// Copies `relative_schema_path` (resolved against *this* crate's own,
/// correct `CARGO_MANIFEST_DIR`) into `staging_dir`, returning the fixed,
/// environment-independent absolute path it now lives at — see the module
/// doc for why the generated fixture references this copy rather than the
/// checked-in original directly.
fn stage_fixture(manifest_dir: &Path, staging_dir: &Path, relative_schema_path: &str) -> PathBuf {
    let source = manifest_dir.join(relative_schema_path);
    let file_name = source
        .file_name()
        .expect("fixture schema path should have a file name");
    let staged = staging_dir.join(file_name);
    fs::copy(&source, &staged).unwrap_or_else(|error| {
        panic!(
            "copy fixture {} to {}: {error}",
            source.display(),
            staged.display()
        )
    });
    staged
}

/// Writes a fixture that calls `include_server_schema!` with the staged,
/// fixed-length path to `relative_schema_path` (see [`stage_fixture`]).
/// Expected to fail with `extension_gate.rs`'s "missing Cargo feature"
/// `compile_error!`, since neither the `pgvector` nor `rate_limit` feature
/// is enabled for this default (no extra `--features`) trybuild
/// invocation.
fn write_fixture(
    manifest_dir: &Path,
    staging_dir: &Path,
    generated_dir: &Path,
    file_name: &str,
    relative_schema_path: &str,
) {
    let staged = stage_fixture(manifest_dir, staging_dir, relative_schema_path);
    let staged = staged
        .to_str()
        .expect("fixture staging path should be valid UTF-8");
    let source = format!(
        "cratestack_macros::include_server_schema!({staged:?}, db = None);\n\nfn main() {{}}\n"
    );
    fs::write(generated_dir.join(file_name), source).expect("write generated trybuild fixture");
}

/// Same idea as [`write_fixture`], but calls `include_embedded_schema!`
/// (bare path literal, no `db` argument) — expected to fail with
/// `extension_gate.rs`'s dedicated "pgvector is never valid on the
/// embedded backend" `compile_error!`, distinct from the ordinary
/// missing-feature message the other two fixtures exercise.
fn write_embedded_pgvector_fixture(
    manifest_dir: &Path,
    staging_dir: &Path,
    generated_dir: &Path,
    file_name: &str,
    relative_schema_path: &str,
) {
    let staged = stage_fixture(manifest_dir, staging_dir, relative_schema_path);
    let staged = staged
        .to_str()
        .expect("fixture staging path should be valid UTF-8");
    let source =
        format!("cratestack_macros::include_embedded_schema!({staged:?});\n\nfn main() {{}}\n");
    fs::write(generated_dir.join(file_name), source).expect("write generated trybuild fixture");
}

/// Same idea as [`write_embedded_pgvector_fixture`], but for a schema
/// declaring an `@computed` field — expected to fail with
/// `include::embedded::computed_guard`'s dedicated "no response boundary"
/// `compile_error!` (docs/design/computed-fields.md decision 3).
fn write_embedded_computed_field_fixture(
    manifest_dir: &Path,
    staging_dir: &Path,
    generated_dir: &Path,
    file_name: &str,
    relative_schema_path: &str,
) {
    let staged = stage_fixture(manifest_dir, staging_dir, relative_schema_path);
    let staged = staged
        .to_str()
        .expect("fixture staging path should be valid UTF-8");
    let source =
        format!("cratestack_macros::include_embedded_schema!({staged:?});\n\nfn main() {{}}\n");
    fs::write(generated_dir.join(file_name), source).expect("write generated trybuild fixture");
}
