//! Compile-fail UI tests for `extension_gate.rs`'s "missing Cargo feature"
//! `compile_error!` diagnostics (cratestack#161) — trybuild spawns an
//! isolated `rustc` build per fixture and asserts it fails, without
//! hard-failing this crate's own `cargo test -p cratestack-macros` run the
//! way a plain `tests/*.rs` integration test invoking the same schema
//! would (that file would simply never compile, taking the whole `cargo
//! test` invocation down with it — the entire reason `trybuild` exists
//! rather than a checked-in fixture under `tests/`).
//!
//! The fixture `.rs` files under `tests/ui/generated/` are generated by
//! this driver at test time rather than checked in directly:
//! `include_server_schema!` resolves its schema-path argument relative to
//! `CARGO_MANIFEST_DIR` of the crate being *compiled* (see
//! `include/parse.rs`'s `parse_schema_literal`), and trybuild compiles
//! each fixture as its own standalone crate in a generated temp directory
//! — so a relative path baked into a checked-in fixture would resolve
//! against the wrong directory there. Substituting in an absolute path,
//! computed from *this* crate's own correct `CARGO_MANIFEST_DIR`, at
//! generation time sidesteps that entirely: `PathBuf::join` with an
//! absolute path replaces the base path outright (see its stdlib docs),
//! so the schema resolves the same no matter where trybuild puts the
//! generated crate. `tests/ui/generated/` is gitignored (see
//! `crates/cratestack-macros/tests/ui/generated/.gitignore`) — it's
//! build output, not a fixture worth checking in.
//!
//! The pass side of this ticket's acceptance criteria ("feature enabled ->
//! the check succeeds") is covered by `include/extension_gate.rs`'s own
//! `#[cfg(feature = "rate_limit")]` / `#[cfg(feature = "pgvector")]` unit
//! tests instead of a second trybuild case here: once the guard clears, a
//! real `include_server_schema!` expansion continues into codegen that
//! references `::cratestack::*` paths only the real `cratestack-pg`/
//! `cratestack-sqlite` facade provides — exactly the "can't fully exercise
//! codegen runs" gap this ticket's own acceptance criteria calls out,
//! since no extension has real codegen yet (that's cratestack#154/#155).

use std::fs;
use std::path::{Path, PathBuf};

#[test]
fn extension_feature_gate_compile_fail() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let generated_dir = manifest_dir.join("tests/ui/generated");
    fs::create_dir_all(&generated_dir).expect("create tests/ui/generated");

    let t = trybuild::TestCases::new();

    // trybuild's generated crate inherits this crate's own active Cargo
    // features (confirmed empirically: running this test under
    // `--features pgvector` makes the pgvector fixture below compile
    // *successfully*, since the guard has nothing to reject once the
    // feature really is on). Skip each ordinary missing-feature fixture
    // once its feature is enabled — CI running this suite a second and
    // third time with `--features rate_limit` / `--features pgvector`
    // (see `include/extension_gate.rs`'s cfg-gated unit tests) is what
    // covers the pass side for those, not this file.
    if !cfg!(feature = "pgvector") {
        write_fixture(
            &manifest_dir,
            &generated_dir,
            "pgvector_feature_missing.rs",
            "tests/fixtures/pgvector_extension.cstack",
        );
        t.compile_fail(generated_dir.join("pgvector_feature_missing.rs"));
    }
    if !cfg!(feature = "rate_limit") {
        write_fixture(
            &manifest_dir,
            &generated_dir,
            "rate_limit_feature_missing.rs",
            "tests/fixtures/rate_limit_extension.cstack",
        );
        t.compile_fail(generated_dir.join("rate_limit_feature_missing.rs"));
    }

    // Distinct scenario from the two above, and run unconditionally: on
    // `include_embedded_schema!`, `pgvector` is rejected regardless of
    // the `pgvector` feature (docs/design/extensions.md §6) — the fixture
    // stays a compile failure no matter which of this crate's own
    // features are active.
    write_embedded_pgvector_fixture(
        &manifest_dir,
        &generated_dir,
        "pgvector_rejected_on_embedded.rs",
        "tests/fixtures/pgvector_extension_embedded.cstack",
    );
    t.compile_fail(generated_dir.join("pgvector_rejected_on_embedded.rs"));
}

/// Writes a fixture that calls `include_server_schema!` with an absolute
/// path to `relative_schema_path` (resolved against *this* crate's own
/// `CARGO_MANIFEST_DIR` — see the module doc). Expected to fail with
/// `extension_gate.rs`'s "missing Cargo feature" `compile_error!`, since
/// neither the `pgvector` nor `rate_limit` feature is enabled for this
/// default (no extra `--features`) trybuild invocation.
fn write_fixture(
    manifest_dir: &Path,
    generated_dir: &Path,
    file_name: &str,
    relative_schema_path: &str,
) {
    let schema_abs = manifest_dir.join(relative_schema_path);
    let schema_abs = schema_abs
        .to_str()
        .expect("fixture schema path should be valid UTF-8");
    let source = format!(
        "cratestack_macros::include_server_schema!({schema_abs:?}, db = None);\n\nfn main() {{}}\n"
    );
    fs::write(generated_dir.join(file_name), source).expect("write generated trybuild fixture");
}

/// Same idea as [`write_fixture`], but calls `include_embedded_schema!`
/// (bare path literal, no `db` argument) — expected to fail with
/// `extension_gate.rs`'s dedicated "pgvector is never valid on the
/// embedded backend" `compile_error!`, distinct from the ordinary
/// missing-feature message the other two fixtures exercise.
fn write_embedded_pgvector_fixture(
    manifest_dir: &Path,
    generated_dir: &Path,
    file_name: &str,
    relative_schema_path: &str,
) {
    let schema_abs = manifest_dir.join(relative_schema_path);
    let schema_abs = schema_abs
        .to_str()
        .expect("fixture schema path should be valid UTF-8");
    let source =
        format!("cratestack_macros::include_embedded_schema!({schema_abs:?});\n\nfn main() {{}}\n");
    fs::write(generated_dir.join(file_name), source).expect("write generated trybuild fixture");
}
