//! Compile-fail proof for cratestack#512: `registry.<method>(&db, &ctx,
//! args)` — calling a `ProcedureRegistry` method directly, the natural-
//! looking way to invoke a procedure from non-HTTP code — must not
//! compile, because it skips every `@allow`/`@deny` check. The generated
//! trait method's last parameter is an `Authorized` witness
//! (`crate::procedure::instrument::authorized_type_tokens`) that only
//! `<procedure>::authorize_with_db`/`<procedure>::invoke_with_db` can
//! construct (private tuple field, module-scoped) — so a call omitting it
//! is an ordinary arity mismatch, not a policy check that happens to run
//! and pass. This driver writes exactly that call into a generated
//! `main()` (`tests/ui/generated/procedure_registry_witness_missing_arg.rs`,
//! gitignored — regenerated by every run, same as every other fixture
//! `ui.rs`/`ui_semantic.rs` write) and asserts it fails to compile.
//!
//! **Why this is a separate suite from `ui.rs`/`ui_semantic.rs`:** those
//! two deliberately never reach real generated-code compilation — every
//! fixture there fails during macro expansion itself (a missing Cargo
//! feature, a malformed schema), before `include_server_schema!` ever
//! emits code that references `::cratestack::*` runtime paths (see
//! `ui_semantic.rs`'s own module doc for exactly this gap). This
//! fixture's whole point is the opposite: the schema must expand
//! *successfully* into a real `ProcedureRegistry` trait and a real
//! `impl` of it, and the failure must come from the call site afterward.
//! That needs `::cratestack::CratestackContext`/`CratestackError`/`Cratestack` to
//! resolve, which requires an actual `cratestack` (facade) dependency —
//! `cratestack-macros`'s ordinary `[dependencies]` deliberately doesn't
//! carry one (this crate only emits code, it doesn't need the runtime
//! types to do that). See `Cargo.toml`'s `[dev-dependencies]` entry for
//! why `cratestack-api` specifically, and why the dev-dependency cycle
//! back through this crate is fine.
//!
//! **Checked-in `.stderr` snapshot, same as the other two suites, and for
//! the same reason.** It's tempting to skip pinning exact rustc prose
//! here (an argument-count mismatch drifting across rustc versions carries
//! no signal about whether the actual guarantee — "the compile fails" —
//! still holds), and `trybuild`'s own per-test logic does tolerate a
//! missing `.stderr` (it writes what it got to `wip/` and reports that one
//! test as passed). But `trybuild::Runner::run`'s *overall* driver — which
//! every `TestCases` instance runs on `Drop` — unconditionally panics with
//! "successfully created new stderr files for N test cases" whenever any
//! test produced a `wip` outcome, regardless of whether every individual
//! test's compile-fail assertion itself held (`report.created_wip > 0`
//! branch in `run.rs`). So a `.stderr` file here isn't optional the way
//! this module's first draft assumed — confirmed by running this test
//! without one and getting exactly that panic. The snapshot
//! (`tests/ui/generated/procedure_registry_witness_missing_arg.stderr`)
//! was generated with `TRYBUILD=overwrite` and is the real rustc output
//! for this fixture, checked in like the other nine.
//!
//! Uses the same fixture-staging trick as `ui.rs`/`ui_semantic.rs` (see
//! `ui.rs`'s module doc) so the generated source's absolute path length
//! doesn't vary by checkout location — irrelevant to *this* file's lack
//! of a `.stderr` snapshot, but kept for consistency and because a
//! future contributor might reasonably add one.

use std::fs;
use std::path::{Path, PathBuf};

const FIXTURE_STAGING_DIR: &str = "/tmp/cratestack-macros-ui-witness-512";

#[test]
fn procedure_registry_direct_call_without_witness_does_not_compile() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let generated_dir = manifest_dir.join("tests/ui/generated");
    fs::create_dir_all(&generated_dir).expect("create tests/ui/generated");

    let staging_dir = Path::new(FIXTURE_STAGING_DIR);
    fs::create_dir_all(staging_dir).expect("create fixture staging dir");

    let staged = stage_fixture(
        &manifest_dir,
        staging_dir,
        "tests/fixtures/procedure_registry_witness.cstack",
    );
    let staged = staged
        .to_str()
        .expect("fixture staging path should be valid UTF-8");

    let source = format!(
        r#"cratestack::include_server_schema!({staged:?}, db = None);

// Imported so the only remaining compile error is the arity mismatch
// (missing `Authorized` witness) this fixture exists to prove, not an
// unrelated "trait not in scope" error the trait-method call syntax
// below would otherwise also trigger.
use cratestack_schema::procedures::ProcedureRegistry;

#[derive(Clone, Default)]
struct Procedures;

impl cratestack_schema::procedures::ProcedureRegistry for Procedures {{
    async fn ping(
        &self,
        _db: &cratestack_schema::Cratestack,
        _ctx: &cratestack::CratestackContext,
        args: cratestack_schema::procedures::ping::Args,
        _authorized: cratestack_schema::procedures::ping::Authorized,
    ) -> Result<cratestack_schema::procedures::ping::Output, cratestack::CratestackError> {{
        Ok(cratestack_schema::PingReply {{
            echo: args.args.message,
        }})
    }}
}}

fn main() {{
    let db = cratestack_schema::Cratestack::builder().build();
    let ctx = cratestack::CratestackContext::anonymous();
    let args = cratestack_schema::procedures::ping::Args {{
        args: cratestack_schema::PingArgs {{
            message: "hello".to_owned(),
        }},
    }};
    let registry = Procedures;

    // cratestack#512: the natural, readable call — no `Authorized`
    // witness — must fail to compile with an arity mismatch, not run
    // (and silently skip) `@allow(auth() != null)`.
    let _ = registry.ping(&db, &ctx, args);
}}
"#
    );
    let fixture_path = generated_dir.join("procedure_registry_witness_missing_arg.rs");
    fs::write(&fixture_path, source).expect("write generated trybuild fixture");

    let t = trybuild::TestCases::new();
    t.compile_fail(fixture_path);
}

/// Same helper as `ui.rs`/`ui_semantic.rs` — see `ui.rs`'s module doc for
/// why the fixture references a staged copy rather than the checked-in
/// original directly.
fn stage_fixture(manifest_dir: &Path, staging_dir: &Path, relative_schema_path: &str) -> PathBuf {
    let source = manifest_dir.join(relative_schema_path);
    let file_name = source
        .file_name()
        .expect("fixture schema path should have a file name");
    let staged = staging_dir.join(file_name);
    fs::copy(&source, &staged).unwrap_or_else(|error| {
        panic!(
            "copy fixture {} to {}: {error}",
            source.display(),
            staged.display()
        )
    });
    staged
}
