//! Client-side companion to `rpc-streaming-example`.
//!
//! Consumes the `procedure.ticks` cbor-seq stream via a typed client
//! generated by `include_client_schema!` from the same `.cstack` schema
//! the server compiles against. The macro branches on `transport rpc`
//! and emits a `cratestack_schema::client::Client` whose
//! sequence-returning procedures return an
//! [`RpcStream`](cratestack_client_rust::RpcStream) —
//! `tokio::sync::mpsc::Receiver<Result<Item, RpcClientError>>` — so
//! items arrive on the channel as cbor-seq frames parse off the wire
//! rather than buffering the full response.
//!
//! `main.rs` is the runnable binary; `tests/smoke.rs` exercises the
//! end-to-end consumption path against a tiny in-process mock so the
//! demo runs in CI without needing the server example running.

use cratestack::include_client_schema;
use cratestack_client_rust::{AuthorizationRequest, ClientError, RequestAuthorizer};

include_client_schema!("schema.cstack");

/// Injects the `x-auth-id` header on every request. The server example
/// reads it via a `HeaderAuthProvider` so any positive integer
/// authenticates as that caller id. Real apps replace this with a
/// signing authorizer (`HmacEnvelope`, JWT, etc.).
pub struct StaticAuthId(pub i64);

impl RequestAuthorizer for StaticAuthId {
    fn authorize(
        &self,
        _request: &AuthorizationRequest,
    ) -> Result<Vec<(String, String)>, ClientError> {
        Ok(vec![("x-auth-id".to_owned(), self.0.to_string())])
    }
}
