//! Who reads each dropped attribute, by name (regenerated by reading the
//! table's own test failure message). See `tests_readers.rs`.

pub(super) const READERS: &[(&str, &[&str])] = &[
    (
        "@@allow",
        &[
            "cratestack-client-typescript/src/types.rs",
            "cratestack-lsp/src/completion.rs",
            "cratestack-lsp/src/mcp_completion.rs",
            "cratestack-macros/src/axum/policy_attr.rs",
            "cratestack-macros/src/include/mcp_gate.rs",
            "cratestack-macros/src/policy/model.rs",
            "cratestack-macros/src/policy/model/audit.rs",
        ],
    ),
    (
        "@@deny",
        &[
            "cratestack-macros/src/policy/model.rs",
            "cratestack-macros/src/policy/model/audit.rs",
        ],
    ),
    (
        "@allow",
        &[
            "cratestack-core/src/procedure_route.rs",
            "cratestack-lsp/src/completion.rs",
            "cratestack-lsp/src/mcp_completion.rs",
            "cratestack-macros/src/include/embedded/query_guard.rs",
            "cratestack-macros/src/include/mcp_gate.rs",
            "cratestack-macros/src/include/server/query_guard.rs",
            "cratestack-macros/src/policy/procedure.rs",
        ],
    ),
    ("@deny", &["cratestack-macros/src/policy/procedure.rs"]),
    (
        "@authorize",
        &["cratestack-macros/src/procedure/authorizer.rs"],
    ),
    ("@@index", &["cratestack-migrate/src/convert/indexes.rs"]),
    (
        "@@unique",
        &[
            "cratestack-cli/src/schema_diff/models.rs",
            "cratestack-lsp/src/completion.rs",
            "cratestack-migrate/src/convert/uniques.rs",
        ],
    ),
    (
        "@@sql",
        &[
            "cratestack-lsp/src/completion.rs",
            "cratestack-macros/src/include/embedded/query_guard.rs",
            "cratestack-macros/src/include/server/query_guard.rs",
        ],
    ),
    ("@@server_sql", &[]),
    (
        "@@embedded_sql",
        &["cratestack-macros/src/include/embedded/query_guard.rs"],
    ),
    (
        "@@materialized",
        &[
            "cratestack-macros/src/include/embedded.rs",
            "cratestack-sqlx/src/delegate/view.rs",
        ],
    ),
    (
        "@@no_unique",
        &[
            "cratestack-macros/src/view/accessor.rs",
            "cratestack-macros/src/view/descriptor.rs",
        ],
    ),
    ("@@audit", &["cratestack-macros/src/model/descriptor.rs"]),
    ("@@retain", &["cratestack-macros/src/model/descriptor.rs"]),
    (
        "@@soft_delete",
        &["cratestack-macros/src/model/descriptor.rs"],
    ),
    ("@@rename", &["cratestack-migrate/src/convert/renames.rs"]),
    ("@rename", &["cratestack-migrate/src/convert/renames.rs"]),
    (
        "@@internal",
        &[
            "cratestack-cli/src/schema_diff/models.rs",
            "cratestack-lsp/src/completion.rs",
            "cratestack-macros/src/include/mcp_gate/resources.rs",
        ],
    ),
    ("@@subscribe", &["cratestack-core/src/op_list.rs"]),
    (
        "@@emit",
        &[
            "cratestack-core/src/events.rs",
            "cratestack-macros/src/event.rs",
            "cratestack-macros/src/procedure/registry_method.rs",
            "cratestack-studio/src/api/records/guards.rs",
            "cratestack-studio/src/data/model_info.rs",
        ],
    ),
    (
        "@no_idempotency",
        &["cratestack-macros/src/transport/idempotency.rs"],
    ),
    (
        "@no_rate_limit",
        &[
            "cratestack-axum/src/ratelimit/rest_ops_filter.rs",
            "cratestack-macros/src/transport/rate_limit.rs",
        ],
    ),
    (
        "@isolation",
        &[
            "cratestack-macros/src/include/server/isolated.rs",
            "cratestack-macros/src/shared/procedure_attrs.rs",
            "cratestack-sqlx/src/bound.rs",
            "cratestack-sqlx/src/bound/join.rs",
            "cratestack-sqlx/src/bound/nested.rs",
            "cratestack-sqlx/src/isolated_run.rs",
        ],
    ),
    (
        "@length",
        &[
            "cratestack-macros/src/validators/parse.rs",
            "cratestack-migrate/src/convert/checks.rs",
            "cratestack-studio/src/validators/predicates.rs",
        ],
    ),
    (
        "@range",
        &[
            "cratestack-macros/src/validators/parse.rs",
            "cratestack-migrate/src/convert/checks.rs",
            "cratestack-studio/src/validators/predicates.rs",
        ],
    ),
    (
        "@regex",
        &[
            "cratestack-macros/src/validators/emit.rs",
            "cratestack-studio/src/validators/predicates.rs",
        ],
    ),
    (
        "@email",
        &["cratestack-studio/src/validators/predicates.rs"],
    ),
    ("@uri", &["cratestack-studio/src/validators/predicates.rs"]),
    (
        "@iso4217",
        &[
            "cratestack-migrate/src/convert/checks.rs",
            "cratestack-studio/src/validators/predicates.rs",
        ],
    ),
    ("@pii", &["cratestack-macros/src/shared/attrs.rs"]),
    ("@sensitive", &["cratestack-macros/src/shared/attrs.rs"]),
    ("@db_enforce", &["cratestack-migrate/src/convert/checks.rs"]),
    (
        "@unique",
        &[
            "cratestack-lsp/src/completion.rs",
            "cratestack-migrate/src/convert/fields.rs",
            "cratestack-migrate/src/convert/renames.rs",
        ],
    ),
    ("@from", &[]),
    (
        "@deprecated",
        &["cratestack-macros/src/axum/procedure/route_attrs.rs"],
    ),
];
