// TypeScript surface of the `cratestack-notes` local Expo module.
//
// At runtime, the native side of this module (ios/CratestackNotesModule.swift
// + android/.../CratestackNotesModule.kt — generated by
// `npx create-expo-module@latest` and then filled in by hand) loads the
// `embedded_expo_native` cdylib and exposes two functions:
//
//   initDatabase(dbPath: string)   →  calls cratestack_init
//   dispatch(requestJson: string)  →  calls cratestack_dispatch + cratestack_free
//
// Both are exposed via `expo-modules-core`'s `requireNativeModule`. The
// JS side wraps them in typed accessors that mirror the cratestack
// schema's `Note` model.
//
// Until the native side is wired, the typed methods below throw an
// explanatory error so the app fails loudly rather than silently
// dropping data.

import { requireNativeModule } from 'expo-modules-core';

export type NoteView = {
  id: string;
  title: string;
  body: string;
  pinned: boolean;
  completed: boolean;
  createdAt: string;
  updatedAt: string;
};

export type NewNote = {
  title: string;
  body?: string;
  pinned?: boolean;
};

type Envelope =
  | { status: 'ok'; data: unknown }
  | { status: 'err'; code: string; message: string };

interface NativeModule {
  initDatabase(dbPath: string): Promise<void> | void;
  dispatch(requestJson: string): Promise<string> | string;
}

let nativeModule: NativeModule | null = null;

function loadNativeModule(): NativeModule {
  if (nativeModule) return nativeModule;
  try {
    nativeModule = requireNativeModule('CratestackNotes') as NativeModule;
    return nativeModule;
  } catch (error) {
    throw new Error(
      'cratestack-notes native module is not linked. Run `npx create-expo-module ' +
        'modules/cratestack-notes` to scaffold the iOS + Android sources, then wire ' +
        '`cratestack_init` / `cratestack_dispatch` / `cratestack_free` into the ' +
        'generated `CratestackNotesModule`. See the README in this example. ' +
        `(underlying error: ${error instanceof Error ? error.message : String(error)})`,
    );
  }
}

function unwrap(envelope: Envelope): unknown {
  if (envelope.status === 'ok') return envelope.data;
  const err = new Error(envelope.message);
  (err as Error & { code: string }).code = envelope.code;
  throw err;
}

async function call<T>(
  model: string,
  kind: 'find_many' | 'find_unique' | 'create' | 'update' | 'delete',
  payload: unknown,
): Promise<T> {
  const native = loadNativeModule();
  const requestJson = JSON.stringify({ model, kind, payload });
  const responseJson = await native.dispatch(requestJson);
  return unwrap(JSON.parse(responseJson) as Envelope) as T;
}

export async function initDatabase(dbPath: string): Promise<void> {
  const native = loadNativeModule();
  await native.initDatabase(dbPath);
}

export function listNotes(): Promise<NoteView[]> {
  return call<NoteView[]>('Note', 'find_many', null);
}

export function findNote(id: string): Promise<NoteView | null> {
  return call<NoteView | null>('Note', 'find_unique', id);
}

export function createNote(input: NewNote): Promise<NoteView> {
  return call<NoteView>('Note', 'create', input);
}

export function updateNote(
  id: string,
  patch: Partial<Pick<NoteView, 'title' | 'body' | 'pinned' | 'completed'>>,
): Promise<NoteView> {
  return call<NoteView>('Note', 'update', { id, ...patch });
}

export function deleteNote(id: string): Promise<NoteView> {
  return call<NoteView>('Note', 'delete', id);
}
