import { RefineFixtureClientClient } from "../fixtures/generated-client/src/client.js";
import { type FakeResourceSchema, FakeRestServer } from "./fake-rest-server.js";

/** Wires a REAL `RefineFixtureClientClient` (generated by
 *  `cargo run -p cratestack-cli -- generate-typescript` against
 *  `tests/fixtures/refine_fixture.cstack`, committed under
 *  `tests/fixtures/generated-client/`) to an in-memory `FakeRestServer`
 *  via the runtime's own `fetch` injection point. Every test in this
 *  suite goes through this, not a hand-rolled stand-in for the
 *  generated client's shape. */
export function createTestClient(schemas: FakeResourceSchema[]): {
  server: FakeRestServer;
  client: RefineFixtureClientClient;
} {
  const server = new FakeRestServer(schemas);
  const client = new RefineFixtureClientClient("https://example.test", {
    basePath: "/api",
    fetch: server.fetch,
  });
  return { server, client };
}

export const WIDGET_SCHEMA: FakeResourceSchema = { path: "widgets", primaryKey: "id" };
export const LEDGER_SCHEMA: FakeResourceSchema = {
  path: "ledgers",
  primaryKey: "id",
  versionField: "version",
  paged: true,
};
export const PRODUCT_SCHEMA: FakeResourceSchema = { path: "products", primaryKey: "sku" };
