import { RefineFixtureRpcClientClient } from "../fixtures/generated-client-rpc/src/client.js";
import { type FakeRpcResourceSchema, FakeRpcServer } from "./fake-rpc-server.js";

/** Wires a REAL `RefineFixtureRpcClientClient` (generated by
 *  `cargo run -p cratestack-cli -- generate-typescript` against
 *  `tests/fixtures/refine_fixture_rpc.cstack`, produced by
 *  `just refine-rpc-fixture`) to an in-memory `FakeRpcServer` via the
 *  runtime's own `fetch` injection point. Every RPC test in this suite
 *  goes through this, not a hand-rolled stand-in for the generated
 *  client's shape — the sibling of `./client.ts` for REST. */
export function createRpcTestClient(schemas: FakeRpcResourceSchema[]): {
  server: FakeRpcServer;
  client: RefineFixtureRpcClientClient;
} {
  const server = new FakeRpcServer(schemas);
  const client = new RefineFixtureRpcClientClient("https://example.test", {
    basePath: "/api",
    fetch: server.fetch,
  });
  return { server, client };
}

export const WIDGET_RPC_SCHEMA: FakeRpcResourceSchema = { model: "Widget", primaryKey: "id" };
export const LEDGER_RPC_SCHEMA: FakeRpcResourceSchema = {
  model: "Ledger",
  primaryKey: "id",
  versionField: "version",
  paged: true,
};
export const PRODUCT_RPC_SCHEMA: FakeRpcResourceSchema = { model: "Product", primaryKey: "sku" };
