import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod_client/flutter_riverpod_client.dart';
import 'package:flutter_riverpod_example_app/src/screens/boards_screen.dart';
import 'package:flutter_test/flutter_test.dart';

/// A fake [CratestackClientAdapter] this test overrides
/// `flutterRiverpodClientAdapterProvider` with — the same, unmodified
/// override point `client/README.md`'s "Adapter Setup" documents (issue
/// #302's acceptance criterion: every generated provider must be
/// reachable through it, never through some new seam this app invents).
/// Recording `requests` proves the generated `BoardApi.list()`/
/// `.create()` methods actually ran; returning canned bodies proves the
/// data rendered on screen came from *this* fake, not a live network
/// call — no real server needed to prove the wiring.
class _FakeAdapter implements CratestackClientAdapter {
  final requests = <CratestackRequest>[];
  final _boards = <Map<String, Object?>>[
    {'id': 1, 'name': 'Getting Started'},
  ];
  var _nextId = 2;

  @override
  Future<Object?> execute(
    CratestackRequest request, {
    CratestackCallOptions? options,
  }) async {
    requests.add(request);
    if (request.method == 'GET' && request.path == '/api/boards') {
      // Stateful, not a static fixture: a create below must actually
      // show up on the next list call, the same way a real server
      // would, or this test would prove nothing about the generated
      // `ref.invalidate(boardListProvider)` refresh actually working.
      return List<Object?>.of(_boards);
    }
    if (request.method == 'POST' && request.path == '/api/boards') {
      final body = request.body as Map<String, Object?>;
      final created = <String, Object?>{'id': _nextId++, 'name': body['name']};
      _boards.add(created);
      return created;
    }
    throw StateError('unexpected request: ${request.method} ${request.path}');
  }
}

void main() {
  testWidgets(
    'overriding flutterRiverpodClientAdapterProvider alone renders real '
    'board data end to end (issue #303: this app has zero hand-written '
    'providers — every provider read/written below was generated by '
    '`cratestack generate-dart --preset riverpod`)',
    (tester) async {
      final fakeAdapter = _FakeAdapter();
      await tester.pumpWidget(
        ProviderScope(
          overrides: [
            flutterRiverpodClientAdapterProvider.overrideWithValue(fakeAdapter),
          ],
          child: const MaterialApp(home: BoardsScreen()),
        ),
      );

      // First frame: `boardListProvider` (generated) is still loading —
      // proves the screen is really driven by the async provider, not a
      // synchronously-available fixture.
      expect(find.byType(CircularProgressIndicator), findsOneWidget);

      await tester.pumpAndSettle();

      expect(fakeAdapter.requests, hasLength(1));
      expect(fakeAdapter.requests.single.method, 'GET');
      expect(fakeAdapter.requests.single.path, '/api/boards');
      expect(find.text('Getting Started'), findsOneWidget);

      // Add a board through the generated `BoardCreateController`, then
      // confirm the list visibly refreshes with no manual fetch call
      // anywhere in `boards_screen.dart` — only `ref.invalidate` on an
      // already-generated provider.
      await tester.enterText(find.byType(TextField), 'Second Board');
      await tester.tap(find.widgetWithText(FilledButton, 'Add board'));
      await tester.pumpAndSettle();

      expect(
        fakeAdapter.requests.map((request) => '${request.method} ${request.path}'),
        ['GET /api/boards', 'POST /api/boards', 'GET /api/boards'],
      );
      expect(find.text('Getting Started'), findsOneWidget);
      expect(find.text('Second Board'), findsOneWidget);
    },
  );
}
